Repository web3/web3.js, pull requests merged in 2019-06, with the labels that each got.

#2856 EIP-1193 updates
  packages/web3-providers/src/resolvers/ProviderResolver.js
  packages/web3-providers/tests/src/resolvers/ProviderResolverTest.js
Labels: bug

#2862 Fix JSON-RPC response validation
  packages/web3-providers/src/providers/Web3EthereumProvider.js
  packages/web3-providers/tests/src/providers/Web3EthereumProviderTest.js
Labels: bug

#2870 batch request fixed for SendRawTransactionMethod
  packages/web3-providers/src/batch-request/BatchRequest.js
  packages/web3-providers/tests/src/batch-request/BatchRequestTest.js
Labels: bug

#2871 non-static type property added
  packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js
  packages/web3-core-method/tests/lib/methods/transaction/AbstractObservedTransactionMethodTest.js
Labels: enhancement

#2855 WebsocketProvider improvements
  packages/web3-core-method/src/observers/TransactionObserver.js
  packages/web3-core-subscriptions/lib/subscriptions/AbstractSubscription.js
  packages/web3-core-subscriptions/tests/lib/subscriptions/AbstractSubscriptionTest.js
  packages/web3-core-subscriptions/tests/src/subscriptions/eth/LogSubscriptionTest.js
  packages/web3-providers/lib/providers/AbstractSocketProvider.js
  packages/web3-providers/src/batch-request/BatchRequest.js
  packages/web3-providers/src/providers/IpcProvider.js
  packages/web3-providers/src/providers/WebsocketProvider.js
  packages/web3-providers/tests/lib/providers/AbstractSocketProviderTest.js
Labels: bug

#2888 Changelog added and github folder created
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  CHANGELOG.md
Labels: 2.x, enhancement, in progress

#2893 Missing YAML properties added to the issue templates
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE/release.md
Labels: enhancement

#2889 Changelog to 1.x branch added
  CHANGELOG.md
Labels: 1.x, enhancement, in progress

#2911 Proxies updated
  packages/web3-core-method/src/proxy/MethodProxy.js
  packages/web3-eth-contract/src/proxies/EventSubscriptionsProxy.js
  packages/web3-eth-contract/src/proxies/MethodsProxy.js
Labels: 2.x, enhancement
