Repository web3/web3.js, pull requests merged in 2019-08, with the labels that each got.

#2898 web3js dependency on webpack to run on browser
  docs/getting-started.rst
Labels: 2.x, documentation

#2914 U Update the document of `sendSignedTransaction`.
  docs/web3-eth.rst
Labels: 1.x, documentation

#2931 U Update the document of `sendSignedTransaction`.
  docs/web3-eth.rst
Labels: 2.x, documentation

#2955 Providers Improvements
  CHANGELOG.md
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-eth-accounts/tests/src/models/AccountTest.js
  packages/web3-providers/lib/providers/AbstractSocketProvider.js
  packages/web3-providers/src/providers/MetamaskProvider.js
  packages/web3-providers/src/providers/MistEthereumProvider.js
  packages/web3-providers/src/providers/WebsocketProvider.js
  packages/web3-providers/tests/lib/providers/AbstractSocketProviderTest.js
  packages/web3-providers/tests/src/providers/Web3EthereumProviderTest.js
Labels: 2.x, bug, enhancement

#2927 Fix removeAllSocketListeners method in Web3EthereumProvider
  packages/web3-providers/src/providers/MetamaskProvider.js
  packages/web3-providers/src/providers/Web3EthereumProvider.js
  packages/web3-providers/tests/src/providers/MetamaskProviderTest.js
  packages/web3-providers/tests/src/providers/Web3EthereumProviderTest.js
Labels: 2.x, enhancement, in progress

#2989 stripHexPrefix fixed
  packages/web3-utils/src/Utils.js
Labels: 2.x, bug

#2960 change listener added to Contract events
  CHANGELOG.md
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-admin/package-lock.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/src/subscriptions/AllEventsLogSubscription.js
  packages/web3-eth-contract/src/subscriptions/EventLogSubscription.js
  packages/web3-eth-contract/tests/src/subscriptions/AllEventsLogSubscriptionTest.js
  packages/web3-eth-contract/tests/src/subscriptions/EventLogSubscriptionTest.js
  packages/web3-eth-debug/package-lock.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-miner/package-lock.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-txpool/package-lock.json
  packages/web3-eth/package-lock.json
  packages/web3-net/package-lock.json
  packages/web3-providers/package-lock.json
  packages/web3-shh/package-lock.json
Labels: 2.x, enhancement

#2983 WebsocketProviderOptions has been adjusted
  CHANGELOG.md
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-providers/tests/src/factories/ProvidersModuleFactoryTest.js
  packages/web3-providers/types/index.d.ts
Labels: 2.x, enhancement

#2993 Error handling fixed with callbacks for BatchRequests
  CHANGELOG.md
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-providers/src/batch-request/BatchRequest.js
  packages/web3-providers/tests/src/batch-request/BatchRequestTest.js
Labels: 2.x, bug

#2994 Websocket provider reconnecting timeout and reconnection event added
  CHANGELOG.md
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-providers/src/providers/WebsocketProvider.js
  packages/web3-providers/tests/src/providers/WebsocketProviderTest.js
Labels: 2.x, enhancement

#2995 websocket dependency updated
  CHANGELOG.md
  packages/web3-providers/package.json
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-providers/src/providers/Web3EthereumProvider.js
  packages/web3-providers/src/providers/WebsocketProvider.js
  packages/web3-providers/tests/src/batch-request/BatchRequestTest.js
  packages/web3-providers/tests/src/factories/ProvidersModuleFactoryTest.js
  packages/web3-providers/tests/src/providers/Web3EthereumProviderTest.js
  packages/web3-providers/tests/src/providers/WebsocketProviderTest.js
  packages/web3-providers/types/index.d.ts
Labels: 2.x, enhancement

#3003 fix net documentation
  docs/include_package-net.rst
Labels: 2.x, documentation

#3007 clearSubscriptions method in AbstractSocketProvider fixed
  CHANGELOG.md
  packages/web3-core-method/types/index.d.ts
  packages/web3-core-method/types/tests/abstract-method-tests.ts
  packages/web3-core/src/AbstractWeb3Module.js
  packages/web3-providers/lib/providers/AbstractSocketProvider.js
  packages/web3-providers/package-lock.json
  packages/web3-providers/tests/lib/providers/AbstractSocketProviderTest.js
Labels: 2.x, bug

#3004 Release - 1.2.1
  CHANGELOG.md
  dist/web3.min.js
  lerna-debug.log
  lerna.json
  package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package.json
  packages/web3/package.json
Labels: 1.x, release

#3006 Release - 2.0.0-alpha.1
  CHANGELOG.md
  lerna.json
  package-lock.json
  package.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-admin/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-debug/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-miner/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth-txpool/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers/lib/providers/AbstractSocketProvider.js
  packages/web3-providers/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 2.x, release

#2887 correct handling of xmlhttprequest network errors
  CHANGELOG.md
  packages/web3-providers/package-lock.json
  packages/web3-providers/src/providers/HttpProvider.js
  packages/web3-providers/tests/src/providers/HttpProviderTest.js
Labels: 2.x, bug

#3008 instant-mine option added
  .travis.yml
  CHANGELOG.md
  packages/web3-core-method/lib/factories/AbstractMethodFactory.js
  packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js
  packages/web3-core-method/lib/observers/AbstractTransactionObserver.js
  packages/web3-core-method/src/index.js
  packages/web3-core-method/src/methods/transaction/EthSendTransactionMethod.js
  packages/web3-core-method/src/methods/transaction/SendRawTransactionMethod.js
  packages/web3-core-method/src/methods/transaction/SendTransactionMethod.js
  packages/web3-core-method/src/observers/HttpTransactionObserver.js
  packages/web3-core-method/src/observers/SocketTransactionObserver.js
  packages/web3-core-method/src/observers/TransactionObserver.js
  packages/web3-core-method/tests/__mocks__/Observer.js
  packages/web3-core-method/tests/lib/factories/AbstractMethodFactoryTest.js
  packages/web3-core-method/tests/lib/methods/transaction/AbstractObservedTransactionMethodTest.js
  packages/web3-core-method/tests/lib/observers/AbstractTransactionObserverTest.js
  packages/web3-core-method/tests/src/methods/transaction/EthSendTransactionMethodTest.js
  packages/web3-core-method/tests/src/observers/HttpTransactionObserverTest.js
  packages/web3-core-method/tests/src/observers/SocketTransactionObserverTest.js
  packages/web3-core-method/tests/src/observers/TransactionObserverTest.js
  packages/web3-core/src/AbstractWeb3Module.js
  packages/web3-core/tests/src/AbstractWeb3ModuleTest.js
  packages/web3-core/types/index.d.ts
  packages/web3-eth-contract/src/AbstractContract.js
  packages/web3-eth-contract/src/factories/MethodFactory.js
  packages/web3-eth-contract/src/methods/ContractDeployMethod.js
  packages/web3-eth-contract/src/methods/SendContractMethod.js
  packages/web3-eth-contract/tests/src/AbstractContractTest.js
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
  packages/web3-eth-ens/src/Ens.js
  packages/web3-eth-ens/src/contracts/Registry.js
  packages/web3-eth-ens/tests/src/EnsTest.js
  packages/web3-eth-ens/tests/src/contracts/RegistryTest.js
  packages/web3-eth-ens/types/index.d.ts
  packages/web3-eth-ens/types/tests/ens-test.ts
  packages/web3-eth/src/Eth.js
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: 2.x, enhancement

#3012 blockNumber check in transaction observers fixed
  CHANGELOG.md
  packages/web3-core-method/src/observers/HttpTransactionObserver.js
  packages/web3-core-method/src/observers/SocketTransactionObserver.js
  packages/web3-core-method/tests/src/observers/HttpTransactionObserverTest.js
  packages/web3-core-method/tests/src/observers/SocketTransactionObserverTest.js
Labels: 2.x, bug

#3015 Fix accessing event.name where event is undefined
  .travis.yml
  packages/web3-eth-contract/src/index.js
Labels: 1.x, bug

#3019 module path in package.json fixed
  packages/web3-core/package.json
Labels: 2.x, bug

#3017 npm run dev not exist in package.json
  README.md
Labels: 2.x, documentation

#3025 Update getting-started.rst
  docs/getting-started.rst
Labels: 1.x, documentation

#3011 Formatting fixes - README.md prettified
  README.md
Labels: 1.x, documentation
