Repository web3/web3.js, pull requests merged in 2019-05, with the labels that each got.

#2765 Setting of a provider after initiating a Web3 object without a provider fixed
  packages/web3-core/src/AbstractWeb3Module.js
  packages/web3-core/tests/src/AbstractWeb3ModuleTest.js
Labels: bug

#2767 [Quorum] Fix #2766, timestamp is not present on a Quorum node
  packages/web3-core-helpers/src/Formatters.js
  packages/web3-core-helpers/tests/src/Formatters/OutputBlockFormatterTest.js
Labels: enhancement, in progress

#2772 LogSubscription extended with changed event
  docs/web3-eth-subscribe.rst
  packages/web3-core-subscriptions/src/subscriptions/eth/LogSubscription.js
  packages/web3-core-subscriptions/tests/src/subscriptions/eth/LogSubscriptionTest.js
Labels: bug

#2774 Release - 1.0.0-beta.54
  docs/include_web3-module-abstract-method-class-reference.rst
  docs/index.rst
  docs/web3-core-method.rst
  lerna.json
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-admin/package-lock.json
  packages/web3-eth-admin/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-debug/package-lock.json
  packages/web3-eth-debug/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-miner/package-lock.json
  packages/web3-eth-miner/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth-txpool/package-lock.json
  packages/web3-eth-txpool/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers/package-lock.json
  packages/web3-providers/package.json
  packages/web3-providers/tests/src/providers/WebsocketProviderTest.js
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: release

#2783 Error handling for the HttpProvider improved
  packages/web3-providers/src/providers/HttpProvider.js
  packages/web3-providers/tests/src/providers/HttpProviderTest.js
Labels: bug

#2784 Fixed typo
  docs/web3-eth-ens.rst
Labels: documentation

#2780 Dependencies of the accounts module updated
  packages/web3-core-method/package-lock.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-eth-accounts/tests/src/models/AccountTest.js
  packages/web3-providers/tests/src/providers/HttpProviderTest.js
Labels: enhancement

#2788 Dependencies updated
  packages/web3-bzz/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-miner/package-lock.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-txpool/package-lock.json
  packages/web3-eth/package-lock.json
  packages/web3-net/package-lock.json
  packages/web3-providers/package-lock.json
  packages/web3-providers/package.json
  packages/web3-providers/types/tests/batch-request-test.ts
  packages/web3-shh/package-lock.json
  packages/web3-utils/package-lock.json
  packages/web3/package.json
  packages/web3/rollup.config.js
Labels: types

#2787 Updated doc for contenthash
  docs/web3-eth-ens.rst
Labels: documentation

#2791 outputBlockFormatter updated
  docs/web3-eth.rst
  packages/web3-core-helpers/src/Formatters.js
  packages/web3-core-helpers/tests/src/Formatters/OutputBlockFormatterTest.js
  packages/web3-eth/types/index.d.ts
Labels: bug

#2793 utils.isBN fixed
  packages/web3-utils/src/Utils.js
Labels: bug

#2794 randomHex fixed
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3-utils/src/index.js
Labels: bug

#2795 BZZ module removed
  docs/getting-started.rst
  docs/include_package-core.rst
  docs/include_package-net.rst
  docs/index.rst
  docs/web3-bzz.rst
  docs/web3-net.rst
  docs/web3.rst
  packages/web3-bzz/README.md
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-bzz/rollup.config.js
  packages/web3-bzz/src/Bzz.js
  packages/web3-bzz/src/index.js
  packages/web3-bzz/types/index.d.ts
  packages/web3-bzz/types/tests/bzz-test.ts
  packages/web3-bzz/types/tsconfig.json
  packages/web3-bzz/types/tslint.json
  packages/web3/package.json
  packages/web3/src/Web3.js
  packages/web3/tests/src/Web3Test.js
  packages/web3/types/index.d.ts
  packages/web3/types/tests/web3-test.ts
Labels: bug

#2799 Module API documentation improved
  docs/web3-core.rst
  docs/web3-module.rst
Labels: documentation

#2803 Release - 1.0.0-beta.55
  .travis.yml
  docs/index.rst
  docs/web3-bzz.rst
  docs/web3-eth.rst
  docs/web3-module.rst
  lerna.json
  package-lock.json
  package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/tests/src/models/AccountTest.js
  packages/web3-eth-admin/package-lock.json
  packages/web3-eth-admin/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-debug/package-lock.json
  packages/web3-eth-debug/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-miner/package-lock.json
  packages/web3-eth-miner/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth-txpool/package-lock.json
  packages/web3-eth-txpool/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers/package-lock.json
  packages/web3-providers/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
  packages/web3/rollup.config.js
Labels: release

#2806 fix typo
  docs/web3-module.rst
Labels: documentation

#2785 Fix typo in `toChecksumAddress` examples
  docs/web3-utils.rst
Labels: documentation

#2815 Fix error on contract method proxy when method parameter is null.
  packages/web3-eth-contract/src/proxies/MethodsProxy.js
  packages/web3-eth-contract/tests/src/proxies/MethodsProxyTest.js
Labels: bug

#2820 End-of-Life node versions
  .travis.yml
  README.md
  package-lock.json
  rollup.config.js
Labels: enhancement

#2836 fix to export isBigNumber
  packages/web3-utils/src/index.js
Labels: bug

#2838 SyncingSubscription fix
  packages/web3-core-subscriptions/src/subscriptions/eth/SyncingSubscription.js
  packages/web3-core-subscriptions/tests/src/subscriptions/eth/SyncingSubscriptionTest.js
  packages/web3-eth/types/index.d.ts
Labels: bug

#2844 fix - 2819 - Block transactions on some instances returns an array of…
  packages/web3-eth/types/index.d.ts
Labels: types

#2796 Fixes BatchRequest for locally signed transactions
  package-lock.json
  package.json
  packages/web3-core-method/src/methods/transaction/EthSendTransactionMethod.js
  packages/web3-core-method/tests/src/methods/transaction/EthSendTransactionMethodTest.js
  packages/web3-core-subscriptions/tests/src/subscriptions/eth/SyncingSubscriptionTest.js
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-providers/src/batch-request/BatchRequest.js
  packages/web3-providers/tests/src/batch-request/BatchRequestTest.js
  packages/web3-providers/types/index.d.ts
  packages/web3-providers/types/tests/batch-request-test.ts
  packages/web3/src/Web3.js
Labels: bug

#2847 Resolve parity nodes invalid "eth_getBlockByNumber" JSONRPC call
  packages/web3-core-method/src/observers/TransactionObserver.js
Labels: enhancement
