Repository web3/web3.js, pull requests merged in 2019-03, with the labels that each got.

#2435 Testing
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  docs/web3-eth-abi.rst
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-method/package-lock.json
  packages/web3-core/package-lock.json
  packages/web3-eth-abi/src/AbiCoder.js
  packages/web3-eth-abi/src/factories/AbiModuleFactory.js
  packages/web3-eth-abi/tests/AbiCoderTest.js
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/src/AbstractContract.js
  packages/web3-eth-contract/src/factories/ContractModuleFactory.js
  packages/web3-eth-contract/src/index.js
  packages/web3-eth-contract/src/mappers/MethodOptionsMapper.js
  packages/web3-eth-contract/src/methods/CallContractMethod.js
  packages/web3-eth-contract/src/methods/ContractDeployMethod.js
  packages/web3-eth-contract/src/proxies/EventSubscriptionsProxy.js
  packages/web3-eth-contract/src/proxies/MethodsProxy.js
  packages/web3-eth-contract/tests/src/AbstractContractTest.js
  packages/web3-eth-contract/tests/src/methods/CallContractMethodTest.js
  packages/web3-eth-contract/tests/src/methods/ContractDeployMethodTest.js
  packages/web3-eth-contract/tests/src/proxies/EventSubscriptionsProxyTest.js
  packages/web3-eth-contract/tests/src/proxies/MethodsProxyTest.js
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-eth/src/Eth.js
  packages/web3-eth/tests/src/EthTest.js
  packages/web3-net/package-lock.json
  packages/web3-shh/package-lock.json
  packages/web3/package-lock.json
Labels: bug, enhancement

#2437 DecodeLog improvements
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/src/AbiCoder.js
  packages/web3-eth-abi/src/factories/AbiModuleFactory.js
  packages/web3-eth-abi/src/index.js
  packages/web3-eth-abi/tests/AbiCoderTest.js
  packages/web3-eth-abi/tests/factories/AbiModuleFactoryTest.js
  packages/web3-eth-contract/src/methods/CallContractMethod.js
  packages/web3-eth-contract/tests/src/methods/CallContractMethodTest.js
Labels: bug, enhancement, in progress

#2439 decodeLog fixed for non-indexed parameters
  packages/web3-eth-abi/src/AbiCoder.js
  packages/web3-eth-abi/tests/AbiCoderTest.js
Labels: bug

#2451 provider resolving fixed
  packages/web3-core/src/AbstractWeb3Module.js
  packages/web3-core/tests/src/AbstractWeb3ModuleTest.js
  packages/web3-core/types/index.d.ts
  packages/web3-eth-accounts/src/Accounts.js
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-contract/src/AbstractContract.js
  packages/web3-eth-contract/src/factories/ContractModuleFactory.js
  packages/web3-eth-contract/src/index.js
  packages/web3-eth-ens/src/Ens.js
  packages/web3-eth-ens/src/contracts/Registry.js
  packages/web3-eth-ens/src/factories/EnsModuleFactory.js
  packages/web3-eth-ens/src/index.js
  packages/web3-eth-personal/src/Personal.js
  packages/web3-eth-personal/src/factories/PersonalModuleFactory.js
  packages/web3-eth-personal/src/index.js
  packages/web3-eth/src/Eth.js
  packages/web3-eth/src/index.js
  packages/web3-net/src/Network.js
  packages/web3-net/src/factories/NetworkModuleFactory.js
  packages/web3-net/src/index.js
  packages/web3-providers/lib/providers/AbstractSocketProvider.js
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-providers/src/index.js
  packages/web3-providers/src/providers/MistEthereumProvider.js
  packages/web3-providers/src/providers/Web3EthereumProvider.js
  packages/web3-providers/src/resolvers/ProviderResolver.js
  packages/web3-providers/tests/src/factories/ProvidersModuleFactoryTest.js
  packages/web3-providers/tests/src/providers/Web3EthereumProviderTest.js
  packages/web3-providers/tests/src/resolvers/ProviderResolverTest.js
  packages/web3-shh/src/Shh.js
  packages/web3-shh/src/factories/ShhModuleFactory.js
  packages/web3-shh/src/index.js
  packages/web3/src/Web3.js
Labels: bug

#2450 Update ISSUE_TEMPLATE to be more descriptive
  ISSUE_TEMPLATE.md
Labels: enhancement

#2456 Contract method call decoding fixed
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-abi/src/AbiCoder.js
  packages/web3-eth-abi/src/index.js
  packages/web3-eth-abi/tests/AbiCoderTest.js
  packages/web3-eth-contract/src/methods/CallContractMethod.js
  packages/web3-eth-contract/tests/src/methods/CallContractMethodTest.js
Labels: bug

#2455 eth.signTransaction documentation updated
  docs/web3-eth.rst
Labels: documentation

#2464 TransactionSigner handling for Accounts improved.
  packages/web3-eth/src/Eth.js
  packages/web3-eth/src/index.js
  packages/web3-eth/tests/src/EthTest.js
Labels: bug

#2463 NewHeadsWatcher updated for CustomProvider
  packages/web3-core-method/src/watchers/NewHeadsWatcher.js
  packages/web3-core-method/tests/__mocks__/CustomProvider.js
  packages/web3-core-method/tests/src/watchers/NewHeadsWatcherTest.js
  packages/web3-core/types/index.d.ts
  packages/web3-eth-accounts/types/index.d.ts
Labels: bug

#2458 Filter handling for contract event logs fixed in EventFilterEncoder
  packages/web3-eth-contract/src/AbstractContract.js
  packages/web3-eth-contract/src/encoders/EventFilterEncoder.js
  packages/web3-eth-contract/src/mappers/EventOptionsMapper.js
  packages/web3-eth-contract/src/methods/AllPastEventLogsMethod.js
  packages/web3-eth-contract/src/methods/PastEventLogsMethod.js
Labels: bug

#2516 `objects` to `any` on typing's return + dtslint fix + general test fixes
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-method/types/index.d.ts
  packages/web3-core-method/types/tests/abstract-method-tests.ts
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-core/types/index.d.ts
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers/package-lock.json
  packages/web3-providers/package.json
  packages/web3-providers/types/index.d.ts
  packages/web3-providers/types/tests/abstract-socket-provider-test.ts
  packages/web3-providers/types/tests/batch-request-test.ts
  packages/web3-providers/types/tests/http-provider-test.ts
  packages/web3-providers/types/tests/provider-module-factory-test.ts
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/get-signature-params-test.ts
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: types

#2479 Separate Transaction and TransactionConfig in typings
  packages/web3-core/types/index.d.ts
  packages/web3-eth-accounts/types/index.d.ts
  packages/web3-eth-personal/types/index.d.ts
  packages/web3-eth/types/index.d.ts
Labels: types

#2478 AbiInput and AbiOutput interface update
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/json-interface-method-to-string-test.ts
Labels: types

#2471 `Sign` needed to have a signature on typing's + fix incorrect docs
  docs/web3-eth-accounts.rst
  packages/web3-eth-accounts/types/index.d.ts
Labels: types

#2510 Unhandled promise rejection of EthSendTransactionMethod fixed.
  .travis.yml
  packages/web3-core-method/src/methods/transaction/EthSendTransactionMethod.js
  packages/web3-core-method/tests/src/methods/transaction/EthSendTransactionMethodTest.js
Labels: bug

#2511 Transaction revert handling improved/fixed
  packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js
  packages/web3-core-method/tests/lib/methods/transaction/AbstractObservedTransactionMethodTest.js
  packages/web3-eth-contract/src/methods/CallContractMethod.js
  packages/web3-eth-contract/src/methods/SendContractMethod.js
Labels: bug

#2512 Parameters amount of NewKeyPairMethod fixed.
  packages/web3-core-method/src/methods/shh/NewKeyPairMethod.js
  packages/web3-core-method/tests/src/methods/shh/GenericShhMethodTest.js
Labels: bug

#2513 MethodOptionsValidator fixed for payable methods.
  packages/web3-eth-contract/src/validators/MethodOptionsValidator.js
  packages/web3-eth-contract/tests/src/validators/MethodOptionsValidatorTest.js
Labels: bug

#2521 ProviderResolver is now minification save
  packages/web3-providers/src/resolvers/ProviderResolver.js
Labels: bug

#2522 IpcProvider updated
  packages/web3-providers/lib/providers/AbstractSocketProvider.js
  packages/web3-providers/package.json
  packages/web3-providers/src/providers/CustomProvider.js
  packages/web3-providers/src/providers/HttpProvider.js
  packages/web3-providers/src/providers/IpcProvider.js
  packages/web3-providers/src/providers/MetamaskProvider.js
  packages/web3-providers/src/providers/MistEthereumProvider.js
  packages/web3-providers/src/providers/Web3EthereumProvider.js
  packages/web3-providers/src/providers/WebsocketProvider.js
  packages/web3-providers/tests/lib/providers/AbstractSocketProviderTest.js
  packages/web3-providers/tests/src/providers/IpcProviderTest.js
  packages/web3-providers/tests/src/providers/MetamaskProviderTest.js
  packages/web3-providers/tests/src/providers/MistEthereumProviderTest.js
  packages/web3-providers/tests/src/providers/WebsocketProviderTest.js
Labels: bug

#2523 Contract options handling improved
  packages/web3-eth-contract/src/AbstractContract.js
  packages/web3-eth-contract/src/proxies/MethodsProxy.js
  packages/web3-eth-contract/tests/src/AbstractContractTest.js
  packages/web3-eth-contract/tests/src/proxies/MethodsProxyTest.js
  packages/web3-eth/src/Eth.js
  packages/web3-eth/tests/src/EthTest.js
Labels: bug

#2524 Module factory methods fixed
  packages/web3-bzz/package-lock.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/types/index.d.ts
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core/package-lock.json
  packages/web3-core/types/index.d.ts
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/src/index.js
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-accounts/types/index.d.ts
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/src/index.js
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/src/index.js
  packages/web3-eth-ens/types/index.d.ts
  packages/web3-eth-ens/types/tests/ens-test.ts
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/src/index.js
  packages/web3-eth-personal/types/index.d.ts
  packages/web3-eth-personal/types/tests/personal-tests.ts
  packages/web3-eth/package-lock.json
  packages/web3-eth/src/index.js
  packages/web3-eth/types/index.d.ts
  packages/web3-net/package-lock.json
  packages/web3-net/src/index.js
  packages/web3-net/types/index.d.ts
  packages/web3-providers/package-lock.json
  packages/web3-providers/src/index.js
  packages/web3-providers/src/providers/IpcProvider.js
  packages/web3-shh/package-lock.json
  packages/web3-shh/src/index.js
  packages/web3-shh/types/index.d.ts
  packages/web3-utils/package-lock.json
  packages/web3/package-lock.json
Labels: bug

#2526 Accounts module fixes and improvements
  packages/web3-eth-accounts/jest.config.js
  packages/web3-eth-accounts/src/Accounts.js
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-accounts/src/models/Wallet.js
  packages/web3-eth-accounts/tests/src/AccountsTest.js
  packages/web3-eth-accounts/tests/src/models/WalletTest.js
  packages/web3-eth-ens/src/index.js
  packages/web3-eth/src/Eth.js
  packages/web3-providers/package-lock.json
Labels: bug

#2530 Ens network detection fixed
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/src/models/Wallet.js
  packages/web3-eth-ens/src/contracts/Registry.js
  packages/web3-eth-ens/src/index.js
  packages/web3-eth-ens/tests/src/contracts/RegistryTest.js
  packages/web3-eth/src/Eth.js
  packages/web3-net/src/Network.js
  packages/web3-net/src/factories/MethodFactory.js
  packages/web3-net/tests/src/NetworkTest.js
  packages/web3-net/tests/src/factories/MethodFactoryTest.js
Labels: bug

#2535 Contract event subscriptions filter fixed
  packages/web3-eth-contract/src/factories/MethodFactory.js
  packages/web3-eth-contract/src/mappers/AllEventsOptionsMapper.js
  packages/web3-eth-contract/src/mappers/EventOptionsMapper.js
  packages/web3-eth-contract/src/methods/AllPastEventLogsMethod.js
  packages/web3-eth-contract/src/methods/PastEventLogsMethod.js
  packages/web3-eth-contract/tests/src/mappers/AllEventsOptionsMapperTest.js
  packages/web3-eth-contract/tests/src/mappers/EventOptionsMapperTest.js
  packages/web3-eth-contract/tests/src/methods/AllPastEventLogsMethodTest.js
  packages/web3-eth-contract/tests/src/methods/PastEventLogsMethodTest.js
Labels: bug

#2545 IpcProvider chunks handling fix
  packages/web3-providers/src/providers/IpcProvider.js
  packages/web3-providers/tests/src/providers/IpcProviderTest.js
Labels: bug

#2556 EventOptions interface types updated
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
Labels: types

#2557 DeployTransactionResponse renamed to ContractSendMethod
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
Labels: types

#2564 XMLHttpRequest options handling improved
  packages/web3-providers/package-lock.json
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-providers/src/providers/HttpProvider.js
  packages/web3-providers/tests/src/factories/ProvidersModuleFactoryTest.js
  packages/web3-providers/tests/src/providers/HttpProviderTest.js
  packages/web3-providers/types/index.d.ts
  packages/web3-providers/types/tests/http-provider-test.ts
Labels: bug

#2566 MethodFactory fixed and test added
  packages/web3-eth-accounts/src/factories/MethodFactory.js
  packages/web3-eth-accounts/tests/src/factories/MethodFactoryTest.js
Labels: bug

#2567 Parameters amount in EcRecoverMethod fixed
  jest.preprocessor.js
  packages/web3-core-method/src/methods/personal/EcRecoverMethod.js
  packages/web3-core-method/src/methods/personal/PersonalSignMethod.js
  packages/web3-core-method/tests/src/methods/personal/EcRecoverMethodTest.js
  packages/web3-core-method/tests/src/methods/personal/PersonalSignMethodTest.js
Labels: bug

#2572 Account model fixed
  packages/web3-eth-accounts/src/models/Account.js
Labels: bug

#2568 Contract calls should return a BigNumber object
  packages/web3-eth-abi/src/index.js
Labels: enhancement

#2529 Use genuine BN type
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-core/types/index.d.ts
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/ascii-to-hex-test.ts
  packages/web3-utils/types/tests/bytes-to-hex-test.ts
  packages/web3-utils/types/tests/check-address-checksum-test.ts
  packages/web3-utils/types/tests/from-ascii-test.ts
  packages/web3-utils/types/tests/from-decimal-test.ts
  packages/web3-utils/types/tests/from-utf8-test.ts
  packages/web3-utils/types/tests/from-wei-test.ts
  packages/web3-utils/types/tests/get-signature-params-test.ts
  packages/web3-utils/types/tests/get-unit-value-test.ts
  packages/web3-utils/types/tests/hex-to-ascii-test.ts
  packages/web3-utils/types/tests/hex-to-bytes-test.ts
  packages/web3-utils/types/tests/hex-to-number-string-test.ts
  packages/web3-utils/types/tests/hex-to-number-test.ts
  packages/web3-utils/types/tests/hex-to-string-test.ts
  packages/web3-utils/types/tests/hex-to-utf8-test.ts
  packages/web3-utils/types/tests/is-address-test.ts
  packages/web3-utils/types/tests/is-big-number-test.ts
  packages/web3-utils/types/tests/is-bloom-test.ts
  packages/web3-utils/types/tests/is-bn-test.ts
  packages/web3-utils/types/tests/is-hex-strict-test.ts
  packages/web3-utils/types/tests/is-hex-test.ts
  packages/web3-utils/types/tests/is-topic-test.ts
  packages/web3-utils/types/tests/keccak256-test.ts
  packages/web3-utils/types/tests/left-pad-test.ts
  packages/web3-utils/types/tests/number-to-hex-test.ts
  packages/web3-utils/types/tests/pad-left-test.ts
  packages/web3-utils/types/tests/pad-right-test.ts
  packages/web3-utils/types/tests/random-hex-test.ts
  packages/web3-utils/types/tests/right-pad-test.ts
  packages/web3-utils/types/tests/sha3-test.ts
  packages/web3-utils/types/tests/solidity-sha3-test.ts
  packages/web3-utils/types/tests/string-to-hex-test.ts
  packages/web3-utils/types/tests/test-address-test.ts
  packages/web3-utils/types/tests/test-topic-test.ts
  packages/web3-utils/types/tests/to-ascii-test.ts
  packages/web3-utils/types/tests/to-check-sum-address-test.ts
  packages/web3-utils/types/tests/to-decimal-test.ts
  packages/web3-utils/types/tests/to-hex-test.ts
  packages/web3-utils/types/tests/to-twos-compement-test.ts
  packages/web3-utils/types/tests/to-utf8-test.ts
  packages/web3-utils/types/tests/to-wei-test.ts
  packages/web3-utils/types/tests/utf8-to-hex-test.ts
Labels: types

#2574 Dependency handling in SubscriptionsFactory fixed
  packages/web3-core-method/src/methods/personal/PersonalSignMethod.js
  packages/web3-eth-abi/src/index.js
  packages/web3-eth/src/factories/SubscriptionsFactory.js
  packages/web3-providers/tests/src/factories/ProvidersModuleFactoryTest.js
  packages/web3-providers/tests/src/providers/HttpProviderTest.js
Labels: bug

#2575 Types for HttpProvider options updated
  packages/web3-providers/types/index.d.ts
Labels: types

#2585 eth.subscribe types improvement
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: types

#2580 Local signing fixed
  packages/web3-bzz/package-lock.json
  packages/web3-core-method/lib/factories/AbstractMethodFactory.js
  packages/web3-core-method/src/methods/transaction/EthSendTransactionMethod.js
  packages/web3-core-method/tests/lib/factories/AbstractMethodFactoryTest.js
  packages/web3-core-method/tests/src/methods/transaction/EthSendTransactionMethodTest.js
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/src/Accounts.js
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-eth-accounts/src/models/Wallet.js
  packages/web3-eth-accounts/tests/src/AccountsTest.js
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-eth/src/signers/TransactionSigner.js
  packages/web3-eth/tests/src/signers/TransactionSignerTest.js
  packages/web3-net/package-lock.json
  packages/web3-shh/package-lock.json
  packages/web3-utils/package-lock.json
Labels: bug

#2589 Error handling for WebsocketProvider fixed
  packages/web3-providers/src/providers/WebsocketProvider.js
  packages/web3-providers/tests/src/providers/WebsocketProviderTest.js
Labels: bug

#2592 Breaking change of Wallet class fixed and test updated
  packages/web3-eth-accounts/src/models/Wallet.js
  packages/web3-eth-accounts/tests/src/models/WalletTest.js
Labels: bug

#2594 Update AbstractObservedTransaction to use formatted receipt.status
  packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js
  packages/web3-core-method/tests/lib/methods/transaction/AbstractObservedTransactionMethodTest.js
Labels: bug

#2598 Release - v1.0.0-beta.51
  package.json
  packages/web3-core-helpers/README.md
  packages/web3-core-helpers/src/Formatters.js
  packages/web3-core-method/lib/factories/AbstractMethodFactory.js
  packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js
  packages/web3-core-subscriptions/README.md
  packages/web3-eth-accounts/README.md
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-contract/src/AbstractContract.js
  packages/web3-eth-contract/tests/src/AbstractContractTest.js
  packages/web3-eth-ens/README.md
  packages/web3-eth-personal/README.md
  packages/web3-eth-personal/src/index.js
  packages/web3-eth/README.md
  packages/web3-eth/src/methods/EthSignMethod.js
  packages/web3-net/README.md
  packages/web3-providers/README.md
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-shh/README.md
  packages/web3/package.json
Labels: release

#2593 fix websocket provider basic auth handling
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-providers/tests/src/factories/ProvidersModuleFactoryTest.js
Labels: bug

#2608 Invalid bytes string error fixed
  packages/web3-eth-contract/src/methods/CallContractMethod.js
  packages/web3-eth-contract/tests/src/methods/CallContractMethodTest.js
Labels: bug
