Repository web3/web3.js, pull requests merged in 2019-01, with the labels that each got.

#2178 Add missing exports
  docs/web3-utils.rst
  package-lock.json
  packages/web3-utils/src/Utils.js
  packages/web3-utils/src/index.js
  packages/web3-utils/tests/src/UtilsTest.js
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/get-signature-params-test.ts
Labels: enhancement

#2148 [documentation] Changing parameters of methods.myMethod.call()
  docs/web3-eth-contract.rst
Labels: documentation

#2088 [Documentation] Fix return values of generateSymKeyFromPassword function
  docs/web3-shh.rst
Labels: documentation

#2008 Add description for importRawKey()
  docs/web3-eth-personal.rst
Labels: documentation

#1602 jsonInterface data type should be consistent
  docs/web3-eth-contract.rst
Labels: documentation

#2209 Deep cloned method and subscription arguments.
  packages/web3-bzz/src/Bzz.js
  packages/web3-core-helpers/src/Formatters.js
  packages/web3-core-method/lib/methods/AbstractMethod.js
  packages/web3-core-method/src/methods/transaction/SendTransactionMethod.js
  packages/web3-core-method/src/proxy/MethodProxy.js
  packages/web3-core-method/src/validators/TransactionReceiptValidator.js
  packages/web3-core-subscriptions/lib/subscriptions/AbstractSubscription.js
  packages/web3-core-subscriptions/src/factories/SubscriptionsFactory.js
  packages/web3-core/src/AbstractWeb3Module.js
  packages/web3-eth-abi/src/AbiCoder.js
  packages/web3-eth-abi/src/factories/AbiModuleFactory.js
  packages/web3-eth-accounts/src/Accounts.js
  packages/web3-eth-contract/src/encoders/EventFilterEncoder.js
  packages/web3-eth-contract/src/mappers/AbiMapper.js
  packages/web3-eth-contract/src/mappers/EventOptionsMapper.js
  packages/web3-eth-contract/src/methods/SendContractMethod.js
  packages/web3-eth-contract/src/models/AbiItemModel.js
  packages/web3-eth-contract/src/proxies/EventSubscriptionsProxy.js
  packages/web3-eth-contract/src/proxies/MethodsProxy.js
  packages/web3-eth-ens/src/Ens.js
  packages/web3-eth-ens/src/contracts/Registry.js
  packages/web3-net/src/Network.js
  packages/web3-providers/lib/providers/AbstractSocketProvider.js
  packages/web3-providers/src/batch-request/BatchRequest.js
  packages/web3-providers/src/providers/IpcProvider.js
  packages/web3-providers/src/providers/WebsocketProvider.js
  packages/web3-providers/src/resolvers/ProviderResolver.js
  packages/web3-providers/src/validators/JsonRpcResponseValidator.js
  packages/web3-utils/src/SoliditySha3.js
  packages/web3-utils/src/Utils.js
  packages/web3-utils/src/index.js
  packages/web3-utils/tests/src/SoliditySha3Test.js
Labels: enhancement

#2219 fix: install `@types/node` so you do not need to add types > node in …
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-providers/package-lock.json
  packages/web3-providers/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: types

#2216 Web3 module options to include_package-core added
  docs/include_package-core.rst
  packages/web3-core/src/AbstractWeb3Module.js
Labels: documentation

#2218 fix: `fromWei` and `toWei` typings
  packages/web3-utils/src/index.js
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/from-wei-test.ts
  packages/web3-utils/types/tests/to-wei-test.ts
Labels: types

#2231 fix types for contract methods
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
Labels: types

#2227 Static providers property improved
  docs/include_package-core.rst
  package.json
  packages/web3-core/src/AbstractWeb3Module.js
  packages/web3-core/tests/src/AbstractWeb3ModuleTest.js
  packages/web3-core/types/index.d.ts
  packages/web3-core/types/tests/abstract-web3-module-test.ts
  packages/web3-eth-abi/package-lock.json
  packages/web3-providers/package-lock.json
  packages/web3/src/Web3.js
  packages/web3/tests/src/Web3Test.js
  packages/web3/types/index.d.ts
  packages/web3/types/tests/web3-test.ts
Labels: bug

#2233 Types/fixes
  packages/web3-core/types/index.d.ts
  packages/web3-core/types/tests/abstract-web3-module-test.ts
  packages/web3-eth/types/tests/eth.tests.ts
  packages/web3-shh/types/tests/shh-test.ts
  packages/web3/types/tests/web3-test.ts
Labels: types

#2234 Documentation/examples improvements
  docs/include_package-core.rst
  docs/web3-bzz.rst
  docs/web3-eth-ens.rst
  docs/web3-eth-personal.rst
  docs/web3-eth.rst
  docs/web3-net.rst
  docs/web3-shh.rst
  docs/web3.rst
Labels: documentation

#2245 Parameters for inputCallFormatter fixed
  packages/web3-eth-accounts/src/Accounts.js
  packages/web3-eth-accounts/tests/src/AccountsTest.js
Labels: bug
