Repository web3/web3.js, pull requests merged in 2019-09, with the labels that each got.

#3035 Replace 1.x scrypt shim of web3-eth-accounts with https://github.com/web3-js/scrypt-shim
  bower.json
  dist/web3.min.js
  package.js
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-accounts/src/scrypt.js
Labels: 1.x, bug

#3036 Replace 2.x scrypt shim of web3-eth-accounts with https://github.com/web3-js/scrypt-shim
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/crypto/Scrypt.js
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-eth-accounts/tests/src/models/AccountTest.js
Labels: 2.x, bug

#3059 correct getPendingTransactions for Typescript
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: 2.x, documentation

#3060 Fixed documentation for abi.encodeParameters
  docs/web3-eth-abi.rst
Labels: 2.x, documentation

#3031 Fix for when localStorage is available but access is restricted
  packages/web3-eth-accounts/src/index.js
Labels: 1.x, enhancement

#3062 Bug fix: Fix regeneratorRuntime error in browser
  dist/web3.min.js
  gulpfile.js
  package-lock.json
  package.json
Labels: 1.x, bug

#3080 Fix tests failing on fresh copy of 2.x
  packages/web3-eth-ens/tests/src/contracts/RegistryTest.js
Labels: 2.x
