Repository web3/web3.js, pull requests merged in 2019-02, with the labels that each got.

#2261 Fix/types reference node types
  packages/web3-bzz/types/index.d.ts
  packages/web3-core/types/index.d.ts
  packages/web3-utils/types/index.d.ts
Labels: types

#2262 fix: patch the angular `browser.js` to allow `{crypto: true, stream: …
  packages/web3/angular-patch.js
  packages/web3/package.json
Labels: enhancement

#2271 fixing example of whisper protocol
  docs/web3-shh.rst
Labels: documentation

#2278 write missing typing for `web3-eth-personal`
  packages/web3-eth-personal/types/index.d.ts
  packages/web3-eth-personal/types/tests/personal-tests.ts
Labels: types

#2288 fix: add `status` onto `TransactionReceipt`
  packages/web3-core/types/index.d.ts
Labels: types

#2295 [GH-2293]-Adding clarification of how data needs to be prefix
  docs/web3-eth-personal.rst
Labels: documentation

#2319 Fixes the module instance reference for the account.signTransaction
  packages/web3-eth-accounts/src/Accounts.js
Labels: bug

#2318 NewAccountMethod fixed
  packages/web3-core-method/src/methods/personal/NewAccountMethod.js
  packages/web3-core-method/tests/src/methods/personal/NewAccountMethodTest.js
Labels: bug

#2317 randomHex export fixed in utils module
  packages/web3-utils/src/index.js
Labels: bug

#2292 fix: assign payable property to AbiItemModel
  packages/web3-eth-contract/src/models/AbiItemModel.js
  packages/web3-eth-contract/tests/src/models/AbiItemModelTest.js
Labels: bug

#2280 allow web3-utils to work in projects with `"noImplicitAny": true,`
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3-utils/types/index.d.ts
Labels: types

#2320 CallMethod updated
  packages/web3-core-method/src/methods/CallMethod.js
  packages/web3-core-method/tests/src/methods/CallMethodTest.js
Labels: bug

#2272 Fix decodeLog() for non indexed params
  packages/web3-eth-abi/src/AbiCoder.js
  packages/web3-eth-abi/tests/AbiCoderTest.js
Labels: bug

#2345 asciiToHex fixed for ethers.js ABI coder
  docs/web3-utils.rst
  packages/web3-utils/src/index.js
  packages/web3-utils/tests/src/UtilsTest.js
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/ascii-to-hex-test.ts
Labels: bug

#2346 Subscription parameters fixed
  packages/web3-core-subscriptions/lib/subscriptions/AbstractSubscription.js
  packages/web3-core-subscriptions/tests/lib/subscriptions/AbstractSubscriptionTest.js
  packages/web3-core-subscriptions/tests/src/subscriptions/eth/NewHeadsSubscriptionTest.js
  packages/web3-core-subscriptions/tests/src/subscriptions/eth/NewPendingTransactionsSubscriptionTest.js
  packages/web3-core-subscriptions/tests/src/subscriptions/eth/SyncingSubscriptionTest.js
  packages/web3-utils/src/index.js
Labels: bug

#2347 ProviderResolver updated for the latest EIP1193 spec
  packages/web3-providers/src/resolvers/ProviderResolver.js
  packages/web3-providers/tests/src/resolvers/ProviderResolverTest.js
Labels: enhancement

#2348 property returnValues was missing for past logs
  packages/web3-core-subscriptions/src/subscriptions/eth/LogSubscription.js
  packages/web3-core-subscriptions/tests/src/subscriptions/eth/LogSubscriptionTest.js
Labels: bug

#2353 MetamaskInpageProvider renamed otherwise MetaMask will replace the provider
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-providers/src/providers/MetamaskProvider.js
  packages/web3-providers/src/resolvers/ProviderResolver.js
  packages/web3-providers/tests/src/providers/MetamaskProviderTest.js
  packages/web3-providers/tests/src/resolvers/ProviderResolverTest.js
Labels: bug

#2366 LogSubscription callback handling fixed
  packages/web3-core-subscriptions/src/subscriptions/eth/LogSubscription.js
Labels: bug

#2355 Fix an interface of EthereumProvider.send
  packages/web3-providers/types/index.d.ts
Labels: types

#2387 Validation of the gas usage fixed in TransactionReceiptValidator
  packages/web3-core-method/src/validators/TransactionReceiptValidator.js
  packages/web3-core-method/src/workflows/TransactionConfirmationWorkflow.js
  packages/web3-core-method/tests/src/validators/TransactionReceiptValidatorTest.js
  packages/web3-core-method/tests/src/workflows/TransactionConfirmationWorkflowTest.js
Labels: bug

#2388 EcRecoverMethod fixed and test updated
  packages/web3-core-method/src/methods/personal/EcRecoverMethod.js
  packages/web3-core-method/tests/src/methods/personal/EcRecoverMethodTest.js
Labels: bug

#2389 AbstractCallMethod fixed when the response is falsy.
  packages/web3-core-method/lib/methods/AbstractCallMethod.js
  packages/web3-core-method/tests/lib/methods/AbstractCallMethodTest.js
Labels: bug

#2390 GetBlockTransactionCountMethod fixed
  packages/web3-core-method/src/methods/block/GetBlockTransactionCountMethod.js
  packages/web3-core-method/tests/src/methods/block/GetBlockTransactionCountMethodTest.js
Labels: bug

#2391 EventLogDecoder fixed
  packages/web3-eth-contract/src/decoders/EventLogDecoder.js
  packages/web3-eth-contract/tests/src/decoders/AllEventsLogDecoderTest.js
  packages/web3-eth-contract/tests/src/decoders/EventLogDecoderTest.js
Labels: bug

#2392 AllEventsLogDecoder improved
  packages/web3-eth-contract/src/decoders/AllEventsLogDecoder.js
  packages/web3-eth-contract/tests/src/decoders/AllEventsLogDecoderTest.js
Labels: bug

#2393 SendTransactionMethod fixed
  packages/web3-core-method/lib/factories/AbstractMethodFactory.js
  packages/web3-core-method/src/factories/ModuleFactory.js
  packages/web3-core-method/src/methods/transaction/SendTransactionMethod.js
  packages/web3-core-method/tests/lib/factories/AbstractMethodFactoryTest.js
  packages/web3-core-method/tests/src/factories/ModuleFactoryTest.js
  packages/web3-core-method/tests/src/methods/transaction/SendTransactionMethodTest.js
  packages/web3-eth-contract/jest.config.js
  packages/web3-eth-contract/src/factories/MethodFactory.js
  packages/web3-eth-contract/src/methods/ContractDeployMethod.js
  packages/web3-eth-contract/src/methods/SendContractMethod.js
  packages/web3-eth-contract/tests/src/factories/MethodFactoryTest.js
  packages/web3-eth-contract/tests/src/methods/ContractDeployMethodTest.js
  packages/web3-eth-contract/tests/src/methods/SendContractMethodTest.js
Labels: bug

#2398 Exports added for all subscriptions in core-subscription
  packages/web3-core-subscriptions/src/index.js
Labels: enhancement

#2413 output formatter updated in GetTransactionReceiptMethod
  packages/web3-core-helpers/src/Formatters.js
  packages/web3-core-helpers/tests/src/Formatters/OutputTransactionReceiptFormatterTest.js
  packages/web3-core-method/src/methods/transaction/GetTransactionReceiptMethod.js
  packages/web3-core-method/src/validators/TransactionReceiptValidator.js
  packages/web3-core-method/tests/src/methods/transaction/GetTransactionReceiptMethodTest.js
  packages/web3-core-method/tests/src/validators/TransactionReceiptValidatorTest.js
Labels: bug, in progress

#2415 fix: turn allowSyntheticDefaultImports to false
  packages/web3-bzz/types/tsconfig.json
  packages/web3-core-helpers/types/tsconfig.json
  packages/web3-core-method/types/tsconfig.json
  packages/web3-core/types/tsconfig.json
  packages/web3-eth-abi/types/tsconfig.json
  packages/web3-eth-accounts/types/tsconfig.json
  packages/web3-eth-contract/types/tsconfig.json
  packages/web3-eth-ens/types/tsconfig.json
  packages/web3-eth-iban/types/tsconfig.json
  packages/web3-eth-personal/types/tsconfig.json
  packages/web3-eth/types/tsconfig.json
  packages/web3-net/types/tsconfig.json
  packages/web3-providers/types/tsconfig.json
  packages/web3-shh/types/tsconfig.json
  packages/web3-utils/types/tsconfig.json
  packages/web3/types/tsconfig.json
Labels: types

#2417 fix: Accounts typings
  packages/web3-eth-accounts/types/index.d.ts
  packages/web3-eth-accounts/types/tests/accounts-tests.ts
Labels: types

#2416 fix: `TransactionReceipt` typings
  packages/web3-core/types/index.d.ts
Labels: types

#2414 HttpProvider error handling improved
  packages/web3-core-method/tests/src/validators/TransactionReceiptValidatorTest.js
  packages/web3-core-subscriptions/src/index.js
  packages/web3-providers/src/providers/HttpProvider.js
  packages/web3-providers/tests/src/providers/HttpProviderTest.js
Labels: bug

#2422 fix: `AbiItem` was missing `anonymous`
  packages/web3-utils/types/index.d.ts
Labels: types

#2420 Fix issue with single named return parameter
  packages/web3-eth-contract/src/methods/CallContractMethod.js
  packages/web3-eth-contract/tests/src/methods/CallContractMethodTest.js
Labels: bug

#2408 Fix CSP "script-src" errors in Firefox
  packages/web3-providers/src/detectors/ProviderDetector.js
  packages/web3-providers/src/resolvers/ProviderResolver.js
Labels: enhancement

#2425 Dependency handling fixed in ens module
  packages/web3-eth-ens/src/Ens.js
  packages/web3-eth-ens/src/factories/EnsModuleFactory.js
  packages/web3-eth-ens/tests/src/EnsTest.js
  packages/web3-providers/src/providers/HttpProvider.js
Labels: bug, in progress

#2429 outputTransactionReceiptFormatter improved
  packages/web3-core-helpers/src/Formatters.js
  packages/web3-core-method/src/validators/TransactionReceiptValidator.js
  packages/web3-core-method/tests/src/validators/TransactionReceiptValidatorTest.js
Labels: bug

#2426 CustomProvider
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-providers/src/providers/CustomProvider.js
  packages/web3-providers/src/resolvers/ProviderResolver.js
  packages/web3-providers/tests/src/providers/CustomProviderTest.js
  packages/web3-providers/tests/src/resolvers/ProviderResolverTest.js
Labels: bug

#2432 AbiMapper improved
  packages/web3-core-method/src/watchers/NewHeadsWatcher.js
  packages/web3-eth-contract/src/AbstractContract.js
  packages/web3-eth-contract/src/encoders/MethodEncoder.js
  packages/web3-eth-contract/src/mappers/AbiMapper.js
  packages/web3-eth-contract/src/methods/ContractDeployMethod.js
  packages/web3-eth-contract/src/validators/MethodOptionsValidator.js
  packages/web3-eth-contract/tests/src/AbstractContractTest.js
  packages/web3-eth-contract/tests/src/encoders/MethodEncoderTest.js
  packages/web3-eth-contract/tests/src/mappers/AbiMapperTest.js
  packages/web3-eth-contract/tests/src/validators/MethodOptionsValidatorTest.js
Labels: bug
