Repository web3/web3.js, pull requests merged in 2019-10, with the labels that each got.

#3091 Clarify eth.personal.sign docs
  docs/web3-eth-personal.rst
Labels: 1.x, documentation

#3097 Use eth_chainId when signing transactions
  CHANGELOG.md
  packages/web3-eth-accounts/src/index.js
  test/eth.accounts.signTransaction.js
  test/helpers/test.method.js
Labels: 1.x, bug

#3090 Allow 'null' receipt.status values
  CHANGELOG.md
  packages/web3-core-helpers/src/formatters.js
  test/formatters.outputTransactionReceiptFormatter.js
Labels: 1.x, bug

#3088 Update error strings in utils module
  CHANGELOG.md
  packages/web3-utils/src/index.js
  test/utils.fromWei.js
  test/utils.toWei.js
Labels: 1.x, bug

#3087 Fix utils.isBN
  CHANGELOG.md
  packages/web3-utils/src/utils.js
Labels: 1.x, bug

#3085 Fix randomHex
  CHANGELOG.md
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3-utils/src/index.js
  test/utils.randomHex.js
Labels: 1.x, bug

#3101 docs: add lerna badge
  README.md
Labels: 2.x, documentation

#3108 docs: add lerna badge
  README.md
Labels: 1.x, documentation

#3095 feat(Network): add support for net id of Goerli
  CHANGELOG.md
  packages/web3-eth/src/getNetworkType.js
  test/eth.net.getNetworkType.js
Labels: 1.x, enhancement

#3096 feat(Network): add support for net id of Goerli
  CHANGELOG.md
  docs/web3-eth-net.rst
  packages/web3-net/src/Network.js
  packages/web3-net/tests/src/NetworkTest.js
Labels: 2.x, enhancement

#3089 Allow 0 fromBlock, toBlock values
  CHANGELOG.md
  packages/web3-core-helpers/src/formatters.js
  test/formatters.inputLogFormatter.js
Labels: 1.x, bug

#3109 inputLogFormatter fix from 1.x forwarded (#3089)
  CHANGELOG.md
  package-lock.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/src/Formatters.js
  packages/web3-core-helpers/tests/src/Formatters/InputLogFormatterTest.js
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth/package-lock.json
  packages/web3-providers/package-lock.json
  packages/web3-utils/package-lock.json
Labels: 2.x, bug

#3099 Update web3.py link to active repo
  README.md
Labels: 2.x, documentation

#3110 Documentation web3.py URL updated
  README.md
Labels: 1.x, documentation

#3102 Update web3-eth-contract.rst
  docs/web3-eth-contract.rst
Labels: 2.x, documentation

#3111 getPastEvents documentation clarified
  docs/web3-eth-contract.rst
Labels: 1.x, documentation

#3112 HttpProvider: CORS issue with Firefox and Safari
  CHANGELOG.md
  dist/web3.min.js
  packages/web3-providers-http/src/index.js
Labels: 1.x, bug

#3105 Bubble up tx signing errors
  CHANGELOG.md
  packages/web3-core-method/src/index.js
Labels: 1.x, bug

#3116 supportsSubscriptions method added to providers
  CHANGELOG.md
  packages/web3-providers-http/src/index.js
  packages/web3-providers-ipc/src/index.js
  packages/web3-providers-ws/src/index.js
Labels: 1.x, enhancement

#3115 Fix fromWei / toWei param and return type documentation
  docs/web3-utils.rst
  test/utils.fromWei.js
  test/utils.toWei.js
Labels: 1.x, documentation

#3113 Add eth.getChainId method to 1.x
  CHANGELOG.md
  docs/web3-eth-net.rst
  docs/web3-eth.rst
  packages/web3-eth/src/index.js
  test/eth.getChainId.js
  test/eth_methods.js
Labels: 1.x, Feature Request

#3123 Gas check fix back-ported to 1.x
  CHANGELOG.md
  packages/web3-core-method/src/index.js
Labels: 1.x, bug

#3119 Ensure the immutability of function `signTransaction` input parameter
  CHANGELOG.md
  packages/web3-eth-accounts/src/index.js
Labels: 1.x, enhancement

#3126 Security patches for build tools
  package-lock.json
Labels: 1.x, dependencies

#3125 Signing fixes back-ported from 2.x
  CHANGELOG.md
  docs/web3-eth-accounts.rst
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/index.js
  test/contract.js
  test/eth.accounts.signTransaction.js
Labels: 1.x, bug

#3076 fixed Web3Utils toHex() for Buffer input #3021
  CHANGELOG.md
  packages/web3-utils/src/utils.js
  test/utils.toHex.js
Labels: 1.x, enhancement

#3086 Fix hexToNumber and hexToNumberString prefix validation
  CHANGELOG.md
  packages/web3-utils/src/utils.js
  test/utils.toNumber.js
  test/utils.toNumberString.js
Labels: 1.x, bug

#3122 Add E2E tests for geth and ganache dev clients
  .npmignore
  .travis.yml
  package-lock.json
  package.json
  scripts/ci.sh
  scripts/coveralls.sh
  scripts/e2e.ganache.sh
  scripts/e2e.geth.automine.sh
  scripts/e2e.geth.instamine.sh
  test/3_givenProvider-ganache.js
  test/e2e.contract.deploy.js
  test/e2e.contract.events.js
  test/e2e.method.send.js
  test/e2e.method.signing.js
  test/helpers/test.utils.js
  test/sources/Basic.json
  test/sources/Basic.sol
  test/sources/Reverts.json
  test/sources/Reverts.sol
Labels: 1.x, enhancement

#3128 #3127 fix
  CHANGELOG.md
  packages/web3-eth/types/index.d.ts
Labels: 2.x, types

#3129 receipt is missing on error event
  CHANGELOG.md
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  package-lock.json
  packages/web3-core-method/src/index.js
  packages/web3-utils/src/index.js
Labels: 1.x, bug

#3130 The transaction confirmation workflow can now be configured
  CHANGELOG.md
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  packages/web3-bzz/package-lock.json
  packages/web3-core-method/src/index.js
  packages/web3-eth-contract/src/index.js
  packages/web3-eth/src/index.js
  test/eth.transactionBlockTimeout.js
  test/eth.transactionConfirmationBlocks.js
  test/eth.transactionPollingTimeout.js
Labels: 1.x, enhancement

#3131 Minified file added to web3 package
  .gitignore
  CHANGELOG.md
  gulpfile.js
  packages/web3/package.json
Labels: 1.x, enhancement

#3138 Fix CI not failing even though tests error
  scripts/ci.sh
  scripts/e2e.geth.automine.sh
  scripts/e2e.geth.instamine.sh
  test/e2e.method.signing.js
Labels: 1.x, CI

#3140 Fixes transaction confirmations with the HttpProvider
  CHANGELOG.md
  package-lock.json
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-core-method/src/index.js
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ws/package-lock.json
  scripts/coveralls.sh
  scripts/e2e.ganache.sh
  scripts/e2e.geth.automine.sh
  scripts/e2e.geth.instamine.sh
  test/contract.js
Labels: 1.x, enhancement

#3028 subscription.js Emit 'connected' event with subscription.id
  CHANGELOG.md
  docs/web3-eth-contract.rst
  docs/web3-eth-subscribe.rst
  packages/web3-core-subscriptions/src/subscription.js
Labels: 1.x, enhancement

#3143 Auto fetch tx signing option values when not set by user
  docs/web3-eth-accounts.rst
  docs/web3-eth.rst
  package-lock.json
  package.json
  packages/web3-core-method/src/index.js
  packages/web3-core/types/index.d.ts
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-contract/src/index.js
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
  packages/web3-eth-contract/types/tslint.json
  packages/web3-eth/src/index.js
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
  packages/web3-utils/package-lock.json
  packages/web3/angular-patch.js
  test/contract.js
  test/e2e.method.signing.js
  test/eth.accounts.signTransaction.js
  test/eth.sendTransaction.js
Labels: 1.x, enhancement

#3141 eth.accounts.signTransaction method fixed
  CHANGELOG.md
  docs/web3-eth-accounts.rst
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  package-lock.json
  package.json
  packages/web3-core-method/src/index.js
  packages/web3-core/types/index.d.ts
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-contract/src/index.js
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
  packages/web3-eth-contract/types/tslint.json
  packages/web3-eth/src/index.js
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
  packages/web3-net/src/index.js
  packages/web3-utils/package-lock.json
  packages/web3-utils/src/utils.js
  packages/web3/angular-patch.js
  test/contract.js
  test/e2e.method.signing.js
  test/eth.accounts.signTransaction.js
  test/eth.sendTransaction.js
Labels: 1.x, bug

#3146 Add karma & chrome/firefox headless browser fixtures
  .travis.yml
  karma.conf.js
  package-lock.json
  package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-providers-ws/package-lock.json
  scripts/ci.sh
  scripts/e2e.chrome.sh
  scripts/e2e.firefox.sh
  test/e2e.contract.deploy.js
  test/e2e.contract.events.js
  test/e2e.method.send.js
  test/e2e.method.signing.js
  test/helpers/test.utils.js
Labels: 1.x, CI

#3148 Skip chromium download in CI
  .travis.yml
  karma.conf.js
Labels: 1.x, CI

#3147 Release - 1.2.2
  .jshintignore
  README.md
  gulpfile.js
  lerna.json
  package-lock.json
  package.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package.json
  packages/web3/package.json
Labels: 1.x, release

#3135 Full support for websocket reconnection/resubscription
  packages/web3-core-requestmanager/src/index.js
  packages/web3-core-subscriptions/src/subscription.js
  packages/web3-providers-ws/README.md
  packages/web3-providers-ws/package.json
  packages/web3-providers-ws/src/index.js
Labels: 1.x, enhancement

#3157 Add npm registry proxy in CI to test publication/installation
  .travis.yml
  package-lock.json
  package.json
  scripts/ci.sh
  scripts/e2e.npm.publish.sh
  scripts/e2e.truffle.sh
  verdaccio.yml
Labels: 1.x, CI

#3170 Fix e2e lerna publish (#3)
  package-lock.json
  package.json
  packages/web3-core-helpers/src/formatters.js
  scripts/e2e.npm.publish.sh
  scripts/e2e.truffle.sh
Labels: 1.x, CI
