Repository web3/web3.js, pull requests merged in 2019-11, with the labels that each got.

#3172 Removes GitHub dependencies
  package-lock.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
Labels: 1.x, bug, dependencies

#3177 Internal improvement: Add & adjust web3-core-helper typings
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-providers-http/types/index.d.ts
  packages/web3-providers-http/types/tests/web3-provider-http-tests.ts
  packages/web3-providers-ipc/types/index.d.ts
  packages/web3-providers-ipc/types/tests/web3-provider-ipc-tests.ts
  packages/web3-providers-ws/types/index.d.ts
  packages/web3-providers-ws/types/tests/web3-provider-ws-tests.ts
Labels: 1.x, types

#3185 [types] AbiOutput: add internalType
  packages/web3-utils/types/index.d.ts
Labels: 1.x, types

#3178 [types] AbiOutput: add internalType
  packages/web3-utils/types/index.d.ts
Labels: 2.x, types

#3179 Bundle size improvements for the web3-eth-ens package
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/rollup.config.js
  packages/web3-eth-ens/src/contracts/Registry.js
Labels: 1.x, CI, enhancement

#3202 Fix regenerator runtime error in bundle
  CHANGELOG.md
  gulpfile.js
  karma.conf.js
Labels: 1.x, bug

#3200 web3-eth exporting of types from web3-core
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: 1.x, types

#3180 Fix typescript definition for eth.getStorageAt
  docs/web3-eth.rst
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
  test/eth.getStorageAt.js
Labels: 1.x, types

#3195 Documentation and types improved for web3-eth and web3-eth-contract
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  packages/web3-core-helpers/src/formatters.js
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-core/types/index.d.ts
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth/types/index.d.ts
Labels: 1.x, types

#3199 Module type definitions updated
  packages/web3-bzz/types/index.d.ts
  packages/web3-bzz/types/tests/bzz-test.ts
  packages/web3-core/types/index.d.ts
  packages/web3-core/types/tslint.json
  packages/web3-eth-accounts/types/tests/accounts-tests.ts
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
  packages/web3-eth-ens/types/index.d.ts
  packages/web3-eth-ens/types/tests/ens-test.ts
  packages/web3-eth-personal/types/index.d.ts
  packages/web3-eth-personal/types/tests/personal-tests.ts
  packages/web3-eth-personal/types/tslint.json
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
  packages/web3-net/types/tests/network-test.ts
  packages/web3-shh/types/index.d.ts
  packages/web3-shh/types/tests/shh-test.ts
  packages/web3/types/index.d.ts
  packages/web3/types/tests/web3-test.ts
Labels: 1.x, types

#3205 Defines corejs v2 in the gulpfile
  gulpfile.js
  package-lock.json
  package.json
Labels: 1.x, enhancement

#3206 Release - 1.2.3
  .versions
  CHANGELOG.md
  bower.json
  dist/web3.min.js
  lerna.json
  package.js
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 1.x, release

#3214 Release - 1.2.4
  CHANGELOG.md
  bower.json
  dist/web3.min.js
  lerna.json
  package-lock.json
  package.js
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 1.x, release

#3213 Not required @types/bignumber.js removed from package.json in web3-core
  packages/web3-core/package.json
Labels: 1.x, dependencies

#3219 eth_requestAccounts added to web3-eth package
  CHANGELOG.md
  docs/web3-eth.rst
  packages/web3-eth/src/index.js
  packages/web3-eth/types/index.d.ts
  test/eth.requestAccounts.js
Labels: 1.x, Feature Request

#3220 eth_getProof added to web3-eth package
  docs/web3-eth.rst
  packages/web3-core-helpers/src/formatters.js
  packages/web3-eth/src/index.js
  packages/web3-eth/types/index.d.ts
  test/eth.getProof.js
Labels: 1.x, Feature Request

#3229 CHANGELOG.md updated
  CHANGELOG.md
Labels: 1.x, documentation

#3235 PULL_REQUEST_TEMPLATE.md extended
  PULL_REQUEST_TEMPLATE.md
Labels: 1.x, documentation

#3241 fix typo: modify
  packages/web3-eth-contract/src/index.js
Labels: 1.x, documentation

#3239 Extends the web3-eth module with the method getPendingTransactions
  CHANGELOG.md
  docs/web3-eth.rst
  packages/web3-eth/src/index.js
  test/eth.getPendingTransactions.js
Labels: 1.x, Feature Request

#3238 big-number (BN & BigNumber) mapping added to abi.encodeParameters
  CHANGELOG.md
  package-lock.json
  packages/web3-eth-abi/src/index.js
  test/abi.encodeParameter.js
Labels: 1.x, enhancement

#3242 eth-lib dependency updated
  CHANGELOG.md
  package-lock.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
Labels: 1.x, dependencies

#3246 clearSubscriptions shouldn't throw an error if no subscriptions do exist
  CHANGELOG.md
  packages/web3-core-requestmanager/src/index.js
Labels: 1.x, Please Review, bug

#3247 fixes defaultBlock property handling
  CHANGELOG.md
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  packages/web3-core-helpers/src/formatters.js
  packages/web3-core/types/index.d.ts
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
  test/eth.getBalance.js
  test/formatters.inputDefaultBlockFormatter.js
  test/helpers/test.method.js
Labels: 1.x, Please Review, bug
