Repository web3/web3.js, pull requests merged in 2019-04, with the labels that each got.

#2613 EventSubscriptionFactory fixed
  packages/web3-eth-contract/src/factories/EventSubscriptionFactory.js
Labels: bug

#2618 Write better types for ens and update the docs
  docs/web3-eth-ens.rst
  packages/web3-eth-ens/types/index.d.ts
  packages/web3-eth-ens/types/tests/ens-test.ts
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: types

#2619 Add index to Wallet type
  packages/web3-eth-accounts/types/index.d.ts
  packages/web3-eth-accounts/types/tests/accounts-tests.ts
Labels: types

#2616 EthSendTransactionMethod simplified and fixed for local signing
  packages/web3-core-method/lib/factories/AbstractMethodFactory.js
  packages/web3-core-method/src/methods/transaction/EthSendTransactionMethod.js
  packages/web3-core-method/tests/lib/factories/AbstractMethodFactoryTest.js
  packages/web3-core-method/tests/src/methods/transaction/EthSendTransactionMethodTest.js
  packages/web3-eth-accounts/src/Accounts.js
  packages/web3-eth-contract/src/factories/MethodFactory.js
  packages/web3-eth-contract/src/methods/ContractDeployMethod.js
  packages/web3-eth-contract/src/methods/SendContractMethod.js
  packages/web3-eth-contract/tests/src/factories/MethodFactoryTest.js
  packages/web3-eth-contract/tests/src/methods/ContractDeployMethodTest.js
  packages/web3-eth-contract/tests/src/methods/SendContractMethodTest.js
  packages/web3-eth/src/Eth.js
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
Labels: bug

#2617 Executing of a state changing method with "method.call()"
  packages/web3-core-method/src/proxy/MethodProxy.js
  packages/web3-eth-contract/src/models/AbiItemModel.js
  packages/web3-eth-contract/src/proxies/MethodsProxy.js
  packages/web3-eth-contract/tests/src/models/AbiItemModelTest.js
  packages/web3-eth-contract/tests/src/proxies/MethodsProxyTest.js
Labels: bug

#2624 Decoding of tuples fixed
  packages/web3-core-method/src/methods/transaction/EthSendTransactionMethod.js
  packages/web3-core-method/tests/src/methods/transaction/EthSendTransactionMethodTest.js
  packages/web3-eth-contract/src/methods/CallContractMethod.js
  packages/web3-eth-contract/tests/src/methods/CallContractMethodTest.js
Labels: bug

#2625 WebsocketProvider improvements
  packages/web3-providers/lib/providers/AbstractSocketProvider.js
  packages/web3-providers/src/factories/ProvidersModuleFactory.js
  packages/web3-providers/src/providers/WebsocketProvider.js
  packages/web3-providers/tests/src/providers/WebsocketProviderTest.js
Labels: bug

#2629 GetProtocolVersionMethod afterExecution added
  packages/web3-core-method/src/methods/network/GetProtocolVersionMethod.js
  packages/web3-core-method/tests/src/methods/network/GetProtocolVersionMethodTest.js
Labels: bug

#2630 Websocket fork removed as dependency
  packages/web3-providers/package-lock.json
  packages/web3-providers/package.json
Labels: enhancement

#2632 supportsSubscriptions added to providers
  packages/web3-core-method/lib/factories/AbstractMethodFactory.js
  packages/web3-core-method/src/observers/TransactionObserver.js
  packages/web3-core-method/tests/lib/factories/AbstractMethodFactoryTest.js
  packages/web3-core-method/tests/src/observers/TransactionObserverTest.js
  packages/web3-core/types/index.d.ts
  packages/web3-core/types/tests/abstract-web3-module-test.ts
  packages/web3-eth-contract/src/factories/MethodFactory.js
  packages/web3-eth-contract/tests/src/factories/MethodFactoryTest.js
  packages/web3-eth/types/tests/eth.tests.ts
  packages/web3-providers/lib/providers/AbstractSocketProvider.js
  packages/web3-providers/src/providers/CustomProvider.js
  packages/web3-providers/src/providers/HttpProvider.js
  packages/web3-providers/tests/lib/providers/AbstractSocketProviderTest.js
  packages/web3-providers/tests/src/providers/CustomProviderTest.js
  packages/web3-providers/tests/src/providers/HttpProviderTest.js
  packages/web3-providers/types/index.d.ts
  packages/web3-providers/types/tests/provider-detector-test.ts
  packages/web3-providers/types/tests/provider-module-factory-test.ts
  packages/web3-shh/types/tests/shh-test.ts
  packages/web3/types/index.d.ts
  packages/web3/types/tests/web3-test.ts
Labels: enhancement

#2643 Web3ModuleOptions interface updated
  packages/web3-core/types/index.d.ts
Labels: types

#2645 fix: make auto-resolve to the root module when importing typings
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package.json
  packages/web3/package.json
Labels: types

#2648 load and save method fixed in Wallet class
  packages/web3-eth-accounts/src/models/Wallet.js
  packages/web3-eth-accounts/tests/src/models/WalletTest.js
Labels: bug

#2644 Documentation updated
  docs/callbacks-promises-events.rst
  docs/conf.py
  docs/getting-started.rst
  docs/glossary.rst
  docs/include_package-core.rst
  docs/include_package-net.rst
  docs/index.rst
  docs/web3-bzz.rst
  docs/web3-eth-abi.rst
  docs/web3-eth-accounts.rst
  docs/web3-eth-contract.rst
  docs/web3-eth-ens.rst
  docs/web3-eth-iban.rst
  docs/web3-eth-net.rst
  docs/web3-eth-personal.rst
  docs/web3-eth.rst
  docs/web3-net.rst
  docs/web3-shh.rst
  docs/web3.rst
  packages/web3-eth-contract/src/models/AbiModel.js
  packages/web3-eth-contract/tests/src/models/AbiModelTest.js
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
Labels: documentation

#2649 Release - 1.0.0-beta.52
  lerna.json
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/lib/methods/AbstractMethod.js
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-method/src/observers/TransactionObserver.js
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers/package.json
  packages/web3-providers/tests/lib/providers/AbstractSocketProviderTest.js
  packages/web3-providers/tests/src/providers/IpcProviderTest.js
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3-utils/src/Utils.js
  packages/web3-utils/src/index.js
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: release

#2655 getPendingTransactions implemented in web3-core-methods
  packages/web3-core-method/src/index.js
  packages/web3-core-method/src/methods/transaction/GetPendingTransactionsMethod.js
  packages/web3-core-method/tests/src/methods/transaction/GetPendingTransactionsMethodTest.js
  packages/web3-eth/src/factories/MethodFactory.js
  packages/web3-eth/tests/src/factories/MethodFactoryTest.js
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: Feature Request

#2672 Fix callback types
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: types

#2658 documentation added for web3-eth-admin module & pendingTransactions
  docs/web3-eth-admin.rst
  docs/web3-eth.rst
Labels: documentation

#2657 Geth Admin management API's implemented (web3-eth-admin)
  packages/web3-core-method/src/index.js
  packages/web3-core-method/src/methods/admin/AddPeerMethod.js
  packages/web3-core-method/src/methods/admin/DataDirectoryMethod.js
  packages/web3-core-method/src/methods/admin/NodeInfoMethod.js
  packages/web3-core-method/src/methods/admin/PeersMethod.js
  packages/web3-core-method/src/methods/admin/SetSolcMethod.js
  packages/web3-core-method/src/methods/admin/StartRpcMethod.js
  packages/web3-core-method/src/methods/admin/StartWsMethod.js
  packages/web3-core-method/src/methods/admin/StopRpcMethod.js
  packages/web3-core-method/src/methods/admin/StopWsMethod.js
  packages/web3-core-method/tests/src/methods/admin/AddPeerMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/DataDirectoryMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/NodeInfoMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/PeersMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/SetSolcMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/StartRpcMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/StartWsMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/StopRpcMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/StopWsMethodTest.js
  packages/web3-core/types/index.d.ts
  packages/web3-eth-admin/README.md
  packages/web3-eth-admin/jest.config.js
  packages/web3-eth-admin/package-lock.json
  packages/web3-eth-admin/package.json
  packages/web3-eth-admin/rollup.config.js
  packages/web3-eth-admin/src/Admin.js
  packages/web3-eth-admin/src/factories/MethodFactory.js
  packages/web3-eth-admin/src/index.js
  packages/web3-eth-admin/test/src/AdminTest.js
  packages/web3-eth-admin/test/src/factories/MethodFactoryTest.js
  packages/web3-eth-admin/types/index.d.ts
  packages/web3-eth-admin/types/tests/admin-tests.ts
  packages/web3-eth-admin/types/tsconfig.json
  packages/web3-eth-admin/types/tslint.json
Labels: Feature Request

#2659 txpool management API's implemented (web3-eth-txpool)
  docs/web3-eth-txpool.rst
  packages/web3-core-method/src/index.js
  packages/web3-core-method/src/methods/txpool/ContentMethod.js
  packages/web3-core-method/src/methods/txpool/InspectMethod.js
  packages/web3-core-method/src/methods/txpool/StatusMethod.js
  packages/web3-core-method/tests/src/methods/txpool/ContentMethodTest.js
  packages/web3-core-method/tests/src/methods/txpool/InspectMethodTest.js
  packages/web3-core-method/tests/src/methods/txpool/StatusMethodTest.js
  packages/web3-core/types/index.d.ts
  packages/web3-eth-txpool/README.md
  packages/web3-eth-txpool/jest.config.js
  packages/web3-eth-txpool/package-lock.json
  packages/web3-eth-txpool/package.json
  packages/web3-eth-txpool/rollup.config.js
  packages/web3-eth-txpool/src/Txpool.js
  packages/web3-eth-txpool/src/factories/MethodFactory.js
  packages/web3-eth-txpool/src/index.js
  packages/web3-eth-txpool/tests/src/TxpoolTest.js
  packages/web3-eth-txpool/tests/src/factories/MethodFactoryTest.js
  packages/web3-eth-txpool/types/index.d.ts
  packages/web3-eth-txpool/types/tests/txpool-tests.ts
  packages/web3-eth-txpool/types/tsconfig.json
  packages/web3-eth-txpool/types/tslint.json
  packages/web3-eth/types/index.d.ts
Labels: Feature Request

#2663 web3-eth-miner documentation
  docs/web3-eth-abi.rst
  docs/web3-eth-admin.rst
  docs/web3-eth-ens.rst
  docs/web3-eth-iban.rst
  docs/web3-eth-miner.rst
  docs/web3-eth-net.rst
  docs/web3-eth-personal.rst
  docs/web3-eth-subscribe.rst
  docs/web3-eth-txpool.rst
  docs/web3-net.rst
  docs/web3-utils.rst
  docs/web3.rst
Labels: documentation

#2701 BN export added to utils
  packages/web3-utils/src/index.js
Labels: bug

#2702 DI improved in index.js of the contract module
  packages/web3-eth-contract/src/index.js
Labels: bug

#2700 Calling new Web3() without a provider.
  packages/web3-providers/src/resolvers/ProviderResolver.js
  packages/web3-providers/tests/src/resolvers/ProviderResolverTest.js
  packages/web3-providers/types/index.d.ts
  packages/web3-providers/types/tests/provider-detector-test.ts
Labels: bug

#2694 Add 'txHash' field to the result of 'accounts.signTransaction'
  docs/web3-eth-accounts.rst
  packages/web3-core/types/index.d.ts
  packages/web3-eth/package-lock.json
  packages/web3-eth/src/signers/TransactionSigner.js
  packages/web3-eth/tests/src/signers/TransactionSignerTest.js
Labels: enhancement, in progress

#2699 Minor changes in some packages
  docs/web3-eth-admin.rst
  docs/web3-eth-miner.rst
  docs/web3-eth-txpool.rst
  packages/web3-core/types/index.d.ts
  packages/web3-eth-admin/README.md
  packages/web3-eth-admin/package-lock.json
  packages/web3-eth-admin/package.json
  packages/web3-eth-admin/types/index.d.ts
  packages/web3-eth-miner/README.md
  packages/web3-eth-miner/package-lock.json
  packages/web3-eth-miner/package.json
  packages/web3-eth-miner/types/index.d.ts
  packages/web3-eth-personal/package.json
  packages/web3-eth-txpool/README.md
  packages/web3-eth-txpool/package-lock.json
  packages/web3-eth-txpool/package.json
  packages/web3-eth-txpool/types/index.d.ts
Labels: enhancement

#2703 TransactionObserver fixed for HTTP
  packages/web3-core-method/lib/methods/transaction/AbstractObservedTransactionMethod.js
  packages/web3-core-method/src/index.js
  packages/web3-core-method/src/methods/transaction/SendRawTransactionMethod.js
  packages/web3-core-method/src/methods/transaction/SendTransactionMethod.js
  packages/web3-core-method/src/observers/TransactionObserver.js
  packages/web3-core-method/tests/lib/methods/transaction/AbstractObservedTransactionMethodTest.js
  packages/web3-core-method/tests/src/methods/transaction/SendRawTransactionMethodTest.js
  packages/web3-core-method/tests/src/methods/transaction/SendTransactionMethodTest.js
  packages/web3-core-method/tests/src/observers/TransactionObserverTest.js
  packages/web3-eth-contract/src/methods/ContractDeployMethod.js
  packages/web3-eth-contract/src/methods/SendContractMethod.js
  packages/web3-eth-contract/tests/src/methods/SendContractMethodTest.js
Labels: bug, in progress

#2705 Error strings in utils module updated
  packages/web3-utils/src/index.js
  packages/web3-utils/tests/src/UtilsTest.js
Labels: bug, in progress

#2719 fixed parameters
  docs/web3-eth-abi.rst
  docs/web3-eth-accounts.rst
  docs/web3-eth-admin.rst
  docs/web3-eth-contract.rst
Labels: documentation

#2710 Renaming sha3 to keccak256
  docs/web3-utils.rst
  packages/web3-core-helpers/src/Formatters.js
  packages/web3-eth-abi/src/AbiCoder.js
  packages/web3-eth-abi/tests/AbiCoderTest.js
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-eth-accounts/tests/src/models/AccountTest.js
  packages/web3-eth/src/signers/TransactionSigner.js
  packages/web3-utils/README.md
  packages/web3-utils/src/BloomFilter.js
  packages/web3-utils/src/SoliditySha3.js
  packages/web3-utils/src/Utils.js
  packages/web3-utils/src/index.js
  packages/web3-utils/tests/src/UtilsTest.js
Labels: enhancement, in progress

#2713 eth_getProof method implementation
  docs/web3-eth.rst
  packages/web3-core-method/src/index.js
  packages/web3-core-method/src/methods/node/GetProofMethod.js
  packages/web3-core-method/tests/src/methods/node/GetProofMethodTest.js
  packages/web3-eth/src/factories/MethodFactory.js
  packages/web3-eth/tests/src/factories/MethodFactoryTest.js
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: Feature Request, in progress

#2735 signTransaction in Accounts module fixed
  packages/web3-eth-accounts/src/Accounts.js
  packages/web3-eth-accounts/tests/src/AccountsTest.js
Labels: bug

#2727 Adapts checksum functionality to RSKIP60 and EIP55
  docs/_build/html/_sources/web3-utils.rst.txt
  packages/web3-utils/src/Utils.js
  packages/web3-utils/src/index.js
  packages/web3-utils/tests/src/UtilsTest.js
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/check-address-checksum-test.ts
  packages/web3-utils/types/tests/is-address-test.ts
  packages/web3-utils/types/tests/strip-hex-prefix-test.ts
  packages/web3-utils/types/tests/to-check-sum-address-test.ts
Labels: enhancement

#2737 AbstractSubscription error handling improved
  packages/web3-core-subscriptions/lib/subscriptions/AbstractSubscription.js
  packages/web3-core-subscriptions/tests/__mocks__/SocketProvider.js
  packages/web3-core-subscriptions/tests/__mocks__/SocketProviderAdapter.js
  packages/web3-core-subscriptions/tests/lib/subscriptions/AbstractSubscriptionTest.js
  packages/web3-core-subscriptions/tests/src/subscriptions/eth/LogSubscriptionTest.js
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-eth-contract/tests/src/methods/SendContractMethodTest.js
Labels: bug

#2740 Error handling for callbacks fixed.
  packages/web3-core-method/lib/methods/AbstractMethod.js
  packages/web3-core-method/tests/lib/methods/AbstractMethodTest.js
  packages/web3-eth/src/methods/EthSignMethod.js
  packages/web3-eth/tests/src/methods/EthSignMethodTest.js
  packages/web3-utils/src/Utils.js
  packages/web3-utils/src/index.js
Labels: bug

#2746 build and test tools updated
  package-lock.json
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core/package-lock.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-admin/package-lock.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-miner/package-lock.json
  packages/web3-eth-txpool/package-lock.json
  packages/web3-eth/package-lock.json
  packages/web3-net/package-lock.json
  packages/web3-providers/package-lock.json
  packages/web3-shh/package-lock.json
  packages/web3-utils/package-lock.json
Labels: bug

#2751 Release - 1.0.0-beta.53
  docs/web3-eth-admin.rst
  docs/web3-eth-debug.rst
  docs/web3-eth-miner.rst
  docs/web3-eth.rst
  docs/web3-utils.rst
  lerna.json
  package.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core-method/src/methods/EstimateGasMethod.js
  packages/web3-core-method/src/methods/admin/NodeInfoMethod.js
  packages/web3-core-method/src/methods/admin/StartRpcMethod.js
  packages/web3-core-method/src/methods/admin/StartWsMethod.js
  packages/web3-core-method/src/methods/miner/SetGasPriceMethod.js
  packages/web3-core-method/src/methods/miner/StartMinerMethod.js
  packages/web3-core-method/src/methods/node/GetProofMethod.js
  packages/web3-core-method/src/methods/transaction/GetPendingTransactionsMethod.js
  packages/web3-core-method/src/methods/txpool/StatusMethod.js
  packages/web3-core-method/tests/src/methods/admin/NodeInfoMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/StartRpcMethodTest.js
  packages/web3-core-method/tests/src/methods/admin/StartWsMethodTest.js
  packages/web3-core-method/tests/src/methods/debug/BlockProfileMethodTest.js
  packages/web3-core-method/tests/src/methods/debug/DumpBlockMethodTest.js
  packages/web3-core-method/tests/src/methods/debug/GetBlockRlpMethodTest.js
  packages/web3-core-method/tests/src/methods/debug/GoTraceMethodTest.js
  packages/web3-core-method/tests/src/methods/debug/TraceBlockByNumberMethodTest.js
  packages/web3-core-method/tests/src/methods/miner/SetGasPriceMethodTest.js
  packages/web3-core-method/tests/src/methods/miner/StartMinerMethodTest.js
  packages/web3-core-method/tests/src/methods/node/GetProofMethodTest.js
  packages/web3-core-method/tests/src/methods/transaction/GetPendingTransactionsMethodTest.js
  packages/web3-core-method/tests/src/methods/transaction/SendTransactionMethodTest.js
  packages/web3-core-method/tests/src/methods/txpool/StatusMethodTest.js
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-admin/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-debug/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-miner/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth-txpool/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: in progress, release

#2753 Transaction.to can be null
  packages/web3-core/types/index.d.ts
Labels: types

#2758 Ipc and WebSocket provider error handling fixed.
  packages/web3-providers/src/providers/IpcProvider.js
  packages/web3-providers/src/providers/WebsocketProvider.js
  packages/web3-providers/tests/src/providers/IpcProviderTest.js
  packages/web3-providers/tests/src/providers/WebsocketProviderTest.js
Labels: bug
