Repository web3/web3.js, pull requests merged in 2019-12, with the labels that each got.

#3212 Fix E2E Publishing tests
  .travis.yml
  package-lock.json
  package.json
  scripts/e2e.npm.publish.sh
  scripts/e2e.truffle.sh
Labels: 1.x, CI

#3253 Fix wrong address in docs
  docs/web3-utils.rst
Labels: 1.x, documentation

#3248 Adds revert instruction handling
  CHANGELOG.md
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  packages/web3-core-helpers/src/errors.js
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-core-helpers/types/tests/errors-test.ts
  packages/web3-core-method/src/index.js
  packages/web3-core-method/types/index.d.ts
  packages/web3-eth-contract/src/index.js
  packages/web3-eth/src/index.js
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
  packages/web3-utils/src/index.js
  test/contract.js
  test/e2e.method.call.js
  test/e2e.method.send.js
  test/eth.handleRevert.js
  test/sources/Basic.json
  test/sources/Basic.sol
Labels: 1.x, Feature Request

#3264 Replace istanbul with nyc
  .gitignore
  package-lock.json
  package.json
  scripts/coveralls.sh
  scripts/e2e.ganache.sh
  scripts/e2e.geth.automine.sh
  scripts/e2e.geth.instamine.sh
Labels: 1.x, CI

#3259 Receipt added to transaction errors
  CHANGELOG.md
  packages/web3-core-helpers/src/errors.js
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-core-method/src/index.js
  test/eth.sendTransaction.revert.js
Labels: 1.x, enhancement

#3260 Add bundlesize to CI
  package-lock.json
  package.json
  scripts/ci.sh
Labels: 1.x, CI, enhancement

#3261 Fix minified bundle
  CHANGELOG.md
  dist/web3.min.js
  gulpfile.js
  karma.conf.js
  package-lock.json
  package.json
  scripts/ci.sh
  scripts/e2e.cdn.sh
  scripts/e2e.min.sh
  scripts/html/index.html
  test/e2e.minified.js
Labels: 1.x, CI, enhancement

#3274 Add E2E Mosaic test
  .travis.yml
  package.json
  scripts/ci.sh
  scripts/e2e.mosaic.sh
  scripts/e2e.npm.publish.sh
  scripts/e2e.truffle.sh
  scripts/js/resolutions.js
  test/contract.js
Labels: 1.x, CI

#3280 Callback type for Accounts.signTransaction fixed
  CHANGELOG.md
  packages/web3-core/types/index.d.ts
  packages/web3-eth-accounts/types/index.d.ts
  packages/web3-eth-accounts/types/tests/accounts-tests.ts
Labels: 1.x, types

#3279 AbiInput type updated in web3-utils
  CHANGELOG.md
  packages/web3-utils/types/index.d.ts
Labels: 1.x, types
