Repository web3/web3.js, pull requests merged in 2019-07, with the labels that each got.

#2918 Added missing words
  docs/web3-eth-contract.rst
Labels: 2.x, documentation

#2930 Travis YML file updated
  .travis.yml
Labels: 1.x, enhancement

#2937 Node >= v8.0.0 support for web3 2.0.0-alpha
  package.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/crypto/Scrypt.js
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-eth-accounts/tests/src/models/AccountTest.js
  packages/web3-eth-admin/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-debug/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-miner/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth-txpool/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package.json
  packages/web3/package.json
Labels: 2.x, enhancement

#2906 Release - 2.0.0-alpha
  CHANGELOG.md
  docs/include_announcement.rst
  lerna.json
  package-lock.json
  package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/crypto/Scrypt.js
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-eth-accounts/tests/src/models/AccountTest.js
  packages/web3-eth-admin/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-debug/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-miner/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth-txpool/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 2.x, release

#2919 Fix Subscription Type
  packages/web3-eth/types/index.d.ts
Labels: 2.x, types

#2920 Fix docs typo for WebsocketProvider
  packages/web3-providers/src/providers/WebsocketProvider.js
Labels: 2.x, documentation

#2926 Solved (miner.startMining is not a function)
  CHANGELOG.md
  packages/web3-core-method/src/index.js
  packages/web3-core-method/src/methods/miner/StartMiningMethod.js
  packages/web3-core-method/src/methods/miner/StopMiningMethod.js
  packages/web3-core-method/tests/src/methods/miner/StartMinerMethodTest.js
  packages/web3-core-method/tests/src/methods/miner/StopMinerMethodTest.js
Labels: 2.x, bug

#2934 Fix constructor name checking when reconnect websocket with options
  packages/web3-providers/src/providers/WebsocketProvider.js
Labels: 2.x, bug

#2929 Length check and formatting private key in accounts.privateKeyToAccount method
  CHANGELOG.md
  packages/web3-eth-accounts/src/models/Account.js
  packages/web3-eth-accounts/tests/src/models/AccountTest.js
Labels: 2.x, enhancement

#2939 Fix TypeScript 'ContractOptions' interface
  CHANGELOG.md
  packages/web3-eth-contract/types/index.d.ts
Labels: 2.x, types

#2951 pickup latest fsevents (v1.2.9) for Node 12 compat
  package-lock.json
Labels: 2.x, bug

#2950 convert salt to Buffer instance before encrypting
  packages/web3-eth-accounts/src/models/Account.js
Labels: 2.x, bug

#2952 implement fallback from built-in scrypt to scryptsy/scrypt packages
  CHANGELOG.md
  packages/web3-eth-accounts/src/crypto/Scrypt.js
Labels: 2.x, bug

#2962 Add Discord link to "Community" section of readme
  README.md
Labels: documentation

#2969 fix doc link
  README.md
Labels: documentation

#2938 Node >= v8.0.0 support for web3 1.0
  .travis.yml
  bower.json
  dist/web3.min.js
  package-lock.json
  package.js
  package.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-accounts/src/scrypt.js
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package.json
  packages/web3/package.json
  test/eth.accounts.create.js
  test/eth.accounts.encrypt-decrypt.js
Labels: 1.x, enhancement

#2982 fix docs dead links
  packages/web3/README.md
Labels: documentation

#2979 requestOptions support added
  packages/web3-providers-ws/src/index.js
Labels: 1.x, enhancement

#2976 switch repo fork for the websocket package
  dist/web3.min.js
  gulpfile.js
  packages/web3-eth-accounts/src/scrypt.js
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-providers-ws/src/index.js
Labels: 1.x, bug

#2985 Fix Web3 image in README
  README.md
Labels: documentation
