Repository web3/web3.js, pull requests merged in 2020-01, with the labels that each got.

#3285 Make user supplied callback fire in accounts.signTransaction
  CHANGELOG.md
  packages/web3-eth-accounts/src/index.js
  test/e2e.method.signing.js
Labels: 1.x, bug

#3224 Add PR and release guidelines
  CONTRIBUTIONS.md
Labels: 1.x, documentation

#3276 Add tests for core-subscriptions edge cases
  packages/web3-core-subscriptions/src/index.js
  packages/web3-core-subscriptions/src/subscription.js
  test/eth.subscribe.ganache.js
Labels: 1.x

#3296 Referencing of the contribution guidelines
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: 1.x, documentation

#2980 Added support for custom http agent
  CHANGELOG.md
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-providers-http/README.md
  packages/web3-providers-http/src/index.js
  packages/web3-providers-http/types/tests/web3-provider-http-tests.ts
  test/helpers/FakeXHR2.js
  test/httpprovider.js
Labels: 1.x, enhancement

#3298 Prefer receipt status to code availability on contract deployment
  CHANGELOG.md
  packages/web3-core-method/src/index.js
  test/e2e.contract.deploy.js
Labels: 1.x, bug

#3297 Verify that event arg indexing matches received topics
  CHANGELOG.md
  packages/web3-eth-contract/src/index.js
  test/e2e.contract.events.js
  test/sources/Child.json
  test/sources/Parent.json
  test/sources/ParentAndChild.sol
Labels: 1.x, bug

#3304 Add ganache-core E2E test
  .travis.yml
  package.json
  scripts/ci.sh
  scripts/e2e.ganache.core.sh
  scripts/e2e.truffle.sh
Labels: 1.x, CI, QA

#3311 Add core-method tests for http confirmations & wallet chain options
  scripts/e2e.geth.automine.sh
  scripts/e2e.npm.publish.sh
  test/e2e.contract.deploy.js
  test/e2e.method.signing.js
Labels: 1.x, Please Review, Testing

#3314 WebsocketProvider - Error Handling
  packages/web3-core-helpers/src/errors.js
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-core-helpers/types/tests/errors-test.ts
  packages/web3-providers-ws/src/index.js
  test/websocket.ganache.js
Labels: 1.x

#3273 add CDN for web3.js
  README.md
Labels: 1.x, documentation

#3301 Adds the possibility to define a custom registry for the ENS module
  .gitignore
  .travis.yml
  CHANGELOG.md
  docs/web3-eth-ens.rst
  package-lock.json
  package.json
  packages/web3-eth-ens/src/ENS.js
  packages/web3-eth-ens/types/index.d.ts
  packages/web3-eth-ens/types/tests/ens-test.ts
  packages/web3-eth/src/index.js
  scripts/ci.sh
  scripts/e2e.ens.sh
  scripts/js/ens/1_initial_migration.js
  scripts/js/ens/truffle-config.js
  test/config/ensAddresses.json
  test/e2e.ens.js
  test/eth.ens.js
Labels: 1.x, Feature Request

#3316 Ensure '0x' prefix exists (web3-eth-accounts)
  CHANGELOG.md
  packages/web3-eth-accounts/src/index.js
  test/eth.accounts.sign.js
Labels: 1.x, enhancement

#3326 Add types for subscription.on(connected)
  CHANGELOG.md
  packages/web3-core-subscriptions/types/index.d.ts
  packages/web3-core-subscriptions/types/tests/subscriptions.tests.ts
  scripts/e2e.mosaic.sh
Labels: 1.x, types

#3323 back-ports privateKey validation of the 2.x Accounts module to 1.x
  docs/web3-eth-accounts.rst
  packages/web3-core/types/index.d.ts
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-accounts/types/tests/accounts-tests.ts
  test/eth.accounts.encrypt-decrypt.js
  test/eth.accounts.sign.js
Labels: 1.x, enhancement

#3303 Minimize changes to test/contract.js (#3190)
  docs/include_package-core.rst
  packages/web3-core-requestmanager/src/index.js
  test/contract.js
Labels: Please Review

#3330 Revert non-essential changes (#3190)
  bower.json
  dist/web3.min.js
  package.js
  packages/web3-bzz/package-lock.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/types/index.d.ts
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-requestmanager/types/index.d.ts
  packages/web3-core-requestmanager/types/tsconfig.json
  packages/web3-core-requestmanager/types/tslint.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core/package-lock.json
  packages/web3-core/types/index.d.ts
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/src/contracts/Registry.js
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth/package-lock.json
  packages/web3-net/package-lock.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/types/index.d.ts
  packages/web3-providers-http/types/tests/web3-provider-http-tests.ts
  packages/web3-providers-http/types/tsconfig.json
  packages/web3-providers-http/types/tslint.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/types/index.d.ts
  packages/web3-providers-ipc/types/tests/web3-provider-ipc-tests.ts
  packages/web3-providers-ipc/types/tsconfig.json
  packages/web3-providers-ws/types/index.d.ts
  packages/web3-providers-ws/types/tests/web3-provider-ws-tests.ts
  packages/web3-providers-ws/types/tsconfig.json
  packages/web3-providers-ws/types/tslint.json
  packages/web3-shh/package-lock.json
  packages/web3-utils/package-lock.json
  packages/web3/package-lock.json
Labels: 1.x

#3315 Release - 1.2.5
  CHANGELOG.md
  README.md
  bower.json
  dist/web3.min.js
  lerna.json
  package-lock.json
  package.js
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 1.x, release

#3342 regenerator-runtime readded to package.json
  package-lock.json
  package.json
Labels: 1.x, dependencies

#3344 Implement FakeIpcProvider.reset (#3190)
  test/contract.js
  test/helpers/FakeIpcProvider.js
Labels: Please Review

#3338 Adds the görli testnet ENS registry to the known registries
  CHANGELOG.md
  packages/web3-eth-ens/src/config.js
Labels: 1.x, Please Review, enhancement

#3349 Add missing `.net` to examples of 1.2.5
  docs/include_package-net.rst
Labels: 1.x, documentation

#3347 Add subscription tests for disconnect & setProvider (#3190)
  test/eth.subscribe.ganache.js
  test/helpers/test.utils.js
Labels: 1.x, Please Review

#3329 Check for error codes on close in RequestManager (#3190)
  packages/web3-core-helpers/src/errors.js
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-core-helpers/types/tests/errors-test.ts
  packages/web3-core-requestmanager/src/index.js
  test/e2e.contract.events.js
  test/eth.subscribe.ganache.js
  test/helpers/test.utils.js
  test/websocket.ganache.js
Labels: 1.x, Please Review
