Repository web3/web3.js, pull requests merged in 2020-03, with the labels that each got.

#3402 Document WS clientConfig options in README and RTD
  docs/include_package-core.rst
  packages/web3-providers-ws/README.md
Labels: 1.x, Please Review, documentation

#3422 Clarify that 0x prefix is needed for imported private keys
  docs/web3-eth-accounts.rst
Labels: 1.x, Please Review, documentation

#3403 Upgrade swarm-js to ^0.1.40
  CHANGELOG.md
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
Labels: 1.x, Please Review, dependencies

#3421 Fix windows CI & lengthen verdaccio timeouts
  scripts/e2e.windows.sh
  scripts/js/basic_usage.js
  test/eth.accounts.wallet.js
  verdaccio.yml
Labels: 1.x, CI, Please Review

#3427 Simplify ENS E2E test
  .travis.yml
  package.json
  scripts/ci.sh
  scripts/e2e.ens.sh
  scripts/js/ens.js
  scripts/js/ens/1_initial_migration.js
  scripts/js/ens/truffle-config.js
  test/e2e.ens.js
  test/eth.ens.js
Labels: 1.x, Please Review, Testing

#3413 update gasPrice to getGasPrice in doc
  docs/web3-eth-accounts.rst
Labels: 1.x, Please Review, documentation
