Repository web3/web3.js, pull requests merged in 2020-06, with the labels that each got.

#3532 Add documentation for testing and CI
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  TESTING.md
  scripts/html/index.html
Labels: 1.x, Please Review, documentation

#3533 Add tests for transactionPollingTimeout
  docs/web3-eth.rst
  test/e2e.method.send.js
Labels: 1.x, Please Review, Testing, documentation

#3550 Add events `sending` and `sent` to tx submission, add arg `latestBlockHash` to event `confirmation`
  CHANGELOG.md
  docs/callbacks-promises-events.rst
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  packages/web3-core-method/src/index.js
  packages/web3-core/types/index.d.ts
  packages/web3-eth-ens/src/contracts/Registry.js
  packages/web3-eth-ens/src/lib/ResolverMethodHandler.js
  packages/web3-eth-ens/src/resources/ABI/Registry.js
  packages/web3-eth-ens/src/resources/ABI/Resolver.js
  test/e2e.contract.deploy.js
Labels: 1.x, Feature Request, Please Review, enhancement

#3469 Make maxListenersExceeded warning configurable
  docs/web3-eth.rst
  packages/web3-core-requestmanager/src/index.js
  packages/web3-eth/src/index.js
  test/3_givenProvider-ganache.js
  test/eth.maxListenersWarningThreshold.js
Labels: 1.x, bug

#3368 Adds the ENS registry for goerli testnet
  packages/web3-eth-ens/src/contracts/Registry.js
Labels: 2.x, enhancement

#3564 Add DOCUMENTATION.md to 0.20.7
  DOCUMENTATION.md
  README.md
Labels: 0.x.x, documentation

#3562 Add gnosis/dex E2E target
  .github/workflows/build.yml
  package.json
  scripts/ci.sh
  scripts/e2e.gnosis.dex.sh
  scripts/e2e.truffle.sh
  scripts/js/resolutions.js
Labels: 1.x, Testing

#3565 Fix wallet test suite race conditions
  test/eth.accounts.wallet.js
Labels: 1.x, Please Review, Testing

#3317 Extend `_txInputFormatter` with hex prefix check
  CHANGELOG.md
  packages/web3-core-helpers/src/formatters.js
  packages/web3-eth-contract/src/index.js
  test/formatters.inputTransactionFormatter.js
Labels: 1.x, Please Review, bug

#3378 Assign window.ethereum to givenProvider when available
  package-lock.json
  package.json
  packages/web3-bzz/src/index.js
  packages/web3-core-requestmanager/src/givenProvider.js
  test/1_givenProvider-ethereumProvider.js
  test/2_givenProvider-currentProvider.js
Labels: 1.x, EIP 1193

#3567 Ensure `toBlock` is not set when calling myContract.events.<eventName> or myContract.events.allEvents
  docs/web3-eth-contract.rst
  packages/web3-eth-contract/src/index.js
  test/e2e.contract.events.js
Labels: 1.x, bug

#3566 Fix WS clientConfig type and clarify docs
  docs/include_package-core.rst
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-providers-ws/README.md
Labels: 1.x, Please Review, documentation, types

#3575 Publish the test site to Netlify
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  README.md
  TESTING.md
  package.json
  scripts/e2e.cdn.sh
  scripts/html/index.html
Labels: 1.x, CI

#3561 Release - 1.2.9
  dist/web3.min.js
  lerna.json
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 1.x, release

#3581 Fix buffer incompatibility issue when used inside React (issue/3580)
  CHANGELOG.md
  packages/web3-eth-accounts/src/index.js
  test/e2e.account.wallet.js
Labels: 1.x, Investigate, bug

#3571 Handle revert reason errors for geth >= 1.9.5
  CHANGELOG.md
  TESTING.md
  packages/web3-core-helpers/src/errors.js
  packages/web3-core-method/src/index.js
  scripts/e2e.geth.automine.sh
  scripts/e2e.geth.instamine.sh
  test/e2e.method.call.js
Labels: 1.x, bug

#3497 Add string event integration tests
  test/e2e.contract.events.js
  test/sources/Basic.json
  test/sources/Basic.sol
Labels: 1.x, Please Review, Testing

#3365 Add tests for eth-contract errors
  packages/web3-core-helpers/src/errors.js
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-core-helpers/types/tests/errors-test.ts
  packages/web3-eth-contract/src/index.js
  test/contract.errors.js
Labels: 1.x, Please Review, QA

#3574 Add undefined callback check to websocket provider response queue
  packages/web3-providers-ws/src/index.js
Labels: 1.x, bug

#3594 updating docs: genesis is not a valid block identifier any longer
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
Labels: 1.x, documentation

#3597 Adds a missing list item number in the methods.myMethod.call docs
  docs/web3-eth-contract.rst
Labels: 1.x, documentation

#3598 Add Netlify to rtd
  RELEASE.md
  docs/getting-started.rst
  docs/index.rst
Labels: 1.x, documentation

#3596 format fromBlock param on resubscription
  packages/web3-core-subscriptions/src/subscription.js
Labels: 1.x, bug

#3599 replaced boolean "values" with types in d.ts
  packages/web3-eth/types/index.d.ts
Labels: 1.x, types

#3602 Remove invisible Â char from web3-utils files
  CHANGELOG.md
  packages/web3-utils/src/index.js
  packages/web3-utils/src/utils.js
Labels: 1.x, bug

#3586 Fix Function type log params decoding
  packages/web3-eth-abi/src/index.js
  test/eth.abi.decodeLog.js
Labels: 1.x, Please Review, bug

#3583 Fix accounts encrypt/decrypt for Webpack Buffer polyfill
  CHANGELOG.md
  package-lock.json
  package.json
  packages/web3-eth-accounts/src/index.js
  test/e2e.method.signing.js
  test/eth.accounts.encrypt-decrypt.js
Labels: 1.x, Please Review, bug
