Repository web3/web3.js, pull requests merged in 2020-02, with the labels that each got.

#3355 Security patch changes applied on 1.x
  CHANGELOG.md
  bower.json
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/src/config.js
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 1.x, security-patch

#3356 ENS address in test corrected
  test/eth.ens.js
Labels: 1.x

#3361 update the ENS registry address
  packages/web3-eth-ens/src/contracts/Registry.js
Labels: 2.x, enhancement

#3357 URL of the coveralls badge in the root readme file corrected
  README.md
Labels: 1.x, documentation

#3363 Use registry uplink timeout & non-conflicting package version
  scripts/e2e.mosaic.sh
  scripts/e2e.npm.publish.sh
  scripts/js/resolutions.js
  verdaccio.yml
Labels: 1.x, CI, QA

#3362 Refractoring/contracts
  packages/web3-eth-contract/src/index.js
Labels: 1.x, refactoring

#3366 Add npm alias scripts for generating html cov report locally
  package.json
Labels: 1.x, QA

#3367 Pull Request Template Improvement
  PULL_REQUEST_TEMPLATE.md
Labels: 1.x, Please Review, documentation

#3325 Implements all methods of the ENS registry
  CHANGELOG.md
  docs/web3-eth-ens.rst
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-ens/src/ENS.js
  packages/web3-eth-ens/src/contracts/Registry.js
  packages/web3-eth-ens/src/lib/ResolverMethodHandler.js
  packages/web3-eth-ens/src/ressources/ABI/Registry.js
  packages/web3-eth-ens/types/index.d.ts
  packages/web3-eth-ens/types/tests/ens-test.ts
  scripts/ci.sh
  test/e2e.ens.js
  test/eth.ens.js
Labels: 1.x, Feature Request, Please Review

#3381 Remove any-promise dependency
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-promievent/src/index.js
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/index.js
Labels: 1.x, Please Review, dependencies

#3375 Add E2E events tests for subscribe("logs")
  test/e2e.contract.events.js
Labels: 1.x, Please Review, QA

#3376 Add Windows CI job (Node 12)
  .travis.yml
  scripts/ci.sh
  scripts/e2e.npm.publish.sh
  scripts/e2e.windows.sh
  scripts/install.sh
  scripts/js/basic_usage.js
  verdaccio.yml
Labels: 1.x, CI, Please Review

#3390 Add bignumber.js to web3-core (for its types)
  CHANGELOG.md
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
Labels: 1.x, Please Review, types
