Repository web3/web3.js, pull requests merged in 2020-08, with the labels that each got.

#3673 Fix gnosis dex ci
  scripts/e2e.gnosis.dex.sh
Labels: 1.x, CI

#3674 CI: Fix restoring empty cache
  .github/workflows/build.yml
  scripts/ci.sh
  scripts/e2e.npm.publish.sh
  scripts/install.sh
Labels: 1.x, CI

#3649 Improve RequestManager send method
  CHANGELOG.md
  packages/web3-core-requestmanager/src/index.js
Labels: 1.x, Please Review, refactoring

#3672 docs: information about OR operation for topics
  docs/web3-eth-contract.rst
Labels: 1.x, documentation

#3679 Clarify estimateGas docs
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
Labels: 1.x, documentation

#3693 switch to wokring version of geth-dev-assistant
  package-lock.json
  package.json
Labels: CI

#3696 Update clearSubscriptions to have return value
  .gitignore
  CHANGELOG.md
  packages/web3-core-requestmanager/src/index.js
  test/eth.subscribe.ganache.js
Labels: 1.x, bug

#3661 Bump web3-providers-ipc oboe version to 2.1.5
  CHANGELOG.md
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
Labels: 1.x
