Repository web3/web3.js, pull requests merged in 2020-05, with the labels that each got.

#3451 Fix 3380: Add AbstractProvider
  packages/web3-core/types/index.d.ts
  packages/web3/types/tests/web3-test.ts
Labels: 1.x, types

#3454 web3-eth-contract: add typescript definitions for `methods` and `call`
  packages/web3-eth-contract/types/index.d.ts
Labels: 1.x, types

#3490 Update ABICoder dependency
  CHANGELOG.md
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-abi/src/index.js
  test/abi.encodeParameter.js
Labels: 1.x, Please Review

#3494 Throw when requests made after WS reconnect attempts are exhausted
  packages/web3-providers-ws/src/index.js
  test/websocket.ganache.js
Labels: 1.x, Please Review, bug

#3428 Add support for ENS contenthash methods
  docs/web3-eth-ens.rst
  package-lock.json
  package.json
  packages/web3-core-helpers/src/errors.js
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-core-helpers/types/tests/errors-test.ts
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/src/ENS.js
  packages/web3-eth-ens/src/config.js
  packages/web3-eth-ens/src/lib/ResolverMethodHandler.js
  packages/web3-eth-ens/src/lib/contentHash.js
  packages/web3-eth-ens/src/ressources/ABI/Resolver.js
  packages/web3-eth-ens/types/index.d.ts
  packages/web3-eth-ens/types/tests/ens-test.ts
  test/e2e.ens.js
  test/eth.ens.js
Labels: 1.x, Please Review

#3499 Add EIP-1193 compatible provider to AbstractProvider interface
  CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-core/types/index.d.ts
  packages/web3/types/tests/web3-test.ts
Labels: 1.x, EIP 1193, Please Review

#3504 Remove optional revert error return types from web3-eth TS definitions
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: 1.x, bug, types

#3502 Backfill logs when resubscribing
  packages/web3-core-subscriptions/src/subscription.js
  packages/web3-core-subscriptions/types/index.d.ts
  packages/web3-core-subscriptions/types/tests/subscriptions.tests.ts
  test/e2e.contract.events.js
Labels: 1.x, Please Review, bug

#3506 Build on push to `1.x`
  .github/workflows/build.yml
  test/eth.accounts.wallet.js
Labels: CI, Please Review

#3509 Fix WSS credentials Base64 encoding (for browser)
  CHANGELOG.md
  packages/web3-providers-ws/src/helpers.js
  test/e2e.contract.deploy.js
Labels: 1.x, Please Review, bug

#3518 Docs: fix newline in `sendTransaction` note
  docs/web3-eth.rst
Labels: 1.x, documentation

#3521 Update AbstractProvider and contract.methods TS definitions
  packages/web3-core/types/index.d.ts
  packages/web3-eth-contract/types/index.d.ts
  scripts/e2e.geth.automine.sh
  scripts/e2e.geth.instamine.sh
Labels: 1.x, Release Patch, types

#3511 Fix setContenthash docs formatting
  docs/web3-eth-ens.rst
Labels: 1.x, Release Patch, documentation

#3522 Update AbiCoder param formatting
  packages/web3-eth-abi/src/index.js
  test/abi.encodeParameter.js
Labels: 1.x, Release Patch

#3510 Release - 1.2.8
  CHANGELOG.md
  dist/web3.min.js
  docs/web3-eth-ens.rst
  lerna.json
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-core/types/index.d.ts
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-abi/src/index.js
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
  test/abi.encodeParameter.js
Labels: release

#3534 Replace @web3-js/websocket@1.0.29 with websocket@1.0.31
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-providers-ws/src/index.js
Labels: 1.x, Please Review, bug, dependencies

#3530 Allow e2e failures in CI
  .github/workflows/build.yml
  scripts/e2e.ganache.core.sh
  scripts/e2e.npm.publish.sh
Labels: 1.x, CI

#3517 Improve check if a provider supports subscriptions
  packages/web3-core-method/src/index.js
  test/method.buildCall.js
Labels: 1.x, Please Review

#3526 Fix `account.hashMessage` with non-ASCII characters
  packages/web3-eth-accounts/src/index.js
  test/eth.accounts.sign.js
Labels: 1.x, bug

#3531 Fix eth.clearSubscriptions size property de-referencing bug
  CHANGELOG.md
  packages/web3-eth/src/index.js
  test/eth.subscribe.ganache.js
Labels: 1.x, Please Review, bug

#3536 Upgrade from `@web3-js/scrypt-shim` to `scrypt-js`
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/index.js
  packages/web3-providers-ws/package-lock.json
Labels: 1.x, dependencies

#3541 Fix abi param encoding for tuple arrays
  packages/web3-eth-abi/src/index.js
  test/abi.encodeParameter.js
Labels: 1.x, Please Review, bug

#3543 Docs: small typos and grammar fixes
  docs/callbacks-promises-events.rst
  docs/getting-started.rst
  docs/include_package-core.rst
  docs/index.rst
  docs/web3-bzz.rst
  docs/web3-eth-abi.rst
  docs/web3-eth-accounts.rst
  docs/web3-eth-contract.rst
  docs/web3-eth-ens.rst
  docs/web3-eth-iban.rst
  docs/web3-eth-net.rst
  docs/web3-eth-personal.rst
  docs/web3-eth-subscribe.rst
  docs/web3-eth.rst
  docs/web3-net.rst
  docs/web3-shh.rst
  docs/web3-utils.rst
  docs/web3.rst
Labels: 1.x, documentation

#3545 Add ts bindings for `handleRevert`
  packages/web3-core-method/types/index.d.ts
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-contract/types/tests/contract-test.ts
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: 1.x, types

#3551 web3-core-promievent README.md fix
  packages/web3-core-promievent/README.md
Labels: 1.x, documentation
