Repository web3/web3.js, pull requests merged in 2020-04, with the labels that each got.

#3453 Move @types/node to dev dependencies
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 1.x, Please Review, dependencies, types

#3455 Fix historical event subscriptions when made as first provider request
  packages/web3-core-subscriptions/src/subscription.js
  test/e2e.contract.events.js
Labels: 1.x, Please Review

#3420 Fetch revert reason for sendSignedTransaction
  CHANGELOG.md
  packages/web3-core-method/src/index.js
  packages/web3-eth/src/index.js
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
  test/e2e.method.signing.js
Labels: 1.x, Please Review

#3437 Gas Type Added in AbiItem
  CHANGELOG.md
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/json-interface-method-to-string-test.ts
  test/contract.encodeABI.js
Labels: 1.x, types

#3467 Add docs note for Geth v1.9.12 `eth_call` change
  CHANGELOG.md
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
Labels: 1.x, documentation

#3477 Update deps and tests for Github Actions
  .github/workflows/build.yml
  package-lock.json
  package.json
  test/e2e.contract.deploy.js
  test/e2e.method.call.js
Labels: 1.x, CI, Please Review, dependencies

#3468 Upgrade CI Provider from Travis to GH Actions
  .github/workflows/build.yml
  .npmignore
  .travis.yml
  CHANGELOG.md
  README.md
  circle.yml
  karma.conf.js
  package-lock.json
  package.json
  scripts/ci.sh
  scripts/coveralls.sh
  scripts/e2e.ganache.core.sh
  scripts/e2e.mosaic.sh
  scripts/e2e.npm.publish.sh
  scripts/e2e.truffle.sh
  scripts/install.sh
  test/e2e.contract.deploy.js
  test/e2e.method.call.js
  verdaccio.yml
Labels: 1.x, CI, in progress

#3479 Fix CI build error from `dtslint`
  CHANGELOG.md
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-bzz/types/index.d.ts
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-helpers/types/index.d.ts
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-method/types/index.d.ts
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core-subscriptions/types/index.d.ts
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-core/types/index.d.ts
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-abi/types/index.d.ts
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/types/index.d.ts
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/types/index.d.ts
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-iban/types/index.d.ts
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth-personal/types/index.d.ts
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-eth/types/index.d.ts
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-net/types/index.d.ts
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-http/types/index.d.ts
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ipc/types/index.d.ts
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-providers-ws/types/index.d.ts
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-shh/types/index.d.ts
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3-utils/types/index.d.ts
  packages/web3/package-lock.json
  packages/web3/package.json
  packages/web3/types/index.d.ts
Labels: 1.x, CI

#3476 Mark html file with commit & branch in surge e2e test
  .github/workflows/build.yml
  scripts/e2e.cdn.sh
  scripts/html/index.html
Labels: 1.x

#3481 Fix mosaic_e2e job error when CI run for fork PR
  .github/workflows/build.yml
Labels: 1.x, CI

#3470 Release - 1.2.7
  CHANGELOG.md
  dist/web3.min.js
  gulpfile.js
  lerna.json
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 1.x, release

#3486 Emit "error" and "end" events on WebsocketProvider close
  CHANGELOG.md
  packages/web3-core-requestmanager/src/index.js
  test/eth.subscribe.ganache.js
  test/websocket.ganache.js
Labels: 1.x, Please Review, bug

#3489 Add provider existence check to WebsocketProvider close emitter logic
  packages/web3-core-requestmanager/src/index.js
Labels: 1.x, bug

#3487 Add --ignore-scripts to lerna publish command for E2E publishing tests
  scripts/e2e.npm.publish.sh
Labels: 1.x, CI

#3463 Improve clarity of HttpProvider keepAlive value
  CHANGELOG.md
  packages/web3-providers-http/src/index.js
Labels: 1.x, refactoring

#3478 Small fix on web3-eth.rst documentation
  docs/web3-eth.rst
Labels: 1.x, documentation

#3495 Expose bundlesize token in GH Actions CI
  .github/workflows/build.yml
Labels: 1.x, CI, Please Review

#3460 Introduce Review and Release Guidelines
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTIONS.md
  README.md
  RELEASE.md
  REVIEW.md
Labels: Please Review, documentation
