Repository web3/web3.js, pull requests merged in 2020-07, with the labels that each got.

#3609 Add caching to ci
  .github/workflows/build.yml
  karma.conf.js
  package-lock.json
  package.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
  scripts/install.sh
  test/utils.toTwosComplement.js
Labels: 1.x, CI, Please Review

#3618 Upgrade build process from gulp to webpack
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  RELEASE.md
  gulpfile.js
  karma.conf.js
  package-lock.json
  package.json
  packages/web3-bzz/README.md
  packages/web3-core-helpers/README.md
  packages/web3-core-method/README.md
  packages/web3-core-promievent/README.md
  packages/web3-core-requestmanager/README.md
  packages/web3-core-subscriptions/README.md
  packages/web3-core/README.md
  packages/web3-eth-abi/README.md
  packages/web3-eth-accounts/README.md
  packages/web3-eth-contract/README.md
  packages/web3-eth-ens/README.md
  packages/web3-eth-iban/README.md
  packages/web3-eth-personal/README.md
  packages/web3-eth/README.md
  packages/web3-net/README.md
  packages/web3-providers-http/README.md
  packages/web3-providers-ipc/README.md
  packages/web3-providers-ws/README.md
  packages/web3-shh/README.md
  packages/web3-utils/README.md
  test/contract.encodeABI.js
  test/contract.js
  webpack.config.js
Labels: 1.x, Please Review, enhancement

#3626 Fix `bundlesize` ci check for PRs from forks
  package.json
Labels: 1.x, CI

#3630 Upgrade github actions/checkout to v2
  .github/workflows/build.yml
Labels: 1.x, CI

#3625 Use provider.request() when available
  packages/web3-core-requestmanager/src/index.js
  test/1_givenProvider-ethereumProvider.js
Labels: 1.x, EIP-1193

#3635 Fix readme bundled file reference
  README.md
Labels: 1.x, documentation

#3622 Add unit tests for isHex and isHexStrict.
  test/utils.isHex.js
  test/utils.isHexStrict.js
Labels: 1.x, Testing

#3633 Release - 1.2.10
  dist/web3.min.js
  dist/web3.min.js.map
  lerna.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 1.x, release

#3647 Fix Provider.request response
  CHANGELOG.md
  packages/web3-core-requestmanager/src/index.js
  test/1_givenProvider-ethereumProvider.js
Labels: 1.x, Please Review, bug

#3648 Release - 1.2.11
  .github/workflows/build.yml
  CHANGELOG.md
  dist/web3.min.js
  dist/web3.min.js.map
  lerna.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: 1.x, release

#3652 Add typescript support
  .github/workflows/build.yml
  .gitignore
  CHANGELOG.md
  package-lock.json
  package.json
  packages/web3-bzz/package.json
  packages/web3-bzz/tsconfig.json
  packages/web3-core-helpers/package.json
  packages/web3-core-helpers/tsconfig.json
  packages/web3-core-method/package.json
  packages/web3-core-method/tsconfig.json
  packages/web3-core-promievent/package.json
  packages/web3-core-promievent/tsconfig.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-requestmanager/tsconfig.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core-subscriptions/tsconfig.json
  packages/web3-core/package.json
  packages/web3-core/src/index.js
  packages/web3-core/tsconfig.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-abi/tsconfig.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/tsconfig.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/tsconfig.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/tsconfig.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-iban/tsconfig.json
  packages/web3-eth-personal/package.json
  packages/web3-eth-personal/tsconfig.json
  packages/web3-eth/package.json
  packages/web3-eth/tsconfig.json
  packages/web3-net/package.json
  packages/web3-net/tsconfig.json
  packages/web3-providers-http/package.json
  packages/web3-providers-http/tsconfig.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ipc/tsconfig.json
  packages/web3-providers-ws/package.json
  packages/web3-providers-ws/tsconfig.json
  packages/web3-shh/package.json
  packages/web3-shh/tsconfig.json
  packages/web3-utils/package.json
  packages/web3-utils/tsconfig.json
  packages/web3/package.json
  packages/web3/tsconfig.json
  scripts/ci.sh
  scripts/e2e.ganache.sh
  tsconfig.json
  webpack.config.js
Labels: 1.x

#3658 include prs with stalebnot
  .github/workflows/stale.yml
Labels: CI, enhancement

#3660 Fix parsing of non-`eth_subscription` provider events
  CHANGELOG.md
  packages/web3-core-requestmanager/src/index.js
Labels: 1.x, bug
