Repository web3/web3.js, pull requests merged in 2021-07, with the labels that each got.

#4069 remove underscore
  CHANGELOG.md
  package.json
  packages/web3-bzz/package.json
  packages/web3-bzz/src/index.js
  packages/web3-core-helpers/package.json
  packages/web3-core-helpers/src/formatters.js
  packages/web3-core-method/package.json
  packages/web3-core-method/src/index.js
  packages/web3-core-requestmanager/package.json
  packages/web3-core-requestmanager/src/index.js
  packages/web3-core-subscriptions/package.json
  packages/web3-core-subscriptions/src/subscription.js
  packages/web3-eth-abi/package.json
  packages/web3-eth-abi/src/index.js
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/index.js
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/src/index.js
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/src/ENS.js
  packages/web3-eth-ens/src/contracts/Registry.js
  packages/web3-eth-ens/src/lib/ResolverMethodHandler.js
  packages/web3-eth/package.json
  packages/web3-eth/src/getNetworkType.js
  packages/web3-eth/src/index.js
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ipc/src/index.js
  packages/web3-providers-ws/package.json
  packages/web3-utils/package.json
  packages/web3-utils/src/index.js
  packages/web3-utils/src/soliditySha3.js
  packages/web3-utils/src/utils.js
  test/abi.decodeParameter.js
  test/eth.accounts.signTransaction.js
  test/helpers/test.method.js
  test/utils.encodePacked.js
  test/utils.soliditySha3.js
Labels: 1.x

#4171 EIP 1559 Debug #2
  packages/web3-eth-accounts/src/index.js
  scripts/e2e.geth.automine.sh
  scripts/js/ens.js
  test/e2e.contract.deploy.js
  test/e2e.contract.events.js
  test/e2e.ens.js
  test/e2e.method.call.js
  test/e2e.method.send.js
  test/e2e.method.signing.js
  test/eth.accounts.signTransaction.js
  test/helpers/test.utils.js
Labels: 1.x

#4182 web3-providers-base@1.0.0-alpha.1
  packages/web3-core-requestmanager/package.json
  packages/web3-providers-base/CHANGELOG.md
  packages/web3-providers-base/package.json
  packages/web3-providers-http/package.json
  yarn.lock
Labels: 4.x, Release

#4151 [Docs] Fixed a broken link
  docs/web3-bzz.rst
Labels: 1.x

#4088 Possible typo in docs
  docs/callbacks-promises-events.rst
Labels: 1.x

#3967 Typically you will have only one Web3 connection, use const
  docs/getting-started.rst
Labels: Documentation, Review Needed

#4147 [Docs] Updated solidity example to modern syntax
  docs/glossary.rst
Labels: 1.x, Documentation

#4054 add nonce to send options.
  CHANGELOG.md
  docs/web3-eth-contract.rst
  packages/web3-eth-contract/types/index.d.ts
Labels: 1.x, Documentation

#4155 EIP1559
  CHANGELOG.md
  package-lock.json
  packages/web3-core-helpers/src/formatters.js
  packages/web3-eth-accounts/src/index.js
  scripts/e2e.geth.automine.sh
  scripts/e2e.geth.instamine.sh
  scripts/js/ens.js
  test/e2e.contract.deploy.js
  test/e2e.contract.events.js
  test/e2e.ens.js
  test/e2e.method.call.js
  test/e2e.method.send.js
  test/e2e.method.signing.js
  test/eth.accounts.signTransaction.js
  test/formatters.outputTransactionFormatter.js
  test/helpers/test.utils.js
Labels: 1.x

#4188 Update docs 2
  CHANGELOG.md
  docs/callbacks-promises-events.rst
  docs/getting-started.rst
  docs/glossary.rst
  docs/include_package-core.rst
  docs/web3-bzz.rst
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  docs/web3-shh.rst
  packages/web3-eth-contract/types/index.d.ts
Labels: 1.x

#4190 eth-feehistory docs
  CHANGELOG.md
  docs/web3-eth.rst
Labels: 1.x

#4191 eth_feeHistory (EIP 1559)
  CHANGELOG.md
  docs/web3-eth.rst
  packages/web3-eth/src/index.js
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
  packages/web3-utils/src/index.js
  packages/web3-utils/src/utils.js
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/to-number-test.ts
  test/eth.feeHistory.js
  test/eth_methods.js
  test/utils.hexToNumber.js
  test/utils.toNumber.js
Labels: 1.x

#4192 Update 1.5.0 with eth_feeHistory PR 4191
  CHANGELOG.md
  docs/callbacks-promises-events.rst
  docs/getting-started.rst
  docs/glossary.rst
  docs/include_package-core.rst
  docs/web3-bzz.rst
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  docs/web3-shh.rst
  packages/web3-eth-contract/types/index.d.ts
  packages/web3-eth/src/index.js
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
  packages/web3-utils/src/index.js
  packages/web3-utils/src/utils.js
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/to-number-test.ts
  test/eth.feeHistory.js
  test/eth_methods.js
  test/utils.hexToNumber.js
  test/utils.toNumber.js
Labels: 1.x, Release Patch

#4193 Update CHANGELOG
  CHANGELOG.md
Labels: 1.x

#4198 Release web3-providers-http@4.0.0-alpha.0
  packages/web3-core-requestmanager/package.json
  packages/web3-providers-http/package.json
Labels: 4.x, Release

#4199 Release web3-core-requestmanager@4.0.0-alpha.0
  packages/web3-core-requestmanager/package.json
  packages/web3-eth/package.json
Labels: 4.x, Release

#4200 Release web3-eth@4.0.0-alpha.0
  packages/web3-eth/package.json
Labels: 4.x, Release

#4207 Revert e2e.ganache.core.sh change
  CHANGELOG.md
  scripts/e2e.ganache.core.sh
Labels: 3.x, Release Patch

#4217 Closes #4210, 4211 - allow non-hex values for eip1559 gas params
  CHANGELOG.md
  packages/web3-core-helpers/src/formatters.js
  test/eth.accounts.signTransaction.js
  test/formatters.inputTransactionFormatter.js
Labels: P1
