Repository web3/web3.js, pull requests merged in 2021-11, with the labels that each got.

#4471 web3 utils hashing encoding 4.x
  packages/web3-common/src/formatters.ts
  packages/web3-common/test/unit/formatters.test.ts
  packages/web3-utils/package.json
  packages/web3-utils/src/converters.ts
  packages/web3-utils/src/errors.ts
  packages/web3-utils/src/hash.ts
  packages/web3-utils/src/types.ts
  packages/web3-utils/src/validation.ts
  packages/web3-utils/test/fixtures/hash.ts
  packages/web3-utils/test/unit/hash.test.ts
  yarn.lock
Labels: 4.x

#4511 Update comment web3.rst
  CHANGELOG.md
  docs/web3.rst
Labels: Review Needed

#4452 Fix buggy `BlockHeader` ts interface
  packages/web3-eth/types/index.d.ts
  test/eth.subscribe.js
Labels: 1.x, Review Needed

#4527 Improve timeout handling for the block polling for confirmation
  CHANGELOG.md
  docs/web3.rst
  packages/web3-core-method/src/index.js
Labels: 1.x

#4514 web3 utils validation
  packages/web3-utils/src/errors.ts
  packages/web3-utils/src/hash.ts
  packages/web3-utils/src/types.ts
  packages/web3-utils/src/validation.ts
  packages/web3-utils/test/fixtures/converters.ts
  packages/web3-utils/test/fixtures/hash.ts
  packages/web3-utils/test/fixtures/string_manipulation.ts
  packages/web3-utils/test/fixtures/validation.ts
  packages/web3-utils/test/unit/hash.test.ts
  packages/web3-utils/test/unit/validation.test.ts
Labels: 4.x

#4519 Create `BatchRequest` class to handle JsonRpc batch feature
  packages/web3-common/src/constants.ts
  packages/web3-common/src/deferred_promise.ts
  packages/web3-common/src/errors.ts
  packages/web3-common/src/index.ts
  packages/web3-common/src/json_rpc.ts
  packages/web3-common/src/types.ts
  packages/web3-common/src/web3_base_provider.ts
  packages/web3-common/test/unit/__snapshots__/errors.test.ts.snap
  packages/web3-core/src/web3_batch_request.ts
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-core/src/web3_subscriptions.ts
  packages/web3-core/test/unit/web3_batch_request.test.ts
  packages/web3-core/test/unit/web3_request_manager.test.ts
  packages/web3-providers-http/src/index.ts
Labels: 4.x

#4434 websocket provider
  packages/web3-common/src/errors.ts
  packages/web3-common/src/types.ts
  packages/web3-common/src/web3_base_provider.ts
  packages/web3-common/test/unit/__snapshots__/errors.test.ts.snap
  packages/web3-common/test/unit/errors.test.ts
  packages/web3-providers-ws/.eslintignore
  packages/web3-providers-ws/.eslintrc.js
  packages/web3-providers-ws/.gitignore
  packages/web3-providers-ws/.npmignore
  packages/web3-providers-ws/.npmrc
  packages/web3-providers-ws/.prettierignore
  packages/web3-providers-ws/.prettierrc.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/README.md
  packages/web3-providers-ws/assets/logo/web3js.ai
  packages/web3-providers-ws/assets/logo/web3js.jpg
  packages/web3-providers-ws/assets/logo/web3js.svg
  packages/web3-providers-ws/package.json
  packages/web3-providers-ws/src/deferred_promise.ts
  packages/web3-providers-ws/src/index.ts
  packages/web3-providers-ws/src/types.ts
  packages/web3-providers-ws/test/.eslintrc.js
  packages/web3-providers-ws/test/config/jest.config.js
  packages/web3-providers-ws/test/config/setup.js
  packages/web3-providers-ws/test/integration/jest.config.js
  packages/web3-providers-ws/test/integration/setup.js
  packages/web3-providers-ws/test/tsconfig.json
  packages/web3-providers-ws/test/unit/constructor.test.ts
  packages/web3-providers-ws/test/unit/jest.config.js
  packages/web3-providers-ws/tsconfig.json
Labels: 4.x

#4513 Strong type support for Eth API
  packages/web3-common/src/deferred_promise.ts
  packages/web3-common/src/eth_execution_api.ts
  packages/web3-common/src/index.ts
  packages/web3-common/src/types.ts
  packages/web3-common/src/web3_base_provider.ts
  packages/web3-core/src/types.ts
  packages/web3-core/src/utils.ts
  packages/web3-core/src/web3_context.ts
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-core/src/web3_subscriptions.ts
  packages/web3-core/test/unit/fixtures/example_subscription.ts
  packages/web3-core/test/unit/web3_request_manager.test.ts
  packages/web3-core/test/unit/web3_subscription.test.ts
  packages/web3-core/test/unit/web3_subscription_manager.test.ts
  packages/web3-providers-http/src/index.ts
  packages/web3-providers-http/test/unit/implemented_methods.test.ts
  packages/web3-providers-ws/README.md
  packages/web3-providers-ws/src/index.ts
  packages/web3-providers-ws/src/types.ts
  packages/web3-utils/src/types.ts
  yarn.lock
Labels: 4.x

#4529 updating getFeeHistory input type
  CHANGELOG.md
  packages/web3-eth/src/index.js
  test/eth.feeHistory.js
Labels: 1.x

#4565 Create web3-eth-contract package structure for the 4.x
  packages/web3-eth-contract/.eslintignore
  packages/web3-eth-contract/.eslintrc.js
  packages/web3-eth-contract/.gitignore
  packages/web3-eth-contract/.npmignore
  packages/web3-eth-contract/.npmrc
  packages/web3-eth-contract/.prettierignore
  packages/web3-eth-contract/.prettierrc.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/README.md
  packages/web3-eth-contract/assets/logo/web3js.ai
  packages/web3-eth-contract/assets/logo/web3js.jpg
  packages/web3-eth-contract/assets/logo/web3js.svg
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/src/errors.ts
  packages/web3-eth-contract/src/index.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-contract/test/.eslintrc.js
  packages/web3-eth-contract/test/config/jest.config.js
  packages/web3-eth-contract/test/config/setup.js
  packages/web3-eth-contract/test/integration/jest.config.js
  packages/web3-eth-contract/test/integration/setup.js
  packages/web3-eth-contract/test/tsconfig.json
  packages/web3-eth-contract/test/unit/constructor.test.ts
  packages/web3-eth-contract/test/unit/jest.config.js
  packages/web3-eth-contract/tsconfig.json
Labels: 4.x

#4567 Update all the dependencies for the 4.x rewrite
  package.json
  packages/web3-common/package.json
  packages/web3-common/src/web3_base_provider.ts
  packages/web3-common/src/web3_base_wallet.ts
  packages/web3-common/test/unit/formatters.test.ts
  packages/web3-core/package.json
  packages/web3-core/src/web3_context.ts
  packages/web3-core/test/unit/web3_batch_request.test.ts
  packages/web3-core/test/unit/web3_config.test.ts
  packages/web3-core/test/unit/web3_context.test.ts
  packages/web3-core/test/unit/web3_request_manager.test.ts
  packages/web3-core/test/unit/web3_subscription.test.ts
  packages/web3-core/test/unit/web3_subscription_manager.test.ts
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/README.md
  packages/web3-eth-contract/package.json
  packages/web3-eth/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-http/src/index.ts
  packages/web3-providers-http/test/unit/constructor.test.ts
  packages/web3-providers-ws/package.json
  packages/web3-providers-ws/src/index.ts
  packages/web3-utils/package.json
  tools/eslint-config-web3-base/package.json
  tools/eslint-config-web3-base/ts-jest.js
  tools/eslint-config-web3-base/ts.js
  tools/web3-packagetemplate/package.json
  yarn.lock
Labels: 4.x

#4232 Updates Transaction and TransactionConfig types
  CHANGELOG.md
  packages/web3-core/types/index.d.ts
Labels: 1.x
