Repository web3/web3.js, pull requests merged in 2021-08, with the labels that each got.

#4213 Accept predefined block numbers for eth_feeHistory
  packages/web3-eth/src/index.js
  test/eth.feeHistory.js
Labels: 1.x

#4220 EIP-1559 support for web3.eth.sendTransaction
  CHANGELOG.md
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-method/src/index.js
  packages/web3-core-method/tsconfig.json
  test/contract.js
  test/e2e.method.send.js
  test/eth.sendTransaction.js
  test/helpers/test.method.js
  test/method.buildCall.js
Labels: 1.x

#4224 Add block tag support for eth_feeHistory
  CHANGELOG.md
  packages/web3-eth/src/index.js
  test/eth.feeHistory.js
Labels: 1.x

#4241 Don't default type = 0x0 for eth_sendTransaction and eth_sendRawTransaction
  CHANGELOG.md
  packages/web3-core-method/src/index.js
  packages/web3-eth-accounts/src/index.js
  test/contract.js
  test/eth.sendTransaction.js
  test/method.buildCall.js
Labels: Bug, 1.x, P0

#4248 Refactors from fixing tsc errors
  packages/web3-core-types/src/types.ts
  packages/web3-eth2-beaconchain/src/index.ts
  packages/web3-providers-http/src/index.ts
  yarn.lock
Labels: 4.x

#4260 Small refactors of 4236
  packages/web3-core-types/src/types.ts
  packages/web3-providers-http/src/index.ts
Labels: 4.x

#4236 4.x - Rewrite eth2 beacon
  .github/workflows/build.yml
  packages/web3-core-provider/test/unit/initWeb3Provider.test.ts
  packages/web3-core-types/src/types.ts
  packages/web3-eth/src/index.ts
  packages/web3-eth2-beaconchain/.eslintrc.js
  packages/web3-eth2-beaconchain/.gitignore
  packages/web3-eth2-beaconchain/.prettierignore
  packages/web3-eth2-beaconchain/.prettierrc.json
  packages/web3-eth2-beaconchain/CHANGELOG.md
  packages/web3-eth2-beaconchain/README.md
  packages/web3-eth2-beaconchain/jest.config.js
  packages/web3-eth2-beaconchain/package.json
  packages/web3-eth2-beaconchain/src/index.ts
  packages/web3-eth2-beaconchain/src/types.ts
  packages/web3-eth2-beaconchain/test/unit/initWeb3Provider.test.ts
  packages/web3-eth2-beaconchain/tsconfig.json
  packages/web3-providers-eip1193/src/index.ts
  packages/web3-providers-eip1193/test/unit/constructor.test.ts
  packages/web3-providers-eip1193/test/unit/request.test.ts
  packages/web3-providers-eip1193/test/unit/setWeb3Client.test.ts
  packages/web3-providers-http/src/index.ts
  packages/web3-providers-ws/src/index.ts
  packages/web3-providers-ws/test/unit/request.test.ts
  yarn.lock
Labels: 4.x
