Repository web3/web3.js, pull requests merged in 2021-09, with the labels that each got.

#3947 Feature/improve xml request error handling
  CHANGELOG.md
  packages/web3-core-helpers/src/errors.js
  packages/web3-providers-http/src/index.js
  test/helpers/FakeXHR2.js
Labels: Enhancement, Review Needed, P2

#4277 EIP-1559 Fix Issue #4258
  CHANGELOG.md
  packages/web3-core-method/src/index.js
  test/method.buildCall.js
Labels: 1.x

#4307 Add missing build step (closes #4119)
  RELEASE.md
Labels: 1.x

#4330 Format baseFeePerGas to number in returned blocks - Closes #4326
  CHANGELOG.md
  docs/web3-eth.rst
  packages/web3-core-helpers/src/formatters.js
  packages/web3-eth/types/index.d.ts
  test/formatters.outputBlockFormatter.js
Labels: 1.x

#4390 Partially replace the use of eth-lib
  CHANGELOG.md
  package-lock.json
  package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/src/index.js
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3-utils/src/utils.js
  packages/web3-utils/tsconfig.json
  test/utils.sha3.js
Labels: 1.x

#4365 Init bug_report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: 1.x, 4.x

#4370 Init feature_request template - Closes #4367
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: Enhancement, 1.x, 4.x

#4397 doc: fix example in web3.eth.personal
  docs/web3-eth-personal.rst
Labels: Documentation, 1.x

#4377 Migrate all errors to web3-common as error constructors
  packages/web3-common/README.md
  packages/web3-common/src/constants.ts
  packages/web3-common/src/errors.ts
  packages/web3-common/src/index.ts
  packages/web3-common/src/types.ts
  packages/web3-common/test/integration/setup.js
  packages/web3-common/test/tsconfig.json
  packages/web3-common/test/unit/__snapshots__/errors.test.ts.snap
  packages/web3-common/test/unit/constructor.test.ts
  packages/web3-common/test/unit/errors.test.ts
  templates/test/tsconfig.json.tmpl
  tools/web3-packagetemplate/README.md
  tools/web3-packagetemplate/test/integration/setup.js
Labels: 4.x

#4408 Update submit an issue link
  README.md
Labels: 4.x

#4395 Create base provider and wallet interfaces
  packages/web3-common/src/index.ts
  packages/web3-common/src/types.ts
  packages/web3-common/src/web3_base_provider.ts
  packages/web3-common/src/web3_base_wallet.ts
  templates/.prettierignore.tmpl
Labels: 4.x
