Repository web3/web3.js, pull requests merged in 2021-10, with the labels that each got.

#4412 Init something_else issue template - Closes #4368
  .github/ISSUE_TEMPLATE/something_else.yml
Labels: 1.x, 4.x

#4411 Init documentation issue template - Closes 4410
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: 1.x, 4.x

#4300 Fix unsubscribe and add a test (#4058)
  CHANGELOG.md
  packages/web3-core-subscriptions/src/subscription.js
  test/eth.subscribe.ganache.js
Labels: 1.x

#4332 eth_createAccessList - Closes #4081
  CHANGELOG.md
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  packages/web3-eth-contract/src/index.js
  packages/web3-eth/src/index.js
  test/e2e.eth.createAccessList.js
  test/eth.createAccessList.js
Labels: 1.x

#4409 Update doc example for web3.eth.personal (#4397)
  CHANGELOG.md
  docs/web3-eth-personal.rst
Labels: Documentation, 1.x

#4405 Migrate data type conversion utils functions from 1.x
  packages/web3-utils/README.md
  packages/web3-utils/src/converters.ts
  packages/web3-utils/src/errors.ts
  packages/web3-utils/src/hash.ts
  packages/web3-utils/src/types.ts
  packages/web3-utils/src/validation.ts
  packages/web3-utils/test/fixtures/converters.ts
  packages/web3-utils/test/unit/constructor.test.ts
  packages/web3-utils/test/unit/converters.test.ts
Labels: 4.x
