Repository web3/web3.js, pull requests merged in 2021-03, with the labels that each got.

#3950 Merging geth-dev-assistant updates
  CHANGELOG.md
  package-lock.json
  package.json
Labels: Bug, P0, dependencies

#3943 Replace hardcoded infura endpoints
  .github/workflows/build.yml
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/html/index.html
  scripts/js/basic_usage.js
Labels: Bug, P0

#3917 use posinstall to do deprecation warnings
  CHANGELOG.md
  packages/web3-bzz/package.json
  packages/web3-bzz/src/index.js
  packages/web3-shh/package.json
  packages/web3-shh/src/index.js
  packages/web3/package.json
Labels: Bug, P2

#3817 add nvmrc file
  .nvmrc
  CHANGELOG.md
Labels: Enhancement, P3

#3971 Wyatt/1.3.5 merge conflicts
  CHANGELOG.md
  README.md
  dist/web3.min.js
  dist/web3.min.js.map
  docs/include_package-core.rst
  package.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-iban/src/index.js
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-eth2-beaconchain/package.json
  packages/web3-eth2-core/package.json
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package.json
  packages/web3/package.json
Labels: P1

#3982 Add 3.x to build triggers
  .github/workflows/build.yml
Labels: 3.x, P0

#3909 Deprecate shh and bzz
  CHANGELOG.md
  README.md
  docs/getting-started.rst
  docs/include_package-core.rst
  docs/include_package-net.rst
  docs/index.rst
  docs/web3-bzz.rst
  docs/web3-eth-subscribe.rst
  docs/web3-net.rst
  docs/web3-shh.rst
  docs/web3.rst
  packages/web3-bzz/README.md
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-bzz/src/index.js
  packages/web3-bzz/tsconfig.json
  packages/web3-bzz/types/index.d.ts
  packages/web3-bzz/types/tests/bzz-test.ts
  packages/web3-bzz/types/tsconfig.json
  packages/web3-bzz/types/tslint.json
  packages/web3-shh/README.md
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-shh/src/index.js
  packages/web3-shh/tsconfig.json
  packages/web3-shh/types/index.d.ts
  packages/web3-shh/types/tests/shh-test.ts
  packages/web3-shh/types/tsconfig.json
  packages/web3-shh/types/tslint.json
  packages/web3/package.json
  packages/web3/src/index.js
  packages/web3/types/index.d.ts
  packages/web3/types/tests/web3-test.ts
  scripts/e2e.ganache.core.sh
  scripts/js/resolutions.js
  test/1_givenProvider-ethereumProvider.js
  test/2_givenProvider-currentProvider.js
  test/batch.js
  test/helpers/test.subscription.js
  test/provider.js
  test/setProvider.js
  test/shh.post.js
  test/shh.subscribe.js
  test/shh_methods.js
  test/web3_methods.js
Labels: In Progress, P2
