Repository web3/web3.js, pull requests merged in 2022-12, with the labels that each got.

#5669 Remove erroneous set provider code for Contract constructor
  CHANGELOG.md
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/unit/contract.test.ts
Labels: 4.x

#5648 Empty string in smart contract
  fixtures/build/MyContract.json
  fixtures/build/MyContract.ts
  fixtures/contracts/MyContract.sol
  packages/web3-eth-contract/test/fixtures/MyContract.json
  packages/web3-eth-contract/test/fixtures/MyContract.ts
  packages/web3-eth-contract/test/integration/contract_empty_string.test.ts
Labels: 4.x

#5697 Release patch/4.0.1 alpha.2/solve merge conflicts
  CHANGELOG.md
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-validator/CHANGELOG.md
Labels: Release Patch, 4.x

#5664 v4.0.1-alpha.2
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-packagetemplate/CHANGELOG.md
  tools/web3-plugin-example/CHANGELOG.md
  tools/web3-plugin-example/package.json
Labels: Release, 4.x
