Repository web3/web3.js, pull requests merged in 2022-10, with the labels that each got.

#5485 4.x Contracts Tests e2e
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/contract_clone.test.ts
  packages/web3-eth-contract/test/integration/contract_deploy.test.ts
  packages/web3-eth-contract/test/integration/contract_erc20.test.ts
  packages/web3-eth-contract/test/integration/contract_erc721.test.ts
  packages/web3-eth-contract/test/integration/local_account/contract_deploy.test.ts
  packages/web3-eth-contract/test/integration/local_account/contract_erc20.test.ts
  packages/web3-eth-contract/test/integration/local_account/contract_erc721.test.ts
  scripts/system_tests_utils.ts
Labels: 4.x

#5507 Temporarily skip a failing test
  packages/web3-eth-contract/test/integration/contract_methods_errors.test.ts
Labels: 4.x

#5483 Hardfork and chain validation for validateTransactionForSigning
  packages/web3-core/CHANGELOG.md
  packages/web3-core/src/web3_config.ts
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/errors/core_errors.ts
  packages/web3-errors/src/errors/transaction_errors.ts
  packages/web3-errors/src/index.ts
  packages/web3-eth-contract/test/unit/contract.test.ts
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/src/validation.ts
Labels: 4.x

#5534 Fix lint errors
  packages/web3-eth-ens/test/unit/constructor.test.ts
  packages/web3-eth-ens/test/unit/ens.test.ts
  packages/web3-eth-ens/test/unit/registry.test.ts
  packages/web3-eth-ens/test/unit/resolver.test.ts
Labels: 4.x

#5525 Nikos/5430/validator unit test coverage
  packages/web3-validator/test/fixtures/abi_to_json_schema.ts
  packages/web3-validator/test/fixtures/errors.ts
  packages/web3-validator/test/fixtures/validation.ts
  packages/web3-validator/test/unit/default_validator.test.ts
  packages/web3-validator/test/unit/error.test.ts
  packages/web3-validator/test/unit/index.test.ts
  packages/web3-validator/test/unit/utils.test.ts
  packages/web3-validator/test/unit/validation/bloom.test.ts
  packages/web3-validator/test/unit/web3_validator.test.ts
Labels: 4.x

#5529 Update 1.x Dependencies
  CHANGELOG.md
  package-lock.json
  packages/web3-bzz/package-lock.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-promievent/package-lock.json
  packages/web3-core-requestmanager/package-lock.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core/package-lock.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth/package-lock.json
  packages/web3-eth2-beaconchain/package-lock.json
  packages/web3-eth2-core/package-lock.json
  packages/web3-net/package-lock.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-shh/package-lock.json
  packages/web3-utils/package-lock.json
  packages/web3/package-lock.json
Labels: 1.x, dependencies

#5481 Use subscription at `rejectIfBlockTimeout` when the provider supports subscription
  CHANGELOG.md
  fixtures/utils.ts
  packages/web3-core/CHANGELOG.md
  packages/web3-core/src/web3_config.ts
  packages/web3-core/src/web3_subscription_manager.ts
  packages/web3-core/test/unit/__snapshots__/web3_context.test.ts.snap
  packages/web3-core/test/unit/web3_config.test.ts
  packages/web3-eth-contract/src/encoding.ts
  packages/web3-eth-contract/test/integration/contract_events.test.ts
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/src/utils/reject_if_block_timeout.ts
  packages/web3-eth/src/utils/try_send_transaction.ts
  packages/web3-eth/src/utils/wait_for_transaction_receipt.ts
  packages/web3-eth/src/utils/watch_transaction_for_confirmations.ts
  packages/web3-eth/test/integration/defaults.test.ts
  packages/web3-eth/test/integration/helper.ts
  packages/web3-eth/test/integration/subscription_heads.test.ts
  packages/web3-eth/test/integration/subscription_new_pending_tx.test.ts
Labels: 4.x

#5545 Init `web3-eth-tx-utils` Base
  CHANGELOG.md
  packages/web3-eth-tx-utils/.eslintignore
  packages/web3-eth-tx-utils/.eslintrc.js
  packages/web3-eth-tx-utils/.gitignore
  packages/web3-eth-tx-utils/.npmignore
  packages/web3-eth-tx-utils/.npmrc
  packages/web3-eth-tx-utils/.prettierignore
  packages/web3-eth-tx-utils/.prettierrc.json
  packages/web3-eth-tx-utils/CHANGELOG.md
  packages/web3-eth-tx-utils/README.md
  packages/web3-eth-tx-utils/assets/logo/web3js.ai
  packages/web3-eth-tx-utils/assets/logo/web3js.jpg
  packages/web3-eth-tx-utils/assets/logo/web3js.svg
  packages/web3-eth-tx-utils/package.json
  packages/web3-eth-tx-utils/src/errors.ts
  packages/web3-eth-tx-utils/src/index.ts
  packages/web3-eth-tx-utils/src/types.ts
  packages/web3-eth-tx-utils/test/.eslintrc.js
  packages/web3-eth-tx-utils/test/config/jest.config.js
  packages/web3-eth-tx-utils/test/config/setup.js
  packages/web3-eth-tx-utils/test/integration/jest.config.js
  packages/web3-eth-tx-utils/test/integration/setup.js
  packages/web3-eth-tx-utils/test/tsconfig.json
  packages/web3-eth-tx-utils/test/unit/constructor.test.ts
  packages/web3-eth-tx-utils/test/unit/jest.config.js
  packages/web3-eth-tx-utils/tsconfig.json
  packages/web3-eth-tx-utils/tsdoc.json
Labels: 4.x

#5561 Call method doesn't work from the contract if data is provided at initiation
  packages/web3-eth-contract/src/utils.ts
  packages/web3-eth-contract/test/integration/contract_methods.test.ts
Labels: 4.x

#4877 Add `removed` property to `Log` type
  CHANGELOG.md
  packages/web3-core/types/index.d.ts
Labels: 1.x

#5571 Tiny enhancements to the Installation section at README.md files (at 4.x)
  README.md
  packages/web3-core/README.md
  packages/web3-errors/README.md
  packages/web3-eth-abi/README.md
  packages/web3-eth-accounts/README.md
  packages/web3-eth-contract/README.md
  packages/web3-eth-ens/README.md
  packages/web3-eth-iban/README.md
  packages/web3-eth-personal/README.md
  packages/web3-eth-tx-utils/README.md
  packages/web3-eth/README.md
  packages/web3-net/README.md
  packages/web3-providers-http/README.md
  packages/web3-providers-ipc/README.md
  packages/web3-providers-ws/README.md
  packages/web3-rpc-methods/README.md
  packages/web3-types/README.md
  packages/web3-utils/README.md
  packages/web3-validator/README.md
  packages/web3/README.md
  tools/web3-packagetemplate/README.md
  tools/web3-plugin-example/README.md
Labels: 4.x

#5558 Init Plugin Docs
  docs/docs/guides/web3_plugin_guide/assets/custom_rpc_method.png
  docs/docs/guides/web3_plugin_guide/assets/custom_rpc_method_with_parameters.png
  docs/docs/guides/web3_plugin_guide/index.md
  docs/docs/guides/web3_plugin_guide/plugin_authors.md
  docs/docs/guides/web3_plugin_guide/plugin_users.md
  docs/docs/guides/web3_tree_shaking_support_guide/index.md
Labels: Documentation, 4.x
