Repository web3/web3.js, pull requests merged in 2022-04, with the labels that each got.

#4901 docs(other-languages): sync link for web3.php
  README.md
Labels: 1.x, Review Needed

#4909 Add input formatting to `rpc_method_wrappers` (#4608)
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/rpc_methods.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/fixtures/rpc_methods_with_params.ts
  packages/web3-validator/src/types.ts
Labels: 4.x

#4916 Fix dead link in web3-eth.rst
  CHANGELOG.md
  docs/web3-eth.rst
Labels: Documentation, 1.x, Review Needed

#4905 Documentation - Updated the ABI link
  docs/glossary.rst
Labels: Documentation, 1.x, Review Needed

#4893 4811/investigate eslint errors in web3 eth
  .github/geth/data/geth/transactions.rlp
  .github/geth/data/geth/triecache/data.0.bin
  .github/geth/data/geth/triecache/metadata.bin
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/wait_for_transaction_receipt.ts
  packages/web3-eth/src/utils/watch_transaction_for_confirmations.ts
Labels: 4.x

#4929 Alex/4591 anonymous event logs
  packages/web3-eth-abi/src/api/logs_api.ts
  packages/web3-eth-abi/src/api/parameters_api.ts
  packages/web3-eth-abi/test/fixtures/data.ts
  packages/web3-eth-contract/src/encoding.ts
  packages/web3-eth-contract/test/fixtures/encoding.ts
  packages/web3-eth-contract/test/unit/encoding.ts
Labels: 4.x

#4918 fix: assignment to function.call
  CHANGELOG.md
  packages/web3-core-method/src/index.js
Labels: 1.x, Review Needed

#4938 assignment to function.call (#4918)
  CHANGELOG.md
  packages/web3-core-method/src/index.js
Labels: 1.x

#4884 Fix static tuple encoding (#4673)
  CHANGELOG.md
  packages/web3-eth-abi/src/index.js
  test/abi.encodeParameter.js
Labels: 1.x

#4903 Fixes calling toHexString on undefined gasPrice
  CHANGELOG.md
  packages/web3-core-method/src/index.js
Labels: 1.x, Review Needed

#4940 Fixes calling toHexString on undefined gasPrice (#4903)
  CHANGELOG.md
  packages/web3-core-method/src/index.js
Labels: 1.x

#4855 Replace deprecated String.prototype.substr()
  CHANGELOG.md
  packages/web3-core-helpers/src/formatters.js
  packages/web3-eth-iban/src/index.js
  packages/web3-utils/src/index.js
  packages/web3-utils/src/utils.js
  test/eth.ens.js
  test/utils.sha3.js
Labels: 1.x, Review Needed

#4920 Rewritten `web3-eth` tests
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/schemas.ts
  packages/web3-eth/src/utils/format_transaction.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/call.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/estimate_gas.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/call.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/estimate_gas.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_balance.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_block.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_block_transaction_count.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_block_uncle_count.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_code.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_fee_history.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_logs.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_pending_transactions.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_proof.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_storage_at.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_transaction.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_transaction_count.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_transaction_from_block.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_transaction_receipt.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_uncle.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/return_formats.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/send_signed_transaction.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/send_transaction.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/sign.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/sign_transaction.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_balance.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_block.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_block_number.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_block_transaction_count.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_block_uncle_count.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_chain_id.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_code.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_coinbase.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_fee_history.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_gas_price.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_hash_rate.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_logs.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_pending_transactions.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_proof.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_protocol_version.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_storage_at.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_transaction_count.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_transaction_from_block.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_transaction_receipt.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_uncle.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/is_mining.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/is_syncing.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_signed_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/sign.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/sign_transaction.test.ts
  packages/web3-eth/test/unit/web3_rpc_method_wrappers_no_parameters.test.ts
  packages/web3-eth/test/unit/web3_rpc_method_wrappers_with_parameters.test.ts
  packages/web3-utils/src/types.ts
Labels: 4.x

#4952 4809 add subscription support to promi events
  .github/Dockerfile
  .github/test.config.ts
  .github/workflows/build.yml
  karma.config.js
  karma.setup.js
  package.json
  packages/web3-common/src/errors.ts
  packages/web3-common/src/types.ts
  packages/web3-eth-personal/src/rpc_method_wrappers.ts
  packages/web3-eth-personal/test/unit/eth_personal.test.ts
  packages/web3-eth/package.json
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/watch_transaction_for_confirmations.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/integration/subscribe.test.ts
  packages/web3-eth/test/integration/unsubscribe.test.ts
  packages/web3-eth/test/integration/watch_transaction.test.ts
  packages/web3-providers-http/package.json
  packages/web3-providers-http/test/integration/request.test.ts
Labels: 4.x

#4987 Solve Merge Conflicts for #4939
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 1.x
