Repository web3/web3.js, pull requests merged in 2022-11, with the labels that each got.

#5560 Revert "Init `web3-eth-tx-utils` Base"
  CHANGELOG.md
  packages/web3-eth-tx-utils/.eslintignore
  packages/web3-eth-tx-utils/.eslintrc.js
  packages/web3-eth-tx-utils/.gitignore
  packages/web3-eth-tx-utils/.npmignore
  packages/web3-eth-tx-utils/.npmrc
  packages/web3-eth-tx-utils/.prettierignore
  packages/web3-eth-tx-utils/.prettierrc.json
  packages/web3-eth-tx-utils/CHANGELOG.md
  packages/web3-eth-tx-utils/README.md
  packages/web3-eth-tx-utils/assets/logo/web3js.ai
  packages/web3-eth-tx-utils/assets/logo/web3js.jpg
  packages/web3-eth-tx-utils/assets/logo/web3js.svg
  packages/web3-eth-tx-utils/package.json
  packages/web3-eth-tx-utils/src/errors.ts
  packages/web3-eth-tx-utils/src/index.ts
  packages/web3-eth-tx-utils/src/types.ts
  packages/web3-eth-tx-utils/test/.eslintrc.js
  packages/web3-eth-tx-utils/test/config/jest.config.js
  packages/web3-eth-tx-utils/test/config/setup.js
  packages/web3-eth-tx-utils/test/integration/jest.config.js
  packages/web3-eth-tx-utils/test/integration/setup.js
  packages/web3-eth-tx-utils/test/tsconfig.json
  packages/web3-eth-tx-utils/test/unit/constructor.test.ts
  packages/web3-eth-tx-utils/test/unit/jest.config.js
  packages/web3-eth-tx-utils/tsconfig.json
  packages/web3-eth-tx-utils/tsdoc.json
Labels: 4.x

#5556 eth.getBlock with hydrated = true returning empty transaction objects
  CHANGELOG.md
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/test/integration/rpc.block.test.ts
  packages/web3-utils/src/formatter.ts
Labels: 4.x

#5572 Tiny enhancements to the Installation section at README.md files (at 1.x)
  README.md
  packages/web3-bzz/README.md
  packages/web3-core-helpers/README.md
  packages/web3-core-method/README.md
  packages/web3-core-promievent/README.md
  packages/web3-core-requestmanager/README.md
  packages/web3-core-subscriptions/README.md
  packages/web3-core/README.md
  packages/web3-eth-abi/README.md
  packages/web3-eth-accounts/README.md
  packages/web3-eth-contract/README.md
  packages/web3-eth-ens/README.md
  packages/web3-eth-iban/README.md
  packages/web3-eth-personal/README.md
  packages/web3-eth/README.md
  packages/web3-net/README.md
  packages/web3-providers-http/README.md
  packages/web3-providers-ipc/README.md
  packages/web3-providers-ws/README.md
  packages/web3-shh/README.md
  packages/web3-utils/README.md
  packages/web3/README.md
  packages/web3/src/index.js
Labels: 1.x

#5574 fix: web3-validator ajv memory leak
  packages/web3-validator/src/web3_validator.ts
Labels: 4.x

#5580 Release/4.0.1 alpha.1
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-eth/src/schemas.ts
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/package.json
  packages/web3/src/version.ts
  packages/web3/test/black_box/test/web3-eth-contract/erc20.test.ts
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#5570 Add support for overloaded functions
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/contract_erc721.test.ts
  packages/web3-eth-contract/test/integration/local_account/contract_erc721.test.ts
  packages/web3-eth-contract/test/integration/local_account/contract_overloaded_methods.test.ts
Labels: 4.x

#5573 5298 - Review and clean up 4.x Documentation
  docs/docs/glossary/json_interface.md
  docs/docs/guides/web3_migration_guide/abi_migration_guide.md
  docs/docs/guides/web3_migration_guide/accounts_migration_guide.md
  docs/docs/guides/web3_migration_guide/contracts_migration_guide.md
  docs/docs/guides/web3_migration_guide/index.md
  docs/docs/guides/web3_migration_guide/net_migration_guide.md
  docs/docs/guides/web3_migration_guide/personal_migration_guide.md
  docs/docs/guides/web3_migration_guide/providers_migration_guide.md
  docs/docs/guides/web3_migration_guide/subscribe_migration_guide.md
  docs/docs/guides/web3_migration_guide/web3_eth_migration_guide.md
  docs/docs/guides/web3_migration_guide/web3_utils_migration_guide.md
  docs/docs/guides/web3_plugin_guide/index.md
  docs/docs/guides/web3_plugin_guide/plugin_authors.md
  docs/docs/guides/web3_plugin_guide/plugin_users.md
  docs/docs/guides/web3_tree_shaking_support_guide/index.md
  docs/docusaurus.config.js
  docs/src/pages/index.tsx
Labels: 4.x

#5472 Emit past contract events based on `fromBlock`
  CHANGELOG.md
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/contract_events.test.ts
Labels: 4.x

#5581 Update wallet.encrypt function signature 4.x
  CHANGELOG.md
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/src/account.ts
  packages/web3-eth-accounts/src/types.ts
  packages/web3-eth-accounts/src/wallet.ts
  packages/web3-eth-accounts/test/fixtures/account.ts
  packages/web3-eth-accounts/test/integration/wallet.test.ts
  packages/web3-eth-accounts/test/unit/wallet.test.ts
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-types/CHANGELOG.md
  packages/web3-types/src/web3_base_wallet.ts
  packages/web3/src/accounts.ts
  scripts/system_tests_utils.ts
Labels: 4.x

#5600 `soliditySha3` implementation is not compatible with 1.x
  packages/web3-types/src/utility_types.ts
  packages/web3-utils/src/converters.ts
  packages/web3-utils/src/hash.ts
  packages/web3-utils/test/fixtures/converters.ts
  packages/web3-utils/test/fixtures/hash.ts
  packages/web3-utils/test/unit/hash.test.ts
Labels: 4.x

#5550 Fix: _jsonInterfaceMethodToString export in types
  CHANGELOG.md
  packages/web3-utils/types/index.d.ts
Labels: Bug, 1.x, Review Needed

#5612 Nikos/5575/number converters have silly implementations
  packages/web3-utils/src/converters.ts
  packages/web3-utils/test/fixtures/converters.ts
  packages/web3-validator/src/utils.ts
  packages/web3-validator/test/unit/utils.test.ts
Labels: 4.x

#5614 Fix Provider Compatibility with EIP 1193
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-types/CHANGELOG.md
  packages/web3-types/src/web3_api_types.ts
  packages/web3-types/src/web3_base_provider.ts
Labels: 4.x

#5642 Pass config defaultAccount to contract options
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth/test/integration/defaults.test.ts
Labels: 4.x

#5621 Plugin Doc and Example Refactors for #5596
  docs/docs/guides/web3_plugin_guide/assets/custom_rpc_method.png
  docs/docs/guides/web3_plugin_guide/assets/custom_rpc_method_with_parameters.png
  docs/docs/guides/web3_plugin_guide/assets/web3_context_augmentation.png
  docs/docs/guides/web3_plugin_guide/index.md
  docs/docs/guides/web3_plugin_guide/plugin_authors.md
  docs/docs/guides/web3_plugin_guide/plugin_users.md
  tools/web3-plugin-example/src/contract_method_wrappers.ts
  tools/web3-plugin-example/src/custom_rpc_methods.ts
  tools/web3-plugin-example/src/reexported_web3_context.ts
  tools/web3-plugin-example/test/unit/contract_method_wrappers.test.ts
  tools/web3-plugin-example/test/unit/custom_rpc_methods.test.ts
Labels: 4.x

#5645 Use different types for jsonInterface setter and getter
  CHANGELOG.md
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-contract/test/unit/contract.test.ts
Labels: 4.x

#5666 Fix firefox error for 1.x
  .github/workflows/build.yml
Labels: 1.x
