Repository web3/web3.js, pull requests merged in 2022-01, with the labels that each got.

#4658 Replace the custom validation logic across packages with `web3-validator`
  packages/web3-common/package.json
  packages/web3-common/src/formatters.ts
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/account.ts
  packages/web3-eth/package.json
  packages/web3-eth/src/index.ts
  packages/web3-eth/src/rpc_methods.ts
  packages/web3-eth/src/validation.ts
  packages/web3-utils/package.json
  packages/web3-utils/src/converters.ts
  packages/web3-utils/src/errors.ts
  packages/web3-utils/src/hash.ts
  packages/web3-utils/src/string_manipulation.ts
  packages/web3-utils/src/validation.ts
  packages/web3-utils/test/fixtures/converters.ts
  packages/web3-utils/test/fixtures/string_manipulation.ts
  packages/web3-utils/test/fixtures/validation.ts
  packages/web3-utils/test/unit/validation.test.ts
  packages/web3-validator/src/errors.ts
  packages/web3-validator/src/formats/block.ts
  packages/web3-validator/src/formats/index.ts
  packages/web3-validator/src/keywords/eth.ts
  packages/web3-validator/src/types.ts
  packages/web3-validator/src/utils.ts
  packages/web3-validator/src/validation/eth.ts
  packages/web3-validator/test/unit/validation/address.test.ts
  packages/web3-validator/test/unit/validation/block.test.ts
  packages/web3-validator/test/unit/validation/bloom.test.ts
  packages/web3-validator/test/unit/validation/boolean.test.ts
  packages/web3-validator/test/unit/validation/bytes.test.ts
  packages/web3-validator/test/unit/validation/eth.test.ts
  packages/web3-validator/test/unit/validation/fitler.test.ts
  packages/web3-validator/test/unit/validation/numbers.test.ts
  packages/web3-validator/test/unit/validation/string.test.ts
  packages/web3-validator/test/unit/validation/topic.test.ts
  packages/web3-validator/test/unit/web3_validator.test.ts
Labels: 4.x

#4613 Update helpers.js
  CHANGELOG.md
  packages/web3-core-requestmanager/src/givenProvider.js
  packages/web3-eth-accounts/src/index.js
  packages/web3-providers-ws/src/helpers.js
Labels: Needs Clarification, 1.x, Review Needed, Changes Requested

#4584 add: custom transaction polling interval
  CHANGELOG.md
  docs/web3-eth-contract.rst
  packages/web3-core-method/src/index.js
  packages/web3-eth-contract/src/index.js
Labels: 1.x, Review Needed, Changes Requested

#4668 Init `web3-eth-tx`
  packages/web3-eth-tx/.eslintignore
  packages/web3-eth-tx/.eslintrc.js
  packages/web3-eth-tx/.gitignore
  packages/web3-eth-tx/.npmignore
  packages/web3-eth-tx/.npmrc
  packages/web3-eth-tx/.prettierignore
  packages/web3-eth-tx/.prettierrc.json
  packages/web3-eth-tx/CHANGELOG.md
  packages/web3-eth-tx/README.md
  packages/web3-eth-tx/assets/logo/web3js.ai
  packages/web3-eth-tx/assets/logo/web3js.jpg
  packages/web3-eth-tx/assets/logo/web3js.svg
  packages/web3-eth-tx/package.json
  packages/web3-eth-tx/src/errors.ts
  packages/web3-eth-tx/src/index.ts
  packages/web3-eth-tx/src/types.ts
  packages/web3-eth-tx/test/.eslintrc.js
  packages/web3-eth-tx/test/config/jest.config.js
  packages/web3-eth-tx/test/config/setup.js
  packages/web3-eth-tx/test/integration/jest.config.js
  packages/web3-eth-tx/test/integration/setup.js
  packages/web3-eth-tx/test/tsconfig.json
  packages/web3-eth-tx/test/unit/constructor.test.ts
  packages/web3-eth-tx/test/unit/jest.config.js
  packages/web3-eth-tx/tsconfig.json
Labels: 4.x

#4669 ENS package
  packages/web3-eth-ens/.eslintignore
  packages/web3-eth-ens/.eslintrc.js
  packages/web3-eth-ens/.gitignore
  packages/web3-eth-ens/.npmignore
  packages/web3-eth-ens/.npmrc
  packages/web3-eth-ens/.prettierignore
  packages/web3-eth-ens/.prettierrc.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/README.md
  packages/web3-eth-ens/assets/logo/web3js.ai
  packages/web3-eth-ens/assets/logo/web3js.jpg
  packages/web3-eth-ens/assets/logo/web3js.svg
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/src/index.ts
  packages/web3-eth-ens/test/.eslintrc.js
  packages/web3-eth-ens/test/config/jest.config.js
  packages/web3-eth-ens/test/config/setup.js
  packages/web3-eth-ens/test/integration/jest.config.js
  packages/web3-eth-ens/test/integration/setup.js
  packages/web3-eth-ens/test/tsconfig.json
  packages/web3-eth-ens/test/unit/constructor.test.ts
  packages/web3-eth-ens/test/unit/jest.config.js
  packages/web3-eth-ens/tsconfig.json
Labels: 4.x

#4672 add: custom transaction polling interval (#4584)
  CHANGELOG.md
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  packages/web3-core-method/src/index.js
  packages/web3-eth-contract/src/index.js
  packages/web3-eth/src/index.js
  test/contract.js
  test/eth.transactionPollingInterval.js
Labels: 1.x

#4662 Fix typos in web3-utils.rst
  CHANGELOG.md
  docs/web3-utils.rst
Labels: Documentation, 1.x, Review Needed

#4691 Fix typos in REVIEW.md and TESTING.md
  CHANGELOG.md
  REVIEW.md
  TESTING.md
Labels: Documentation, 1.x

#4710 Troubleshoot is one word
  README.md
Labels: Documentation, 1.x

#4714 ENS ABI contract ReverseRegistrar and TestRegistrar
  packages/web3-eth-ens/src/ABI/Registry.ts
  packages/web3-eth-ens/src/ABI/ReverseRegistrar.ts
  packages/web3-eth-ens/src/ABI/TestRegistrar.ts
Labels: 4.x

#4715 init iban package
  packages/web3-eth-iban/.eslintignore
  packages/web3-eth-iban/.eslintrc.js
  packages/web3-eth-iban/.gitignore
  packages/web3-eth-iban/.npmignore
  packages/web3-eth-iban/.npmrc
  packages/web3-eth-iban/.prettierignore
  packages/web3-eth-iban/.prettierrc.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/README.md
  packages/web3-eth-iban/assets/logo/web3js.ai
  packages/web3-eth-iban/assets/logo/web3js.jpg
  packages/web3-eth-iban/assets/logo/web3js.svg
  packages/web3-eth-iban/logo/web3js.ai
  packages/web3-eth-iban/logo/web3js.jpg
  packages/web3-eth-iban/logo/web3js.svg
  packages/web3-eth-iban/package.json
  packages/web3-eth-iban/src/index.ts
  packages/web3-eth-iban/test/.eslintrc.js
  packages/web3-eth-iban/test/config/jest.config.js
  packages/web3-eth-iban/test/config/setup.js
  packages/web3-eth-iban/test/integration/jest.config.js
  packages/web3-eth-iban/test/integration/setup.js
  packages/web3-eth-iban/test/tsconfig.json
  packages/web3-eth-iban/test/unit/constructor.test.ts
  packages/web3-eth-iban/test/unit/jest.config.js
  packages/web3-eth-iban/tsconfig.json
Labels: 4.x

#4611 Add example import for package level types
  README.md
Labels: 1.x, Review Needed

#4725 Update CHANGELOG for 4611
  CHANGELOG.md
Labels: 1.x

#4719 updating libs
  CHANGELOG.md
  package-lock.json
Labels: 1.x

#4730 '0x' strings returned by contract are incorrectly interpreted as nulls
  CHANGELOG.md
  packages/web3-eth-abi/src/index.js
  packages/web3-eth-abi/types/tests/abi-coder-test.ts
  test/abi.decodeParameter.js
Labels: 1.x

#4678 Implement `Contract` public interfaces
  packages/web3-common/src/constants.ts
  packages/web3-common/src/eth_execution_api.ts
  packages/web3-common/src/json_rpc.ts
  packages/web3-common/src/types.ts
  packages/web3-common/src/web3_base_provider.ts
  packages/web3-core/src/web3_context.ts
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-core/src/web3_subscription_manager.ts
  packages/web3-core/src/web3_subscriptions.ts
  packages/web3-core/test/unit/fixtures/example_subscription.ts
  packages/web3-core/test/unit/web3_context.test.ts
  packages/web3-core/test/unit/web3_request_manager.test.ts
  packages/web3-core/test/unit/web3_subscription_manager.test.ts
  packages/web3-eth-abi/src/types.ts
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/encoding.ts
  packages/web3-eth-contract/src/errors.ts
  packages/web3-eth-contract/src/log_subscription.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-contract/src/utils.ts
  packages/web3-eth-contract/test/fixtures/erc20.ts
  packages/web3-eth-contract/test/fixtures/erc721.ts
  packages/web3-eth-contract/test/unit/contract_typing.test.ts
  packages/web3-providers-ipc/src/index.ts
  packages/web3-utils/src/index.ts
  packages/web3-utils/src/objects.ts
  packages/web3-utils/src/types.ts
  packages/web3-utils/test/fixtures/objects.ts
  packages/web3-utils/test/unit/objects.test.ts
  packages/web3-validator/src/web3_validator.ts
Labels: 4.x

#4742 input address formatter
  packages/web3-common/package.json
  packages/web3-common/src/constants.ts
  packages/web3-common/src/errors.ts
  packages/web3-common/src/formatters.ts
  packages/web3-common/test/unit/formatters.test.ts
  packages/web3-eth-abi/src/types.ts
  packages/web3-eth-iban/package.json
  packages/web3-eth-iban/src/index.ts
  packages/web3-eth-iban/test/fixtures/iban.ts
Labels: 4.x
