Repository web3/web3.js, pull requests merged in 2022-03, with the labels that each got.

#4798 Revert "Updating library "
  CHANGELOG.md
  package-lock.json
Labels: 1.x

#4792 Wyatt/4.x/4789 transaction rpc methods
  packages/web3-common/src/constants.ts
  packages/web3-common/src/eth_execution_api.ts
  packages/web3-core/src/types.ts
  packages/web3-core/src/web3_config.ts
  packages/web3-core/src/web3_context.ts
  packages/web3-core/src/web3_subscriptions.ts
  packages/web3-core/test/unit/web3_config.test.ts
  packages/web3-eth/src/errors.ts
  packages/web3-eth/src/index.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/rpc_methods.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/validation.ts
  packages/web3-eth/test/unit/web3_rpc_method_wrappers_with_parameters.test.ts
Labels: 4.x

#4790 web3 net
  CHANGELOG.md
  packages/web3-net/.eslintignore
  packages/web3-net/.eslintrc.js
  packages/web3-net/.gitignore
  packages/web3-net/.npmignore
  packages/web3-net/.npmrc
  packages/web3-net/.prettierignore
  packages/web3-net/.prettierrc.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/README.md
  packages/web3-net/assets/logo/web3js.ai
  packages/web3-net/assets/logo/web3js.jpg
  packages/web3-net/assets/logo/web3js.svg
  packages/web3-net/package.json
  packages/web3-net/src/index.ts
  packages/web3-net/src/rpc_method_wrappers.ts
  packages/web3-net/src/rpc_methods.ts
  packages/web3-net/src/web3_net_api.ts
  packages/web3-net/test/.eslintrc.js
  packages/web3-net/test/config/jest.config.js
  packages/web3-net/test/config/setup.js
  packages/web3-net/test/fixtures/rpc_method_wrappers.ts
  packages/web3-net/test/fixtures/web3_net_methods.ts
  packages/web3-net/test/integration/jest.config.js
  packages/web3-net/test/integration/setup.js
  packages/web3-net/test/tsconfig.json
  packages/web3-net/test/unit/jest.config.js
  packages/web3-net/test/unit/rpc_method_wrappers.test.ts
  packages/web3-net/test/unit/rpc_methods.test.ts
  packages/web3-net/test/unit/web3_net_methods.test.ts
  packages/web3-net/tsconfig.json
  yarn.lock
Labels: 4.x

#4781 Web3 Eth Personal
  packages/web3-eth-personal/.eslintignore
  packages/web3-eth-personal/.eslintrc.js
  packages/web3-eth-personal/.gitignore
  packages/web3-eth-personal/.npmignore
  packages/web3-eth-personal/.npmrc
  packages/web3-eth-personal/.prettierignore
  packages/web3-eth-personal/.prettierrc.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/README.md
  packages/web3-eth-personal/assets/logo/web3js.ai
  packages/web3-eth-personal/assets/logo/web3js.jpg
  packages/web3-eth-personal/assets/logo/web3js.svg
  packages/web3-eth-personal/package.json
  packages/web3-eth-personal/src/eth_personal_api.ts
  packages/web3-eth-personal/src/index.ts
  packages/web3-eth-personal/src/rcp_methods.ts
  packages/web3-eth-personal/src/rpc_method_wrappers.ts
  packages/web3-eth-personal/src/types.ts
  packages/web3-eth-personal/test/.eslintrc.js
  packages/web3-eth-personal/test/config/jest.config.js
  packages/web3-eth-personal/test/config/setup.js
  packages/web3-eth-personal/test/integration/jest.config.js
  packages/web3-eth-personal/test/integration/setup.js
  packages/web3-eth-personal/test/tsconfig.json
  packages/web3-eth-personal/test/unit/eth_personal.test.ts
  packages/web3-eth-personal/test/unit/jest.config.js
  packages/web3-eth-personal/tsconfig.json
  packages/web3-eth/src/format_transaction.ts
  packages/web3-eth/src/index.ts
  packages/web3-eth/src/web3_eth.ts
Labels: 4.x

#4806 Update `web3-eth-contract` to use `web3-eth` methods
  CHANGELOG.md
  packages/web3-common/src/web3_event_emitter.ts
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-contract/src/utils.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  yarn.lock
Labels: 4.x

#4788 Create the Web3 class
  CHANGELOG.md
  packages/web3-common/test/unit/promi_event.test.ts
  packages/web3-core/src/types.ts
  packages/web3-core/src/utils.ts
  packages/web3-core/src/web3_config.ts
  packages/web3-core/src/web3_context.ts
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-core/test/unit/__snapshots__/web3_context.test.ts.snap
  packages/web3-core/test/unit/web3_context.test.ts
  packages/web3-eth-accounts/src/index.ts
  packages/web3-eth-accounts/src/wallet.ts
  packages/web3-eth-accounts/test/unit/__snapshots__/wallet.test.ts.snap
  packages/web3-eth-accounts/test/unit/wallet.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/index.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-contract/src/utils.ts
  packages/web3-eth-contract/tsconfig.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/src/ens.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/test/unit/populate_transaction.test.ts
  packages/web3/package.json
  packages/web3/src/errors.ts
  packages/web3/src/index.ts
  packages/web3/tsconfig.json
  templates/tsconfig.json.tmpl
Labels: 4.x

#4827 ETH Transaction Utils Refactors
  packages/web3-core/src/web3_context.ts
  packages/web3-core/test/unit/web3_context.test.ts
  packages/web3-eth/src/eth_tx.ts
  packages/web3-eth/src/index.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/detect_transaction_type.ts
  packages/web3-eth/src/utils/format_transaction.ts
  packages/web3-eth/src/utils/prepare_transaction_for_signing.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/src/validation.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  packages/web3-eth/test/unit/detect_transction_type.test.ts
  packages/web3-eth/test/unit/format_transaction.test.ts
  packages/web3-eth/test/unit/prepare_transaction_for_signing.test.ts
  packages/web3-eth/test/unit/validate_transaction_for_signing.test.ts
Labels: 4.x

#4823 ETH Tx Utilities TODOs [5/5] - Refactor validation to use `web3-validator`
  packages/web3-eth/src/eth_tx.ts
  packages/web3-eth/src/validation.ts
Labels: 4.x

#4824 ETH Tx Utilities TODOs [4/5] - Function overrides
  packages/web3-core/src/types.ts
  packages/web3-core/src/web3_config.ts
  packages/web3-core/src/web3_context.ts
  packages/web3-core/test/unit/__snapshots__/web3_context.test.ts.snap
  packages/web3-core/test/unit/web3_context.test.ts
  packages/web3-eth/src/eth_tx.ts
  packages/web3-eth/src/index.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/utils/detect_transaction_type.ts
  packages/web3-eth/src/utils/format_transaction.ts
  packages/web3-eth/src/utils/index.ts
  packages/web3-eth/src/utils/prepare_transaction_for_signing.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/src/validation.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  packages/web3-eth/test/unit/detect_transction_type.test.ts
  packages/web3-eth/test/unit/format_transaction.test.ts
  packages/web3-eth/test/unit/prepare_transaction_for_signing.test.ts
  packages/web3-eth/test/unit/validate_transaction_for_signing.test.ts
Labels: 4.x

#4834 Contract all events and past events support
  packages/web3-common/src/formatters.ts
  packages/web3-eth-contract/src/constants.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-utils/src/types.ts
Labels: 4.x

#4825 Now we can remove the close event
  packages/web3-core-requestmanager/src/index.js
Labels: Needs Clarification, Review Needed

#4837 `defaultTransactionBuilder` Refactors and Add Gas Pricing to `sendTransaction`
  packages/web3-core/src/web3_config.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/get_transaction_gas_pricing.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
Labels: 4.x

#4761 Fix jsonrpc payload and response types (#4743)
  CHANGELOG.md
  packages/web3-core-helpers/types/index.d.ts
Labels: 1.x

#4860 libs update
  CHANGELOG.md
  package-lock.json
Labels: 1.x, Review Needed

#4865 Nonce must be 8 bytes by Ethereum spec (#4559)
  test/formatters.outputBlockFormatter.js
Labels: 1.x

#4839 Now we can remove the close event (#4825)
  CHANGELOG.md
  packages/web3-core-requestmanager/src/index.js
Labels: 1.x

#4842 `defaultTransactionBuilder` (`chainId` and `networkId`) - #4800
  packages/web3-eth/package.json
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  packages/web3-eth/test/unit/prepare_transaction_for_signing.test.ts
  packages/web3-net/src/index.ts
  packages/web3-net/src/web3_net.ts
  packages/web3-utils/src/types.ts
Labels: 4.x

#4867 Fix `something_else` issue template
  .github/ISSUE_TEMPLATE/something_else.yml
Labels: 1.x, 4.x

#4808 Replace old xhr2-cookies with xhr2-cookies-patched deps for 1.x, fix User-Agent header problem
  CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-http/src/index.js
  test/httpprovider.js
Labels: Discussion, 1.x, Do Not Merge

#4844 4555/encode decode parameters
  CHANGELOG.md
  packages/web3-eth-abi/src/api/logs_api.ts
  packages/web3-eth-abi/src/api/parameters_api.ts
  packages/web3-eth-abi/test/fixtures/data.ts
  packages/web3-eth-abi/test/unit/api/parameters_api.test.ts
  packages/web3-eth-contract/src/encoding.ts
Labels: 4.x

#4833 Make disconnect params optional in types
  CHANGELOG.md
  CONTRIBUTIONS.md
  packages/web3-core-helpers/types/index.d.ts
Labels: 1.x, Review Needed

#4673 Fix static tuple encoding
  packages/web3-eth-abi/src/index.js
  test/abi.encodeParameter.js
Labels: 1.x, Review Needed

#4883 Make disconnect params optional in types (#4833)
  CHANGELOG.md
  CONTRIBUTIONS.md
  packages/web3-core-helpers/types/index.d.ts
Labels: 1.x

#4847 errorhandling 4583
  packages/web3-eth/src/errors.ts
  packages/web3-eth/test/fixtures/errors.ts
  packages/web3-eth/test/unit/errors.test.ts
  packages/web3-utils/src/errors.ts
  packages/web3-utils/src/string_manipulation.ts
  packages/web3-utils/test/fixtures/errors.ts
  packages/web3-utils/test/fixtures/string_manipulation.ts
  packages/web3-utils/test/unit/converters.test.ts
  packages/web3-utils/test/unit/errors.test.ts
Labels: 4.x

#4864 integration test: request
  .github/Dockerfile
  .github/workflows/build.yml
  karma.config.js
  package.json
  packages/web3-common/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth-tx/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-http/test/fixtures/config.ts
  packages/web3-providers-http/test/integration/request.test.ts
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-utils/package.json
  packages/web3-validator/package.json
  packages/web3/package.json
  tools/web3-packagetemplate/package.json
  yarn.lock
Labels: 4.x

#4885 4774/update repo docs 4.x
  CONTRIBUTIONS.md
  README.md
  REVIEW.md
  SECURITY.md
  packages/web3-core/README.md
  packages/web3-eth-abi/README.md
  packages/web3-eth-accounts/README.md
  packages/web3-eth/README.md
  packages/web3-net/README.md
  packages/web3-providers-ipc/README.md
  packages/web3-providers-ws/README.md
  packages/web3-validator/README.md
Labels: 4.x

#4870 4784/log filter topic type and digest
  packages/web3-common/src/eth_execution_api.ts
  packages/web3-eth/src/rpc_methods.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/unit/rpc_methods_with_parameters.test.ts
Labels: 4.x

#4882 4556 - improve formatparameter
  packages/web3-eth-abi/src/api/parameters_api.ts
  packages/web3-eth-abi/src/utils.ts
  packages/web3-eth-abi/test/fixtures/data.ts
  packages/web3-eth-abi/test/unit/api/parameters_api.test.ts
Labels: 4.x

#4859 Refactor formatters to JSON schemas and TypeScript band-aid solution
  CHANGELOG.md
  packages/web3-common/package.json
  packages/web3-common/src/formatter.ts
  packages/web3-common/src/index.ts
  packages/web3-common/test/unit/formatter.test.ts
  packages/web3-core/src/web3_config.ts
  packages/web3-core/test/unit/__snapshots__/web3_context.test.ts.snap
  packages/web3-core/test/unit/web3_config.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-ens/src/ens.ts
  packages/web3-eth-personal/src/rpc_method_wrappers.ts
  packages/web3-eth-personal/test/unit/eth_personal.test.ts
  packages/web3-eth/src/convertible_properties.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/schemas.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/utils/detect_transaction_type.ts
  packages/web3-eth/src/utils/format_transaction.ts
  packages/web3-eth/src/utils/get_transaction_gas_pricing.ts
  packages/web3-eth/src/utils/prepare_transaction_for_signing.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/src/validation.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/fixtures/detect_transaction_type.ts
  packages/web3-eth/test/fixtures/format_transaction.ts
  packages/web3-eth/test/fixtures/prepare_transaction_for_signing.ts
  packages/web3-eth/test/fixtures/rpc_methods_wrappers.ts
  packages/web3-eth/test/fixtures/validate_transaction_for_signing.ts
  packages/web3-eth/test/fixtures/web3_eth_methods_with_parameters.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  packages/web3-eth/test/unit/format_transaction.test.ts
  packages/web3-eth/test/unit/web3_eth_methods_with_parameters.test-disable.ts
  packages/web3-eth/test/unit/web3_rpc_method_wrappers_with_parameters.test-disable.ts
  packages/web3-net/src/rpc_method_wrappers.ts
  packages/web3-net/src/web3_net.ts
  packages/web3-net/test/fixtures/rpc_method_wrappers.ts
  packages/web3-net/test/fixtures/web3_net_methods.ts
  packages/web3-net/test/unit/rpc_method_wrappers.test.ts
  packages/web3-net/test/unit/web3_net_methods.test.ts
  packages/web3-utils/src/converters.ts
  packages/web3-utils/src/errors.ts
  packages/web3-utils/src/types.ts
  packages/web3-utils/test/fixtures/converters.ts
  packages/web3-utils/test/unit/converters.test.ts
  packages/web3-validator/src/types.ts
  packages/web3-validator/src/utils.ts
  packages/web3-validator/src/validation/index.ts
  packages/web3-validator/src/validation/object.ts
Labels: 4.x

#4875 `web3-eth` `sendTransaction` and `sendSignedTransaction` `PromiEvent` tests #4810
  packages/web3-common/src/eth_execution_api.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-ens/src/ens.ts
  packages/web3-eth/src/errors.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/schemas.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/utils/wait_for_transaction_receipt.ts
  packages/web3-eth/src/utils/watch_transaction_for_confirmations.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/send_signed_transaction.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/send_transaction.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_signed_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_transaction.test.ts
Labels: 4.x
