Repository web3/web3.js, pull requests merged in 2022-05, with the labels that each got.

#4911 Fix types: returnTransactionObjects param value affects resolve type
  CHANGELOG.md
  packages/web3-eth/types/index.d.ts
Labels: 1.x, Review Needed

#5000 Fix types: returnTransactionObjects param value affects resolve type …
  CHANGELOG.md
  packages/web3-eth/types/index.d.ts
Labels: 1.x

#4822 Exposing web3.eth.Contract.setProvider() as per public documentation
  packages/web3-eth-contract/types/index.d.ts
Labels: 1.x, Review Needed

#5001 Exposing web3.eth.Contract.setProvider() as per public documentation
  CHANGELOG.md
  packages/web3-eth-contract/types/index.d.ts
Labels: 1.x

#4949 :building_construction: Improve system tests structure
  .github/test.config.ts
  .github/workflows/build.yml
  karma.config.js
  karma.setup.js
  package.json
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-eth-contract/.eslintignore
  packages/web3-eth-contract/cypress
  packages/web3-eth-contract/cypress.json
  packages/web3-eth-contract/test/fixtures/system_test_utils.ts
  packages/web3-eth-contract/test/integration/conract_deploy.test.ts
  packages/web3-eth-contract/test/integration/contract_clone.test.ts
  packages/web3-eth-contract/test/integration/contract_events.test.ts
  packages/web3-eth-contract/test/integration/contract_methods.test.ts
  packages/web3-eth-iban/src/index.ts
  packages/web3-eth/cypress
  packages/web3-eth/cypress.json
  packages/web3-eth/package.json
  packages/web3-eth/test/fixtures/system_test_utils.ts
  packages/web3-eth/test/integration/subscribe.test.ts
  packages/web3-eth/test/integration/unsubscribe.test.ts
  packages/web3-eth/test/integration/watch_transaction.test.ts
  packages/web3-providers-http/cypress
  packages/web3-providers-http/cypress.json
  packages/web3-providers-http/package.json
  packages/web3-providers-http/test/fixtures/system_test_utils.ts
  packages/web3-providers-http/test/integration/request.test.ts
  packages/web3-utils/src/string_manipulation.ts
  scripts/env.sh
  scripts/ganache.sh
  scripts/geth.sh
  scripts/system_tests_utils.ts
  scripts/test-runner.sh
  templates/.eslintignore.tmpl
  templates/cypress.json
  templates/cypress/plugins/index.js
  templates/cypress/support/commands.js
  templates/cypress/support/index.js
  templates/cypress/webpack.config.js
  yarn.lock
Labels: 4.x

#4990 4852 web3 subscribe tests
  packages/web3-common/package.json
  packages/web3-core/package.json
  packages/web3-errors/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/src/index.ts
  packages/web3-eth-contract/test/integration/conract_deploy.test.ts
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/src/web3_subscriptions.ts
  packages/web3-eth/test/integration/helper.ts
  packages/web3-eth/test/integration/subscribe.test.ts
  packages/web3-eth/test/integration/subscription_heads.test.ts
  packages/web3-eth/test/integration/subscription_logs.test.ts
  packages/web3-eth/test/integration/subscription_new_pending_tx.test.ts
  packages/web3-eth/test/integration/unsubscribe.test.ts
  packages/web3-eth/test/integration/watch_transaction.test.ts
  packages/web3-eth/test/shared_fixtures
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-utils/package.json
  packages/web3-validator/package.json
  packages/web3/package.json
  scripts/geth.sh
  templates/cypress/support/index.js
Labels: 4.x

#5010 Enable the e2e tests for web3-eth-contract
  .github/workflows/build.yml
  fixtures/sources/DeployRevert.sol
  fixtures/sources/DeployRevert.ts
  fixtures/utils.ts
  packages/web3-common/src/deferred_promise.ts
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/errors/connection_errors.ts
  packages/web3-errors/src/web3_error_base.ts
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/conract_deploy.test.ts
  packages/web3-eth/src/index.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-providers-ws/src/index.ts
  packages/web3-providers-ws/test/unit/__mocks__/isomorphic-ws.ts
  packages/web3-providers-ws/test/unit/web_socket_provider.test.ts
  templates/cypress/support/index.js
Labels: 4.x

#5023 Add `prettier-plugin-solidity` dev dependency v2
  fixtures/contracts/Basic.sol
  fixtures/contracts/DeployRevert.sol
  fixtures/contracts/Greeter.sol
  package.json
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/send_transaction.ts
  yarn.lock
Labels: 4.x

#4984 4853 - web3 Personal- 4.0.0 Alpha.0 System Test
  packages/web3-eth-contract/test/integration/contract_deploy.test.ts
  packages/web3-eth-personal/package.json
  packages/web3-eth-personal/src/eth_personal_api.ts
  packages/web3-eth-personal/test/config/personal.config.ts
  packages/web3-eth-personal/test/fixtures/system_test_utils.ts
  packages/web3-eth-personal/test/integration/personal.test.ts
  scripts/ganache.sh
Labels: 4.x

#5019 Replace substr with slice in ts files
  package.json
  packages/web3-common/src/formatters.ts
  packages/web3-common/test/unit/formatters.test.ts
  packages/web3-utils/test/unit/random.test.ts
  packages/web3-validator/src/utils.ts
  packages/web3-validator/src/validation/address.ts
  packages/web3-validator/src/validation/bloom.ts
  tools/eslint-config-web3-base/package.json
  tools/eslint-config-web3-base/ts.js
  yarn.lock
Labels: 4.x

#5051 The status field for the receipt info should be formatted as number when use FMT_NUMBER.STR
  packages/web3-common/test/unit/formatter.test.ts
  packages/web3-eth/test/fixtures/format_transaction.ts
  packages/web3-eth/test/fixtures/rpc_methods_with_params.ts
  packages/web3-eth/test/fixtures/rpc_methods_wrappers.ts
  packages/web3-eth/test/unit/format_transaction.test.ts
  packages/web3-utils/src/objects.ts
  packages/web3-utils/test/unit/objects.test.ts
  packages/web3-validator/src/validation/object.ts
Labels: 4.x

#5008 4897/websocket provider 4x system tests
  packages/web3-eth/test/integration/jest.config.js
  packages/web3-providers-ws/package.json
  packages/web3-providers-ws/src/index.ts
  packages/web3-providers-ws/src/types.ts
  packages/web3-providers-ws/test/fixtures/helpers.ts
  packages/web3-providers-ws/test/fixtures/system_test_utils.ts
  packages/web3-providers-ws/test/integration/basic_auth.test.ts
  packages/web3-providers-ws/test/integration/jest.config.js
  packages/web3-providers-ws/test/integration/web_socket_provider_integration.test.ts
  scripts/test-runner.sh
  templates/jest.config.js.tmpl
  yarn.lock
Labels: 4.x

#5070 4799 - failing test sign transactions
  packages/web3-eth/test/fixtures/prepare_transaction_for_signing.ts
Labels: 4.x
