Repository web3/web3.js, pull requests merged in 2022-06, with the labels that each got.

#5086 Fix odd length hex string conversion
  packages/web3-utils/src/converters.ts
  packages/web3-utils/test/fixtures/converters.ts
  packages/web3-utils/test/unit/converters.test.ts
Labels: 4.x

#5074 5072 - updating bn 1.x
  CHANGELOG.md
  package-lock.json
  package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3-utils/src/utils.js
  test/eth.accounts.signTransaction.js
  test/utils.BN.js
Labels: 1.x

#5056 `web3-eth` Integration Tests (#4880)
  packages/web3-common/src/eth_execution_api.ts
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/web3_error_base.ts
  packages/web3-eth/package.json
  packages/web3-eth/src/errors.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/schemas.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/integration/web3_eth/call.test.ts
  packages/web3-eth/test/integration/web3_eth/estimate_gas.test.ts
  packages/web3-eth/test/integration/web3_eth/send_signed_transaction.test.ts
  packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts
  packages/web3-eth/test/integration/web3_eth/sign.test.ts
  packages/web3-eth/test/integration/web3_eth/sign_transaction.test.ts
  packages/web3-eth/test/integration/web3_eth/submit_work.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/send_signed_transaction.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_signed_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/sign_transaction.test.ts
  scripts/system_tests_utils.ts
Labels: 4.x

#5034 Change parameter type and format transaction to default type
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/test/integration/defaults.test.ts
Labels: 4.x

#5134 4970/web3 documentation
  packages/web3-providers-http/src/index.ts
  packages/web3-providers-ws/src/index.ts
  packages/web3/src/index.ts
Labels: 4.x

#5137 Change default return type for integer values to BigInt
  packages/web3-common/src/formatter.ts
  packages/web3-common/src/formatters.ts
  packages/web3-common/src/web3_base_provider.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/contract_methods.test.ts
  packages/web3-eth-ens/src/ens.ts
  packages/web3-eth-personal/src/rpc_method_wrappers.ts
  packages/web3-eth-personal/test/unit/eth_personal.test.ts
  packages/web3-eth/src/constants.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/utils/detect_transaction_type.ts
  packages/web3-eth/src/utils/get_transaction_gas_pricing.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/fixtures/detect_transaction_type.ts
  packages/web3-eth/test/fixtures/format_transaction.ts
  packages/web3-eth/test/integration/defaults.test.ts
  packages/web3-eth/test/integration/helper.ts
  packages/web3-eth/test/integration/rpc.test.ts
  packages/web3-eth/test/integration/subscription_logs.test.ts
  packages/web3-eth/test/integration/watch_transaction.test.ts
  packages/web3-eth/test/integration/web3_eth/estimate_gas.test.ts
  packages/web3-eth/test/integration/web3_eth/send_signed_transaction.test.ts
  packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/call.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/estimate_gas.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_balance.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_block.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_block_transaction_count.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_block_uncle_count.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_code.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_fee_history.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_proof.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_storage_at.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_transaction_count.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_transaction_from_block.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_uncle.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/sign_transaction.test.ts
  packages/web3-validator/src/validation/block.ts
  packages/web3-validator/src/validation/numbers.ts
  packages/web3-validator/test/fixtures/validation.ts
  packages/web3-validator/test/unit/validation/block.test.ts
  packages/web3/test/integration/main_web3.test.ts
  yarn.lock
Labels: 4.x

#5139 :sparkles: Make the web3 constructor parameters optional
  packages/web3-core/src/utils.ts
  packages/web3-core/src/web3_context.ts
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-core/src/web3_subscription_manager.ts
  packages/web3-core/test/unit/__snapshots__/web3_context.test.ts.snap
  packages/web3-core/test/unit/web3_request_manager.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-validator/src/validation/numbers.ts
  packages/web3/src/web3.ts
  packages/web3/test/integration/main_web3.test.ts
Labels: 4.x

#5140 :art: Update the webpack to build per package
  .github/workflows/build.yml
  package.json
  packages/web3-validator/.eslintignore
  packages/web3-validator/package.json
  packages/web3-validator/webpack.config.js
  packages/web3/.eslintignore
  packages/web3/package.json
  packages/web3/webpack.config.js
  webpack.base.config.js
  webpackprod.config.js
Labels: 4.x

#5145 Fix typo in web3-eth-accounts
  docs/web3-eth-accounts.rst
Labels: Documentation, 1.x, Future Release

#5142 Typo found
  docs/web3-eth-accounts.rst
Labels: 1.x, Future Release

#5116 Fix typo
  docs/web3-eth.rst
Labels: 1.x, Future Release

#5143 5105/web3 migration guide
  docs/docs/guides/web3_migration_guide.md
Labels: 4.x

#5115 Updates on `README.md` Format
  CHANGELOG.md
  README.md
Labels: 1.x, Future Release

#5162 Contract API Documentation
  docs/docs/glossary/json_interface.md
  docs/docs/guides/setting_provider.md
  docs/docusaurus.config.js
  docs/sidebars.js
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/encoding.ts
  packages/web3-eth-contract/src/index.ts
  packages/web3-eth-contract/src/log_subscription.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3/src/index.ts
  packages/web3/src/types.ts
  packages/web3/src/web3.ts
  tools/eslint-config-web3-base/ts.js
  yarn.lock
Labels: 4.x

#5175 Fix bugs for the wallet and PromiEvent
  packages/web3-common/src/web3_base_wallet.ts
  packages/web3-common/src/web3_promi_event.ts
  packages/web3-common/test/unit/web3_promi_event.test.ts
  packages/web3-eth-accounts/src/wallet.ts
  packages/web3-eth-accounts/test/unit/wallet.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/contract_defaults.test.ts
  packages/web3-eth-contract/test/integration/contract_deploy.test.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/test/integration/defaults.test.ts
  packages/web3-eth/test/integration/helper.ts
  packages/web3-eth/test/integration/watch_transaction.test.ts
  packages/web3-eth/test/integration/web3_eth/send_signed_transaction.test.ts
  packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_signed_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_transaction.test.ts
Labels: 4.x

#5178 Update `got` dependency for `web3-bzz` package
  CHANGELOG.md
  package-lock.json
  packages/web3-bzz/package.json
Labels: 1.x, Future Release

#5164 4969/account wallet docs
  packages/web3-common/src/web3_base_wallet.ts
  packages/web3-eth-accounts/src/account.ts
  packages/web3-eth-accounts/src/index.ts
  packages/web3-eth-accounts/src/wallet.ts
  packages/web3/src/types.ts
  packages/web3/src/web3.ts
Labels: 4.x
