Repository web3/web3.js, pull requests merged in 2022-08, with the labels that each got.

#5300 Fix minor typo in README
  README.md
Labels: 4.x

#5305 Web3RequestManager is not compatible with the Ganache provider
  packages/web3-core/src/utils.ts
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-core/test/unit/web3_request_manager.test.ts
  packages/web3-types/src/web3_base_provider.ts
Labels: 4.x

#5296 adding build script for docs
  .github/workflows/build.yml
  docs/docusaurus.config.js
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  package.json
Labels: 4.x

#5301 Adding a wrapper for keccak256 to allow hashing `string` and `bigint`
  packages/web3-utils/src/hash.ts
  packages/web3-utils/test/fixtures/hash.ts
  packages/web3-utils/test/unit/hash.test.ts
Labels: 4.x

#5306 4x alpha release process
  RELEASE.md
  package.json
Labels: 4.x

#5322 Tuple value validation for JSON objects
  packages/web3-eth-contract/src/contract.ts
  packages/web3-validator/src/utils.ts
  packages/web3-validator/test/fixtures/abi_to_json_schema.ts
  packages/web3-validator/test/unit/utils.test.ts
Labels: 4.x

#5324 Handling of the "null" response from provider
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-core/test/unit/web3_request_manager.test.ts
Labels: 4.x

#5323 Invalid `transactionPollingTimeout` compared to `transactionPollingInterval`
  packages/web3-core/src/web3_config.ts
  packages/web3-core/test/unit/__snapshots__/web3_context.test.ts.snap
  packages/web3-core/test/unit/web3_config.test.ts
  packages/web3-eth/test/integration/defaults.test.ts
Labels: 4.x

#5317 4xalphachangelog
  CHANGELOG.md
Labels: 4.x

#5325 Migration Guide - Review breaking changes by installing Truffle
  docs/docs/guides/web3_migration_guide.md
  docs/docs/guides/web3_utils_migration_guide.md
Labels: 4.x

#5328 4x doc updates 5326
  docs/docs/guides/net_migration_guide.md
  docs/docs/guides/providers_migration_guide.md
  docs/docusaurus.config.js
  docs/src/css/custom.css
  docs/src/pages/index.tsx
Labels: 4.x

#5338 call `Error.captureStackTrace(...)` only if available
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/web3_error_base.ts
  packages/web3-validator/package.json
  packages/web3-validator/src/errors.ts
Labels: 4.x

#5347 version fix 5341
  packages/web3/package.json
  packages/web3/src/version.ts
  packages/web3/src/web3.ts
Labels: 4.x

#5333 Enable subscribing to `error` event at `WebSocketProvider` underlying connection
  packages/web3-providers-ws/src/index.ts
  packages/web3-providers-ws/test/integration/web_socket_provider_integration.test.ts
Labels: 4.x

#5234 [README] Add GitPOAP Badge to Display Number of Minted GitPOAPs for Contributors
  README.md
Labels: Documentation, 1.x, Future Release

#5358 Fix syntax issue for relative links in README
  README.md
Labels: 1.x

#5359 Interrupt waiting for node after timeout (when sending a transaction or getting its receipt)
  CHANGELOG.md
  docs/docs/guides/web3_utils_migration_guide.md
  packages/web3-core/src/web3_config.ts
  packages/web3-core/test/unit/__snapshots__/web3_context.test.ts.snap
  packages/web3-core/test/unit/web3_config.test.ts
  packages/web3-errors/src/error_codes.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth/src/errors.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/wait_for_transaction_receipt.ts
  packages/web3-eth/test/integration/defaults.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_signed_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/send_transaction.test.ts
  packages/web3-utils/src/index.ts
  packages/web3-utils/src/promise_helpers.ts
Labels: 4.x

#5354 update node versions
  .github/workflows/build.yml
Labels: 1.x

#5357 Update `sha3` and `sha3Raw` type definitions to accept `Buffer`
  CHANGELOG.md
  docs/web3-utils.rst
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/sha3-raw-test.ts
  packages/web3-utils/types/tests/sha3-test.ts
Labels: 1.x

#5274 adding browser support polyfill
  CHANGELOG.md
  packages/web3/package.json
Labels: 1.x, Future Release

#5365 web build fix 5345
  packages/web3-validator/webpack.config.js
  packages/web3/src/index.ts
  packages/web3/src/web3.ts
  packages/web3/webpack.config.js
  webpack.base.config.js
Labels: 4.x

#5363 Block Schema Fix
  packages/web3-eth/src/schemas.ts
  packages/web3-eth/test/integration/rpc.block.test.ts
  packages/web3-utils/src/formatter.ts
Labels: 4.x

#5353 Black box tests
  .github/workflows/black_box_tests.yml
  package.json
  packages/web3-core/package.json
  packages/web3-core/src/web3_promi_event.ts
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/test/integration/contract_methods.test.ts
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-eth/src/index.ts
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ws/package.json
  packages/web3-types/package.json
  packages/web3-utils/package.json
  packages/web3-utils/src/web3_deferred_promise.ts
  packages/web3-validator/package.json
  packages/web3/package.json
  packages/web3/scripts/black_box_test.sh
  packages/web3/scripts/env.sh
  packages/web3/test/black_box/.yarnrc
  packages/web3/test/black_box/jest.config.js
  packages/web3/test/black_box/package.json
  packages/web3/test/black_box/test/batchRequest.test.ts
  packages/web3/test/black_box/test/fixtures/contracts/ERC20Token.ts
  packages/web3/test/black_box/test/fixtures/contracts/ERC721Token.ts
  packages/web3/test/black_box/test/web3-eth-accounts/create.test.ts
  packages/web3/test/black_box/test/web3-eth-accounts/hashMessage.test.ts
  packages/web3/test/black_box/test/web3-eth-contract/erc20.test.ts
  packages/web3/test/black_box/test/web3-eth/getBlock.test.ts
  packages/web3/test/black_box/test/web3-eth/getTransaction.test.ts
  packages/web3/test/black_box/yarn.lock
  scripts/ganache.sh
  scripts/geth.sh
  scripts/verdaccio.sh
  verdaccio.yml
  yarn.lock
Labels: 4.x

#5375 Release/4.0.0 alpha.0
  CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
Labels: Release, 4.x

#5371 Start incrementing jsonrpc message id from random number
  CHANGELOG.md
  packages/web3-core-requestmanager/src/jsonrpc.js
Labels: Bug, 1.x

#5381 Fix black_box_tests.yml
  .github/workflows/black_box_tests.yml
Labels: 4.x

#5384 Release/4.0.1 alpha.0
  CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-types/package.json
  packages/web3-utils/package.json
  packages/web3-validator/package.json
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-packagetemplate/package.json
Labels: Release, 4.x

#5390 Note for yarn users
  CHANGELOG.md
Labels: 4.x

#5273 implement handleRevert
  packages/web3-core/src/web3_config.ts
  packages/web3-errors/src/errors/transaction_errors.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3/test/integration/handle_revert.test.ts
  packages/web3/test/shared_fixtures/build
Labels: 4.x

#5394 Update contract class to not mutate options object
  CHANGELOG.md
  packages/web3-eth-contract/src/index.js
  test/contract.js
Labels: 1.x

#5392 Add console warn for empty web3js construction
  packages/web3/src/web3.ts
Labels: 4.x

#5385 Throw error on broken links in docs
  docs/docusaurus.config.js
Labels: 4.x
