Repository web3/web3.js, pull requests merged in 2022-07, with the labels that each got.

#5179 web3-providers-http: Migrate from xhr2-cookies to cross-fetch
  CHANGELOG.md
  package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-http/src/index.js
  packages/web3-providers-http/types/index.d.ts
  packages/web3-providers-http/types/tests/web3-provider-http-tests.ts
  test/helpers/FakeIpcProvider2.js
  test/helpers/FakeXHR2.js
  test/httpprovider.js
Labels: 1.x, Future Release

#5184 wallet.signTransaction fail with error
  packages/web3-common/src/web3_base_wallet.ts
  packages/web3-core/src/web3_context.ts
  packages/web3-eth-accounts/src/account.ts
  packages/web3-eth-accounts/src/index.ts
  packages/web3-eth-accounts/src/schemas.ts
  packages/web3-eth-accounts/src/types.ts
  packages/web3-eth-accounts/test/unit/account.test.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/prepare_transaction_for_signing.ts
  packages/web3/src/abi.ts
  packages/web3/src/accounts.ts
  packages/web3/src/types.ts
  packages/web3/src/web3.ts
  packages/web3/test/integration/web3.abi.test.ts
  packages/web3/test/integration/web3.accounts.test.ts
  packages/web3/test/integration/web3.test.ts
  packages/web3/test/integration/web3_external_providers.test.ts
  scripts/system_tests_utils.ts
Labels: 4.x

#5157 hexToNumber: return BigInt if result is bigger than max integer
  CHANGELOG.md
  docs/web3-eth.rst
  packages/web3-core-helpers/src/formatters.js
  packages/web3-core-method/src/index.js
  test/eth.getTransactionReceipt.js
Labels: 1.x

#5083 Fix transactionRoot -> transactionsRoot in BlockHeader
  CHANGELOG.md
  packages/web3-eth/types/index.d.ts
Labels: Types, 1.x, Future Release

#5192 5166/get accounts checksum address
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/integration/rpc.test.ts
Labels: 4.x

#5050 Problem deleting account when checksummed address is equal to lowercase address
  CHANGELOG.md
  packages/web3-eth-accounts/src/index.js
  test/eth.accounts.wallet.js
Labels: 1.x, Future Release

#5158 🏷️ Update AbstractProvider with correct typing
  CHANGELOG.md
  packages/web3-core/types/index.d.ts
Labels: Types, 1.x, Future Release

#5190 4.x compatibility issues with 1.x
  packages/web3-common/src/formatter.ts
  packages/web3-common/src/formatters.ts
  packages/web3-errors/src/errors/transaction_errors.ts
  packages/web3-errors/src/types.ts
  packages/web3-errors/test/unit/errors.test.ts
  packages/web3-eth-abi/src/api/logs_api.ts
  packages/web3-eth-accounts/src/account.ts
  packages/web3-eth-accounts/src/wallet.ts
  packages/web3-eth-accounts/test/unit/wallet.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/encoding.ts
  packages/web3-eth-contract/src/log_subscription.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-contract/src/utils.ts
  packages/web3-eth-contract/test/fixtures/encoding.ts
  packages/web3-eth-contract/test/integration/contract_deploy.test.ts
  packages/web3-eth-contract/test/integration/contract_erc20.test.ts
  packages/web3-eth-contract/test/integration/contract_erc721.test.ts
  packages/web3-eth-contract/test/integration/contract_events.test.ts
  packages/web3-eth-contract/test/unit/constructor.test.ts
  packages/web3-eth-contract/test/unit/contract.test.ts
  packages/web3-eth-contract/test/unit/encoding.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/utils/watch_transaction_for_confirmations.ts
  packages/web3-eth/src/validation.ts
  packages/web3-eth/test/integration/defaults.test.ts
  packages/web3-eth/test/integration/helper.ts
  packages/web3-eth/test/integration/rpc.test.ts
  packages/web3-eth/test/integration/subscription_logs.test.ts
  packages/web3-eth/test/integration/subscription_logs_block.test.ts
  packages/web3-eth/test/integration/watch_transaction.test.ts
  packages/web3-eth/test/integration/watch_transaction_polling.test.ts
  packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts
  packages/web3/src/accounts.ts
  packages/web3/src/web3.ts
  scripts/system_tests_utils.ts
  tools/eslint-config-web3-base/ts.js
Labels: 4.x

#5210 fix decode function. migration guide. fix unit tests
  CHANGELOG.md
  docs/docs/guides/abi_migration_guide.md
  packages/web3-eth-abi/src/api/logs_api.ts
  packages/web3-eth-abi/src/api/parameters_api.ts
  packages/web3-eth-abi/src/types.ts
  packages/web3-eth-abi/test/fixtures/data.ts
  packages/web3-eth-abi/test/unit/api/parameters_api.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/encoding.ts
  packages/web3-eth-contract/test/integration/contract_methods.test.ts
  packages/web3-eth/test/integration/rpc.test.ts
Labels: 4.x

#5205 Incompatible return types for 4.x implementations
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/errors/transaction_errors.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/fixtures/web3_eth_methods_with_parameters.ts
  packages/web3-eth/test/unit/web3_eth_methods_with_parameters.test.ts
Labels: 4.x

#5211 Upgrade ethereum-cryptography to 1.0
  packages/web3-eth-accounts/package.json
  packages/web3-eth-accounts/src/account.ts
  packages/web3-eth-accounts/test/fixtures/account.ts
  packages/web3-eth-accounts/test/unit/account.test.ts
  packages/web3-utils/package.json
  packages/web3-validator/package.json
  yarn.lock
Labels: 4.x

#5198 web3-common/core defaults documentation
  packages/web3-core/src/web3_config.ts
Labels: 4.x

#5136 Init web3_eth_migration_guide
  docs/docs/guides/web3_eth_migration_guide.md
  packages/web3-eth/src/web3_eth.ts
Labels: 4.x

#5209 Add documentation for breaking changes and migration guide
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3/CHANGELOG.md
Labels: 4.x

#5238 Add provider options migration guide
  docs/docs/guides/setting_provider.md
Labels: 4.x

#5080 Fix promise in `accounts.signTransaction()` throwing errors that cannot be caught
  CHANGELOG.md
  packages/web3-eth-accounts/src/index.js
  test/eth.accounts.signTransaction.js
Labels: Bug, 1.x, Future Release

#5254 1.x Libs Update including parse-url
  CHANGELOG.md
  package-lock.json
Labels: 1.x

#4955 Update index.d.ts
  packages/web3-eth-contract/types/index.d.ts
Labels: 1.x, Review Needed, Stale

#5245 4xdocfix
  docs/docs/guides/abi_migration_guide.md
  docs/docs/guides/accounts_migration_guide.md
  docs/docs/guides/contracts_migration_guide.md
  docs/docs/guides/intro.md
  docs/docs/guides/migration_guide.md
  docs/docs/guides/personal_migration_guide.md
  docs/docs/guides/setting_provider.md
  docs/docs/guides/web3_eth_migration_guide.md
  docs/docs/guides/web3_migration_guide.md
  docs/docusaurus.config.js
Labels: 4.x

#5221 ensure backward compatibility for Web3 constructor
  packages/web3-eth-accounts/src/index.ts
  packages/web3/src/index.ts
  packages/web3/test/integration/ipc.test.ts
  packages/web3/test/integration/web3.abi.test.ts
  packages/web3/test/integration/web3.accounts.test.ts
  packages/web3/test/integration/web3.test.ts
  packages/web3/test/integration/web3_external_providers.test.ts
Labels: 4.x

#5239 Migration Guide/Breaking Changes - Subscribe
  CHANGELOG.md
  docs/docs/guides/subscribe_migration_guide.md
  packages/web3-common/src/types.ts
  packages/web3-core/src/web3_subscription_manager.ts
  packages/web3-eth-accounts/src/account.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/utils/watch_transaction_for_confirmations.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/src/web3_subscriptions.ts
  packages/web3-eth/test/integration/subscription_heads.test.ts
Labels: 4.x

#5258 4975/net documentation
  docs/docs/guides/accounts_migration_guide.md
  docs/docs/guides/net_migration_guide.md
  packages/web3-net/src/index.ts
  packages/web3-net/src/net.ts
Labels: 4.x

#5275 Fix package versions for new packages
  packages/web3-core/package.json
  packages/web3-errors/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-types/package.json
  packages/web3-utils/package.json
  packages/web3-validator/package.json
  packages/web3/package.json
  tools/web3-packagetemplate/package.json
Labels: 4.x

#5276 :arrow_up: Update package dependencies
  package.json
  packages/web3-core/package.json
  packages/web3-core/src/web3_promi_event.ts
  packages/web3-core/test/unit/formatters.test.ts
  packages/web3-core/test/unit/web3_config.test.ts
  packages/web3-errors/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-eth/test/integration/defaults.test.ts
  packages/web3-net/package.json
  packages/web3-net/src/net.ts
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-types/package.json
  packages/web3-utils/package.json
  packages/web3-utils/src/hash.ts
  packages/web3-utils/src/web3_deferred_promise.ts
  packages/web3-validator/package.json
  packages/web3/package.json
  packages/web3/src/web3.ts
  tools/eslint-config-web3-base/package.json
  tools/web3-packagetemplate/package.json
  yarn.lock
Labels: 4.x

#5266 Change subscription's response format to web3.common format function
  packages/web3-core/src/formatters.ts
  packages/web3-core/src/web3_subscription_manager.ts
  packages/web3-core/src/web3_subscriptions.ts
  packages/web3-core/test/unit/formatters.test.ts
  packages/web3-core/test/unit/web3_subscription_manager.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/encoding.ts
  packages/web3-eth-contract/src/log_subscription.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-ens/src/ens.ts
  packages/web3-eth-ens/src/registry.ts
  packages/web3-eth-ens/src/resolver.ts
  packages/web3-eth/src/schemas.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/src/web3_subscriptions.ts
  packages/web3-types/src/eth_types.ts
  scripts/system_tests_utils.ts
Labels: 4.x

#5219 Update feeHistory Schema
  packages/web3-eth/src/schemas.ts
  packages/web3-eth/test/integration/web3_eth/getFeeHistory.test.ts
  packages/web3-types/src/eth_types.ts
Labels: 4.x

#5284 Polling for new blocks after blockHeaderTimeout passes or if error happened
  packages/web3-eth/src/utils/watch_transaction_for_confirmations.ts
  packages/web3-eth/test/integration/defaults.test.ts
Labels: 4.x

#5251 Web3Eth Docs
  packages/web3-eth/src/index.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/web3_eth.ts
Labels: 4.x
