Repository web3/web3.js, pull requests merged in 2023-03, with the labels that each got.

#5880 Nikos/fix ens event test
  packages/web3-eth-ens/test/integration/ens.events.test.ts
Labels: 4.x

#5884 Nikos/5835/websocket provider keeps important error message back
  CHANGELOG.md
  packages/web3-core-helpers/src/errors.js
  packages/web3-providers-ws/src/index.js
  test/websocket.ganache.js
Labels: 1.x

#5854 `sendTransaction` and `sendSignedTransaction` Error Refactors
  CHANGELOG.md
  docs/docs/guides/web3_migration_guide/providers_migration_guide.md
  docs/docs/guides/web3_providers_guide/index.md
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/errors/response_errors.ts
  packages/web3-errors/src/errors/transaction_errors.ts
  packages/web3-errors/test/unit/__snapshots__/errors.test.ts.snap
  packages/web3-errors/test/unit/errors.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/contract_defaults_extra.test.ts
  packages/web3-eth-contract/test/integration/contract_methods.test.ts
  packages/web3-eth-ens/src/registry.ts
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/types.ts
  packages/web3-eth/src/utils/get_revert_reason.ts
  packages/web3-eth/src/utils/get_transaction_error.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/integration/helper.ts
  packages/web3-eth/test/integration/web3_eth/send_signed_transaction.test.ts
  packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/send_signed_transaction.ts
  packages/web3-eth/test/unit/utils/get_revert_reason.test.ts
  packages/web3-eth/test/unit/utils/get_transaction_error.test.ts
  packages/web3-eth/test/unit/utils/parse_transaction_error.test.ts
  packages/web3/test/integration/handle_revert.test.ts
  scripts/system_tests_utils.ts
Labels: 4.x

#5914 Nikos/4967/web3 eth personal docs
  packages/web3-eth-personal/src/index.ts
  packages/web3-eth-personal/src/personal.ts
Labels: 4.x

#5910 Nikos/4966/abi documentation
  packages/web3-eth-abi/src/api/events_api.ts
  packages/web3-eth-abi/src/api/functions_api.ts
  packages/web3-eth-abi/src/api/logs_api.ts
  packages/web3-eth-abi/src/api/parameters_api.ts
  packages/web3-eth-abi/src/index.ts
Labels: 4.x

#5916 Update `CODEOWNERS` file to use `@web3/web3-js`
  .github/CODEOWNERS
Labels: 4.x

#5919 updates contracts' migration guide
  docs/docs/guides/web3_migration_guide/contracts_migration_guide.md
Labels: 4.x

#5926 Nikos/5883/4x integration fail test
  packages/web3-eth-contract/test/integration/contract_defaults_extra.test.ts
  packages/web3-eth/test/integration/defaults.transactionBlockTimeout.test.ts
Labels: 4.x

#5932 Add empty job to unstuck actions in 1.x
  .github/workflows/build.yml
Labels: 1.x

#5895 Release/1.9.0
  CHANGELOG.md
  dist/web3.min.js
  dist/web3.min.js.map
  lerna.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-eth2-beaconchain/package-lock.json
  packages/web3-eth2-beaconchain/package.json
  packages/web3-eth2-core/package-lock.json
  packages/web3-eth2-core/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: Release, 1.x

#5924 Add subscribe docs
  docs/docs/guides/web3_migration_guide/subscribe_migration_guide.md
  packages/web3-eth/src/index.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/src/web3_subscriptions.ts
Labels: 4.x

#5915 Use `gas` and `input` instead of `gasLimit` and `data`
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/src/formatters.ts
  packages/web3-core/test/unit/formatters.test.ts
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/errors/contract_errors.ts
  packages/web3-errors/src/errors/transaction_errors.ts
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-contract/src/utils.ts
  packages/web3-eth-contract/test/integration/contract_methods.test.ts
  packages/web3-eth-contract/test/unit/contract.test.ts
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/format_transaction.ts
  packages/web3-eth/src/utils/prepare_transaction_for_signing.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/src/validation.ts
  packages/web3-eth/test/fixtures/prepare_transaction_for_signing.ts
  packages/web3-eth/test/fixtures/validate_transaction_for_signing.ts
  packages/web3-eth/test/integration/web3_eth/sign_transaction.test.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  packages/web3-eth/test/unit/format_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_transaction.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_transaction.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/get_transaction_from_block.test.ts
  packages/web3-types/CHANGELOG.md
  packages/web3-types/src/eth_types.ts
  tools/web3-plugin-example/test/unit/contract_method_wrappers.test.ts
Labels: 4.x

#5952 Create CODEOWNERS
  .github/CODEOWNERS
Labels: 1.x

#5950 Replace `private _config` with `public config` in `web3_config.ts`
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/src/web3_config.ts
  packages/web3-core/src/web3_context.ts
  packages/web3-core/test/unit/web3_config.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/contract_defaults_extra.test.ts
  packages/web3-eth-contract/test/unit/contract.test.ts
Labels: 4.x

#5955 Improve logging of connection errors
  CHANGELOG.md
  packages/web3-providers-http/src/index.js
Labels: 1.x
