Repository web3/web3.js, pull requests merged in 2023-04, with the labels that each got.

#5979 Format `transaction.type` to hex. Add empty `accessList` is `tx.type === '0x1'`
  CHANGELOG.md
  packages/web3-core-helpers/src/formatters.js
  packages/web3-core-method/src/index.js
  test/e2e.method.send.js
  test/eth.sendTransaction.js
  test/formatters.inputTransactionFormatter.js
Labels: 1.x

#6019 Ganache tests fix
  packages/web3-eth/test/integration/web3_eth/call.test.ts
  packages/web3-eth/test/integration/web3_eth/estimate_gas.test.ts
  packages/web3-eth/test/integration/web3_eth/send_signed_transaction.test.ts
  packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts
  packages/web3/test/integration/external-providers/helper.ts
  packages/web3/test/integration/external-providers/truffle-hdwallet.test.ts
Labels: 4.x

#6016 Release/4.0.1 rc.1
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-packagetemplate/CHANGELOG.md
  tools/web3-packagetemplate/package.json
  tools/web3-plugin-example/CHANGELOG.md
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#5990 Init sepolia and mainnet testing
  .github/workflows/e2e_network_tests.yml
  .gitignore
  RELEASE.md
  package.json
  packages/web3/package.json
  packages/web3/test/e2e/e2e_utils.ts
  packages/web3/test/e2e/estimate_gas.test.ts
  packages/web3/test/e2e/fixtures/mainnet.ts
  packages/web3/test/e2e/fixtures/mainnet_block_hydrated.ts
  packages/web3/test/e2e/fixtures/sepolia.ts
  packages/web3/test/e2e/get_accounts.test.ts
  packages/web3/test/e2e/get_balance.test.ts
  packages/web3/test/e2e/get_block.test.ts
  packages/web3/test/e2e/get_block_number.test.ts
  packages/web3/test/e2e/get_block_transaction_count.test.ts
  packages/web3/test/e2e/get_block_uncle_count.test.ts
  packages/web3/test/e2e/get_chain_id.test.ts
  packages/web3/test/e2e/get_fee_history.test.ts
  packages/web3/test/e2e/get_gas_price.test.ts
  packages/web3/test/e2e/get_id.test.ts
  packages/web3/test/e2e/get_peer_count.test.ts
  packages/web3/test/e2e/get_proof.test.ts
  packages/web3/test/e2e/get_protocol_version.test.ts
  packages/web3/test/e2e/get_transaction_count.test.ts
  packages/web3/test/e2e/get_transaction_from_block.test.ts
  packages/web3/test/e2e/get_uncle.test.ts
  packages/web3/test/e2e/is_listening.test.ts
  packages/web3/test/e2e/is_syncing.test.ts
  packages/web3/test/e2e/jest.config.js
  packages/web3/test/e2e/mainnet/call.test.ts
  packages/web3/test/e2e/mainnet/get_code.test.ts
  packages/web3/test/e2e/mainnet/get_past_logs.test.ts
  packages/web3/test/e2e/mainnet/get_storage_at.test.ts
  packages/web3/test/e2e/mainnet/get_transaction.test.ts
  packages/web3/test/e2e/mainnet/get_transaction_receipt.test.ts
  packages/web3/test/e2e/sepolia/call.test.ts
  packages/web3/test/e2e/sepolia/contract.test.ts
  packages/web3/test/e2e/sepolia/get_code.test.ts
  packages/web3/test/e2e/sepolia/get_past_logs.test.ts
  packages/web3/test/e2e/sepolia/get_storage_at.test.ts
  packages/web3/test/e2e/sepolia/get_transaction.test.ts
  packages/web3/test/e2e/sepolia/get_transaction_receipt.test.ts
  packages/web3/test/e2e/sepolia/send_signed_transaction.test.ts
  packages/web3/test/e2e/setup.js
  packages/web3/test/shared_fixtures/utils.ts
  scripts/init.ts
  scripts/test-runner.sh
  templates/.secrets.json.tmpl
Labels: 4.x

#6001 schema with key or id already exists
  packages/web3-validator/src/web3_validator.ts
  packages/web3-validator/test/unit/web3_validator.test.ts
Labels: 4.x

#5960 Add types for user input in send/call
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/types.ts
  packages/web3-eth-contract/src/utils.ts
  packages/web3-types/CHANGELOG.md
  packages/web3-types/src/eth_contract_types.ts
Labels: 4.x
