Repository web3/web3.js, pull requests merged in 2023-06, with the labels that each got.

#6152 Release/4.0.1 rc.2
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#6140 Init simple overload contract test
  packages/web3-eth-contract/test/fixtures/SimpleOverloaded.ts
  packages/web3-eth-contract/test/fixtures/contracts/SimpleOverloaded.sol
  packages/web3-eth-contract/test/integration/contract_simple_overloaded.test.ts
Labels: 4.x

#6167 Event filtering using non/indexed string arguments
  CHANGELOG.md
  fixtures/build/Basic.json
  fixtures/build/Basic.ts
  fixtures/contracts/Basic.sol
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/src/api/logs_api.ts
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/src/encoding.ts
  packages/web3-eth-contract/test/integration/contract_filter_events.test.ts
  packages/web3-eth-contract/test/unit/encode_event_abi.test.ts
Labels: 4.x

#6174 Fix broken link to migration from 1.X
  README.md
Labels: Documentation, 4.x

#6166 6164 batch request fix
  packages/web3-core/CHANGELOG.md
  packages/web3-eth/test/integration/batch.test.ts
  packages/web3-utils/src/json_rpc.ts
Labels: 4.x

#6205 added ws types in dep
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3/CHANGELOG.md
Labels: 4.x

#6194 Add `.on('error')` test for reverted contract methods
  packages/web3-eth-contract/test/integration/contract_methods_errors.test.ts
Labels: 4.x

#6221 Add tests for using `int`s in contracts, and test case for `web3-eth-abi`'s `encodeFunctionCall`
  fixtures/build/NegativeNumbers.json
  fixtures/build/NegativeNumbers.ts
  fixtures/contracts/NegativeNumbers.sol
  packages/web3-eth-abi/test/fixtures/data.ts
  packages/web3-eth-contract/test/integration/contract_negative_numbers.test.ts
Labels: 4.x

#6226 Release/4.0.2
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
Labels: Release, 4.x

#6238 Bump `typescript` to `4.9.5` and `ts-node` to `10.9.1`
  CHANGELOG.md
  dist/web3.min.js.LICENSE.txt
  package-lock.json
  package.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-ens/types/tests/ens-test.ts
  packages/web3-eth-ens/types/tslint.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-eth2-beaconchain/package.json
  packages/web3-eth2-core/package.json
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package.json
  packages/web3-utils/package.json
  packages/web3-utils/types/tests/check-address-checksum-test.ts
  packages/web3/package.json
Labels: 1.x

#6239 Fix for ABI encoding large negative ints
  CHANGELOG.md
  packages/web3-eth-abi/src/index.js
  test/eth.abi.encodeParameter.js
Labels: 1.x
