Repository web3/web3.js, pull requests merged in 2023-08, with the labels that each got.

#6325 1x doc updates
  README.md
  docs/index.rst
Labels: 1.x

#6324 1x code owners update
  .github/CODEOWNERS
Labels: 1.x

#6323 4x code owners update
  .github/CODEOWNERS
Labels: 4.x

#6294 Transaction `input` and `data` refactors
  CHANGELOG.md
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/decode_signed_transaction.ts
  packages/web3-eth/src/utils/format_transaction.ts
  packages/web3-eth/src/utils/prepare_transaction_for_signing.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/test/integration/web3_eth/sign_transaction.test.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_pending_transactions.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_transaction.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/get_transaction_from_block.ts
  packages/web3-eth/test/unit/rpc_method_wrappers/fixtures/sign_transaction.ts
  packages/web3-types/CHANGELOG.md
  packages/web3-types/src/eth_types.ts
Labels: 4.x

#6329 Release/1.10.1
  CHANGELOG.md
  dist/web3.min.js
  dist/web3.min.js.LICENSE.txt
  dist/web3.min.js.map
  lerna.json
  package-lock.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-eth2-beaconchain/package-lock.json
  packages/web3-eth2-beaconchain/package.json
  packages/web3-eth2-core/package-lock.json
  packages/web3-eth2-core/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: Release, 1.x

#6342 Release/4.1.0
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-plugin-example/CHANGELOG.md
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#6346 6306 allEvents bug fix
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/contract_events.test.ts
  packages/web3-eth-contract/test/unit/contract.test.ts
Labels: 4.x

#6362 ESM import fix
  package.json
  packages/.prettierignore
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/src/errors/rpc_error_messages.ts
  packages/web3-eth-accounts/src/tx/types.ts
  packages/web3-types/src/web3_base_provider.ts
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/src/validation/abi.ts
  packages/web3-validator/src/validator.ts
  tools/eslint-config-web3-base/ts-jest.js
  tools/eslint-config-web3-base/ts.js
  tools/web3-plugin-example/src/contract_method_wrappers.ts
  tools/web3-plugin-example/src/custom_rpc_methods.ts
  yarn.lock
Labels: 4.x

#6367 Release/4.1.1
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-plugin-example/CHANGELOG.md
  tools/web3-plugin-example/package.json
Labels: Release, 4.x
