Repository web3/web3.js, pull requests merged in 2023-01, with the labels that each got.

#5715 Parameters decoding error for nested components
  CHANGELOG.md
  packages/web3-eth-abi/src/api/logs_api.ts
  packages/web3-eth-abi/src/api/parameters_api.ts
  packages/web3-eth-abi/src/types.ts
  packages/web3-eth-abi/test/fixtures/data.ts
  packages/web3-eth-abi/test/unit/api/parameters_api.test.ts
Labels: 4.x

#5710 Fix Webpack Build for `web3-validator`
  CHANGELOG.md
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3-validator/webpack.config.js
  scripts/verdaccio.sh
Labels: 4.x

#5671 Update 1.x tests infrastructure/libs
  TESTING.md
  package-lock.json
  package.json
  scripts/e2e.chrome.sh
  scripts/e2e.firefox.sh
  scripts/e2e.ganache.sh
  test/3_givenProvider-ganache.js
  test/e2e.contract.events.js
  test/e2e.method.send.js
  test/e2e.method.signing.js
  test/eth.subscribe.ganache.js
  test/websocket.ganache.js
Labels: 1.x, dependencies

#5659 Nikos/5482/implement tests for eip 838 errors with local contract deployment
  fixtures/build/ErrorsContract.json
  fixtures/build/ErrorsContract.ts
  fixtures/contracts/ErrorsContract.sol
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth-contract/test/integration/contract_methods.test.ts
  packages/web3-eth-contract/test/integration/contract_methods_errors.test.ts
  packages/web3-eth-contract/test/unit/contract.test.ts
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/types.ts
Labels: 4.x

#5725 Release/4.0.1 alpha.3
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-plugin-example/CHANGELOG.md
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#5727 update1xdependencies
  CHANGELOG.md
  package-lock.json
Labels: 1.x

#5741 using latest lighthouse docker image in tests
  scripts/eth2.sh
Labels: 1.x

#5750 Build for 4.0.1-alpha.4
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-packagetemplate/package.json
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#5731 Nikos/5711/transaction with local wallet index should support to as a wallet index
  CHANGELOG.md
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/errors/transaction_errors.ts
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/src/rpc_method_wrappers.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/src/web3_eth.ts
  packages/web3-eth/test/integration/defaults.test.ts
  packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts
  packages/web3-types/CHANGELOG.md
  packages/web3-types/src/eth_types.ts
Labels: 4.x

#5755 Remove `browser` entry from `web3` and `web3-validator` `package.json`s
  CHANGELOG.md
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
Labels: 4.x

#5757 v4.0.1-alpha.5
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-packagetemplate/package.json
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#5735 5035/exception code
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/src/web3_config.ts
  packages/web3-core/src/web3_context.ts
  packages/web3-core/src/web3_request_manager.ts
  packages/web3-core/test/unit/__snapshots__/web3_context.test.ts.snap
  packages/web3-core/test/unit/web3_config.test.ts
  packages/web3-core/test/unit/web3_request_manager.test.ts
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/errors/rpc_errors.ts
  packages/web3-errors/src/index.ts
  packages/web3-eth/test/integration/defaults.test.ts
  packages/web3-utils/src/json_rpc.ts
Labels: Feature Request, 4.x

#5767 updated current release process
  RELEASE.md
Labels: 4.x

#5765 Update node minimum version to 14
  package.json
  packages/web3-core/package.json
  packages/web3-errors/package.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package.json
  packages/web3-net/package.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/package.json
  packages/web3-types/package.json
  packages/web3-utils/package.json
  packages/web3-validator/package.json
  packages/web3/package.json
  tools/web3-packagetemplate/package.json
  tools/web3-plugin-example/package.json
Labels: 4.x

#5740 1.8.2
  CHANGELOG.md
  dist/web3.min.js
  dist/web3.min.js.map
  lerna.json
  package-lock.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-eth2-beaconchain/package-lock.json
  packages/web3-eth2-beaconchain/package.json
  packages/web3-eth2-core/package-lock.json
  packages/web3-eth2-core/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: Release, 1.x

#5784 Spelling correction API Reference -> Web3 -> utils #5758 Solved
  docs/web3.rst
Labels: 1.x

#5734 Fix: minor typos
  docs/glossary.rst
  docs/web3-bzz.rst
  docs/web3-eth-abi.rst
Labels: Documentation, 1.x, Future Release

#5792 5704 memory leak in web3.eth.contract
  CHANGELOG.md
  packages/web3-eth/src/web3_eth.ts
  packages/web3/CHANGELOG.md
  packages/web3/src/types.ts
  packages/web3/src/web3.ts
  packages/web3/test/integration/web3.setProvider.test.ts
  scripts/system_tests_utils.ts
Labels: 4.x
