Repository web3/web3.js, pull requests merged in 2023-07, with the labels that each got.

#6266 Release/4.0.3
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-plugin-example/CHANGELOG.md
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#6229 1.x - update submit work and contract.myMethod.send docs
  CHANGELOG.md
  docs/web3-eth-contract.rst
  docs/web3-eth.rst
  packages/web3-eth/types/index.d.ts
  packages/web3-eth/types/tests/eth.tests.ts
Labels: Documentation, 1.x

#6243 Add missing `blockHeaderSchema` properties
  CHANGELOG.md
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-eth/src/schemas.ts
  packages/web3-eth/test/e2e/accounts.json
  packages/web3-eth/test/e2e/e2e_utils.ts
  packages/web3-eth/test/e2e/jest.config.js
  packages/web3-eth/test/e2e/setup.js
  packages/web3-eth/test/e2e/subscription_new_heads.test.ts
  packages/web3-eth/test/integration/subscription_heads.test.ts
  packages/web3-types/src/eth_types.ts
Labels: 4.x
