Repository web3/web3.js, pull requests merged in 2023-05, with the labels that each got.

#6044 1x update
  CHANGELOG.md
  README.md
  docs/index.rst
  package-lock.json
  packages/web3-bzz/package-lock.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core/package-lock.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth2-beaconchain/package-lock.json
  packages/web3-eth2-core/package-lock.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-shh/package-lock.json
  packages/web3-utils/package-lock.json
  packages/web3/README.md
  packages/web3/package-lock.json
Labels: 1.x

#5888 refactor: Remove the unnecessary chainId parameter
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/to-check-sum-address-test.ts
Labels: Types, 1.x

#6057 Remove the unnecessary chainId parameter (#5888)
  CHANGELOG.md
  packages/web3-utils/types/index.d.ts
  packages/web3-utils/types/tests/to-check-sum-address-test.ts
Labels: 1.x

#6046 updated doc links
  README.md
  packages/web3/README.md
Labels: 4.x

#6058 Release/1.10.0
  CHANGELOG.md
  dist/web3.min.js
  dist/web3.min.js.map
  lerna.json
  package-lock.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-eth2-beaconchain/package-lock.json
  packages/web3-eth2-beaconchain/package.json
  packages/web3-eth2-core/package-lock.json
  packages/web3-eth2-core/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: Release, 1.x

#6073 updated the file
  README.md
Labels: 4.x

#6080 Update `formatTransaction` to not delete `data` property
  packages/web3-eth/src/utils/format_transaction.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/test/integration/web3_eth/send_transaction.test.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  tools/web3-plugin-example/test/unit/contract_method_wrappers.test.ts
Labels: 4.x

#6102 `defaultTransactionTypeParser` Refactor
  CHANGELOG.md
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/src/error_codes.ts
  packages/web3-errors/src/errors/transaction_errors.ts
  packages/web3-errors/test/unit/__snapshots__/errors.test.ts.snap
  packages/web3-errors/test/unit/errors.test.ts
  packages/web3-eth-contract/src/contract.ts
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/src/utils/detect_transaction_type.ts
  packages/web3-eth/test/fixtures/detect_transaction_type.ts
  packages/web3-eth/test/fixtures/prepare_transaction_for_signing.ts
  packages/web3-eth/test/integration/defaults.test.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  packages/web3-eth/test/unit/detect_transction_type.test.ts
  packages/web3-types/CHANGELOG.md
  packages/web3-types/src/error_types.ts
  packages/web3-types/src/eth_types.ts
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/src/errors.ts
  packages/web3-validator/src/types.ts
  packages/web3-validator/src/validator.ts
  packages/web3-validator/src/web3_validator.ts
  packages/web3-validator/test/unit/error.test.ts
Labels: 4.x

#6071 transaction integration tests
  packages/web3-core/src/web3_context.ts
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/src/utils/prepare_transaction_for_signing.ts
  packages/web3-eth/src/utils/transaction_builder.ts
  packages/web3-eth/test/unit/default_transaction_builder.test.ts
  packages/web3-eth/test/unit/prepare_transaction_for_signing.test.ts
  packages/web3/test/fixtures/transactions.json
  packages/web3/test/integration/web3.accounts.test.ts
  packages/web3/test/integration/web3.eth.transaction.test.ts
  scripts/system_tests_utils.ts
Labels: 4.x

#6130 migration guide update
  docs/docs/guides/web3_migration_guide/web3_eth_ens.md
Labels: 4.x
