Repository web3/web3.js, pull requests merged in 2023-10, with the labels that each got.

#6466 feature - add privateKeyToPublicKey function
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/src/account.ts
  packages/web3-eth-accounts/test/fixtures/account.ts
  packages/web3-eth-accounts/test/unit/account.test.ts
Labels: Feature Request, 4.x

#6473 fix stale.yml
  .github/workflows/stale.yml
Labels: Bug, 4.x

#6464 waitForTransactionReceipt fix
  packages/web3-eth/src/utils/wait_for_transaction_receipt.ts
  packages/web3-eth/test/integration/defaults.transactionBlockTimeout.test.ts
  packages/web3-eth/test/unit/utils/wait_for_transaction_receipt.test.ts
  packages/web3-utils/src/promise_helpers.ts
  packages/web3-utils/test/unit/promise_helpers.test.ts
Labels: 4.x

#6474 web3-eth-contract validation test fail
  packages/web3-eth-contract/test/integration/local_account/contract_erc721.test.ts
Labels: Bug, 4.x

#6510 Release/1.10.3
  CHANGELOG.md
  dist/web3.min.js
  dist/web3.min.js.map
  lerna.json
  package-lock.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-eth2-beaconchain/package-lock.json
  packages/web3-eth2-beaconchain/package.json
  packages/web3-eth2-core/package-lock.json
  packages/web3-eth2-core/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: Release, 1.x

#6517 Release/4.2.0
  CHANGELOG.md
  packages/web3-core/CHANGELOG.md
  packages/web3-core/package.json
  packages/web3-errors/CHANGELOG.md
  packages/web3-errors/package.json
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/CHANGELOG.md
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/CHANGELOG.md
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3-net/CHANGELOG.md
  packages/web3-net/package.json
  packages/web3-providers-http/CHANGELOG.md
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/CHANGELOG.md
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/CHANGELOG.md
  packages/web3-providers-ws/package.json
  packages/web3-rpc-methods/CHANGELOG.md
  packages/web3-rpc-methods/package.json
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3-validator/CHANGELOG.md
  packages/web3-validator/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-plugin-example/CHANGELOG.md
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#6545 4.2.1 draft release
  CHANGELOG.md
  packages/web3-eth-abi/CHANGELOG.md
  packages/web3-eth-abi/package.json
  packages/web3-eth-contract/CHANGELOG.md
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/CHANGELOG.md
  packages/web3-eth-ens/package.json
  packages/web3-eth-personal/CHANGELOG.md
  packages/web3-eth-personal/package.json
  packages/web3-eth/CHANGELOG.md
  packages/web3-eth/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/src/version.ts
  tools/web3-plugin-example/package.json
Labels: Release, 4.x

#6550 1x release process
  RELEASE.md
Labels: 1.x

#6549 release process update
  RELEASE.md
Labels: 4.x
