Repository web3/web3.js, pull requests merged in 2024-02, with the labels that each got.

#6755 Release/1.10.4
  CHANGELOG.md
  dist/web3.min.js
  dist/web3.min.js.LICENSE.txt
  dist/web3.min.js.map
  lerna.json
  package-lock.json
  packages/web3-bzz/package-lock.json
  packages/web3-bzz/package.json
  packages/web3-core-helpers/package-lock.json
  packages/web3-core-helpers/package.json
  packages/web3-core-method/package-lock.json
  packages/web3-core-method/package.json
  packages/web3-core-promievent/package.json
  packages/web3-core-requestmanager/package.json
  packages/web3-core-subscriptions/package-lock.json
  packages/web3-core-subscriptions/package.json
  packages/web3-core/package-lock.json
  packages/web3-core/package.json
  packages/web3-eth-abi/package-lock.json
  packages/web3-eth-abi/package.json
  packages/web3-eth-accounts/package-lock.json
  packages/web3-eth-accounts/package.json
  packages/web3-eth-contract/package-lock.json
  packages/web3-eth-contract/package.json
  packages/web3-eth-ens/package-lock.json
  packages/web3-eth-ens/package.json
  packages/web3-eth-iban/package-lock.json
  packages/web3-eth-iban/package.json
  packages/web3-eth-personal/package-lock.json
  packages/web3-eth-personal/package.json
  packages/web3-eth/package-lock.json
  packages/web3-eth/package.json
  packages/web3-eth2-beaconchain/package-lock.json
  packages/web3-eth2-beaconchain/package.json
  packages/web3-eth2-core/package-lock.json
  packages/web3-eth2-core/package.json
  packages/web3-net/package-lock.json
  packages/web3-net/package.json
  packages/web3-providers-http/package-lock.json
  packages/web3-providers-http/package.json
  packages/web3-providers-ipc/package-lock.json
  packages/web3-providers-ipc/package.json
  packages/web3-providers-ws/package-lock.json
  packages/web3-providers-ws/package.json
  packages/web3-shh/package-lock.json
  packages/web3-shh/package.json
  packages/web3-utils/package-lock.json
  packages/web3-utils/package.json
  packages/web3/package-lock.json
  packages/web3/package.json
Labels: Release, 1.x

#6802 Release/4.5.0
  CHANGELOG.md
  packages/web3-types/CHANGELOG.md
  packages/web3-types/package.json
  packages/web3-utils/CHANGELOG.md
  packages/web3-utils/package.json
  packages/web3/CHANGELOG.md
  packages/web3/package.json
  packages/web3/scripts/black_box_test.sh
  packages/web3/src/version.ts
Labels: Release, 4.x

#6825 6201 multi provider
  docs/docs/guides/web3_providers_guide/eip6963.md
  docs/docs/guides/web3_providers_guide/events_listening.md
  docs/docs/guides/web3_providers_guide/http.md
  docs/docs/guides/web3_providers_guide/injected_provider.md
  docs/docs/guides/web3_providers_guide/ipc.md
  docs/docs/guides/web3_providers_guide/truffle.md
  docs/docs/guides/web3_providers_guide/websocket.md
  packages/web3/CHANGELOG.md
  packages/web3/src/web3.ts
  packages/web3/src/web3_eip6963.ts
  packages/web3/test/unit/constructor.test.ts
  packages/web3/test/unit/web3eip6963.test.ts
Labels: 4.x
